scoreboard players tag @a add AirInSlot18 {Inventory:[{Slot:18b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot18 {Inventory:[{Slot:18b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot18 {Inventory:[{Slot:18b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot18 {Inventory:[{Slot:18b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot18 {Inventory:[{Slot:18b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot18 {Inventory:[{Slot:18b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot18 {Inventory:[{Slot:18b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot18 {Inventory:[{Slot:18b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot18 {Inventory:[{Slot:18b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot18 {Inventory:[{Slot:18b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot18 {Inventory:[{Slot:18b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot18 {Inventory:[{Slot:18b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot18 {Inventory:[{Slot:18b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot18 {Inventory:[{Slot:18b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot18 {Inventory:[{Slot:18b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot18 {Inventory:[{Slot:18b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot18 {Inventory:[{Slot:18b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot18 {Inventory:[{Slot:18b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot18 {Inventory:[{Slot:18b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot18 {Inventory:[{Slot:18b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot18 {Inventory:[{Slot:18b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot18 {Inventory:[{Slot:18b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot18 {Inventory:[{Slot:18b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot18 {Inventory:[{Slot:18b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot18 {Inventory:[{Slot:18b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot18 {Inventory:[{Slot:18b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot18 {Inventory:[{Slot:18b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot18 {Inventory:[{Slot:18b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot18 {Inventory:[{Slot:18b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot18 {Inventory:[{Slot:18b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot18 {Inventory:[{Slot:18b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot18 {Inventory:[{Slot:18b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot18 {Inventory:[{Slot:18b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:structure_block",Damage:0s}]}
