scoreboard players tag @s add AirInSlot14 {Inventory:[{Slot:14b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot14 {Inventory:[{Slot:14b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot14 {Inventory:[{Slot:14b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot14 {Inventory:[{Slot:14b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot14 {Inventory:[{Slot:14b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot14 {Inventory:[{Slot:14b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot14 {Inventory:[{Slot:14b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot14 {Inventory:[{Slot:14b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot14 {Inventory:[{Slot:14b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot14 {Inventory:[{Slot:14b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot14 {Inventory:[{Slot:14b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot14 {Inventory:[{Slot:14b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot14 {Inventory:[{Slot:14b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot14 {Inventory:[{Slot:14b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot14 {Inventory:[{Slot:14b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot14 {Inventory:[{Slot:14b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot14 {Inventory:[{Slot:14b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot14 {Inventory:[{Slot:14b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot14 {Inventory:[{Slot:14b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot14 {Inventory:[{Slot:14b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot14 {Inventory:[{Slot:14b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot14 {Inventory:[{Slot:14b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot14 {Inventory:[{Slot:14b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot14 {Inventory:[{Slot:14b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot14 {Inventory:[{Slot:14b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot14 {Inventory:[{Slot:14b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot14 {Inventory:[{Slot:14b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot14 {Inventory:[{Slot:14b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot14 {Inventory:[{Slot:14b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot14 {Inventory:[{Slot:14b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot14 {Inventory:[{Slot:14b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot14 {Inventory:[{Slot:14b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot14 {Inventory:[{Slot:14b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot14 {Inventory:[{Slot:14b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot14 {Inventory:[{Slot:14b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot14 {Inventory:[{Slot:14b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot14 {Inventory:[{Slot:14b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot14 {Inventory:[{Slot:14b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot14 {Inventory:[{Slot:14b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot14 {Inventory:[{Slot:14b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot14 {Inventory:[{Slot:14b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot14 {Inventory:[{Slot:14b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot14 {Inventory:[{Slot:14b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot14 {Inventory:[{Slot:14b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot14 {Inventory:[{Slot:14b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot14 {Inventory:[{Slot:14b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot14 {Inventory:[{Slot:14b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot14 {Inventory:[{Slot:14b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot14 {Inventory:[{Slot:14b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot14 {Inventory:[{Slot:14b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot14 {Inventory:[{Slot:14b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot14 {Inventory:[{Slot:14b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot14 {Inventory:[{Slot:14b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot14 {Inventory:[{Slot:14b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot14 {Inventory:[{Slot:14b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot14 {Inventory:[{Slot:14b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot14 {Inventory:[{Slot:14b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot14 {Inventory:[{Slot:14b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot14 {Inventory:[{Slot:14b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot14 {Inventory:[{Slot:14b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot14 {Inventory:[{Slot:14b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot14 {Inventory:[{Slot:14b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot14 {Inventory:[{Slot:14b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot14 {Inventory:[{Slot:14b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot14 {Inventory:[{Slot:14b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot14 {Inventory:[{Slot:14b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot14 {Inventory:[{Slot:14b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot14 {Inventory:[{Slot:14b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot14 {Inventory:[{Slot:14b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot14 {Inventory:[{Slot:14b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot14 {Inventory:[{Slot:14b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot14 {Inventory:[{Slot:14b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot14 {Inventory:[{Slot:14b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot14 {Inventory:[{Slot:14b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot14 {Inventory:[{Slot:14b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot14 {Inventory:[{Slot:14b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot14 {Inventory:[{Slot:14b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot14 {Inventory:[{Slot:14b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot14 {Inventory:[{Slot:14b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot14 {Inventory:[{Slot:14b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot14 {Inventory:[{Slot:14b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot14 {Inventory:[{Slot:14b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot14 {Inventory:[{Slot:14b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot14 {Inventory:[{Slot:14b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot14 {Inventory:[{Slot:14b,id:"minecraft:structure_block",Damage:0s}]}
