scoreboard players tag @s add AirInSlot20 {Inventory:[{Slot:20b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot20 {Inventory:[{Slot:20b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot20 {Inventory:[{Slot:20b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot20 {Inventory:[{Slot:20b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot20 {Inventory:[{Slot:20b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot20 {Inventory:[{Slot:20b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot20 {Inventory:[{Slot:20b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot20 {Inventory:[{Slot:20b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot20 {Inventory:[{Slot:20b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot20 {Inventory:[{Slot:20b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot20 {Inventory:[{Slot:20b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot20 {Inventory:[{Slot:20b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot20 {Inventory:[{Slot:20b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot20 {Inventory:[{Slot:20b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot20 {Inventory:[{Slot:20b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot20 {Inventory:[{Slot:20b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot20 {Inventory:[{Slot:20b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot20 {Inventory:[{Slot:20b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot20 {Inventory:[{Slot:20b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot20 {Inventory:[{Slot:20b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot20 {Inventory:[{Slot:20b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot20 {Inventory:[{Slot:20b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot20 {Inventory:[{Slot:20b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot20 {Inventory:[{Slot:20b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot20 {Inventory:[{Slot:20b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot20 {Inventory:[{Slot:20b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot20 {Inventory:[{Slot:20b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot20 {Inventory:[{Slot:20b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot20 {Inventory:[{Slot:20b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot20 {Inventory:[{Slot:20b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot20 {Inventory:[{Slot:20b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot20 {Inventory:[{Slot:20b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot20 {Inventory:[{Slot:20b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot20] ~ ~ ~ execute @s[tag=!StoneInSlot20] ~ ~ ~ execute @s[tag=!GraniteInSlot20] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot20] ~ ~ ~ execute @s[tag=!DioriteInSlot20] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot20] ~ ~ ~ execute @s[tag=!AndesiteInSlot20] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot20] ~ ~ ~ execute @s[tag=!GrassBlockInSlot20] ~ ~ ~ execute @s[tag=!DirtInSlot20] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot20] ~ ~ ~ execute @s[tag=!PodzolInSlot20] ~ ~ ~ execute @s[tag=!CobblestoneInSlot20] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot20] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot20] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot20] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot20] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot20] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot20] ~ ~ ~ execute @s[tag=!OakSaplingInSlot20] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot20] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot20] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot20] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot20] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot20] ~ ~ ~ execute @s[tag=!BedrockInSlot20] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot20] ~ ~ ~ execute @s[tag=!StillWaterInSlot20] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot20] ~ ~ ~ execute @s[tag=!StillLavaInSlot20] ~ ~ ~ execute @s[tag=!SandInSlot20] ~ ~ ~ execute @s[tag=!RedSandInSlot20] ~ ~ ~ execute @s[tag=!GravelInSlot20] ~ ~ ~ execute @s[tag=!GoldOreInSlot20] ~ ~ ~ execute @s[tag=!IronOreInSlot20] ~ ~ ~ execute @s[tag=!CoalOreInSlot20] ~ ~ ~ execute @s[tag=!OakWoodInSlot20] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot20] ~ ~ ~ execute @s[tag=!BirchWoodInSlot20] ~ ~ ~ execute @s[tag=!JungleWoodInSlot20] ~ ~ ~ execute @s[tag=!OakLeavesInSlot20] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot20] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot20] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot20] ~ ~ ~ execute @s[tag=!SpongeInSlot20] ~ ~ ~ execute @s[tag=!WetSpongeInSlot20] ~ ~ ~ execute @s[tag=!GlassInSlot20] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot20] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot20] ~ ~ ~ execute @s[tag=!DispenserInSlot20] ~ ~ ~ execute @s[tag=!SandstoneInSlot20] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot20] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot20] ~ ~ ~ execute @s[tag=!NoteBlockInSlot20] ~ ~ ~ execute @s[tag=!BedInSlot20] ~ ~ ~ execute @s[tag=!PoweredRailInSlot20] ~ ~ ~ execute @s[tag=!DetectorRailInSlot20] ~ ~ ~ execute @s[tag=!StickyPistonInSlot20] ~ ~ ~ execute @s[tag=!CobwebInSlot20] ~ ~ ~ execute @s[tag=!DeadShrubInSlot20] ~ ~ ~ execute @s[tag=!GrassInSlot20] ~ ~ ~ execute @s[tag=!FernInSlot20] ~ ~ ~ execute @s[tag=!DeadBushInSlot20] ~ ~ ~ execute @s[tag=!PistonInSlot20] ~ ~ ~ execute @s[tag=!PistonHeadInSlot20] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot20] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot20] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot20] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot20] ~ ~ ~ execute @s[tag=!YellowWoolInSlot20] ~ ~ ~ execute @s[tag=!LimeWoolInSlot20] ~ ~ ~ execute @s[tag=!PinkWoolInSlot20] ~ ~ ~ execute @s[tag=!GrayWoolInSlot20] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot20] ~ ~ ~ execute @s[tag=!CyanWoolInSlot20] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot20] ~ ~ ~ execute @s[tag=!BlueWoolInSlot20] ~ ~ ~ execute @s[tag=!BrownWoolInSlot20] ~ ~ ~ execute @s[tag=!GreenWoolInSlot20] ~ ~ ~ execute @s[tag=!RedWoolInSlot20] ~ ~ ~ execute @s[tag=!BlackWoolInSlot20] ~ ~ ~ execute @s[tag=!DandelionInSlot20] ~ ~ ~ execute @s[tag=!PoppyInSlot20] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot20] ~ ~ ~ execute @s[tag=!AlliumInSlot20] ~ ~ ~ execute @s[tag=!AzureBluetInSlot20] ~ ~ ~ execute @s[tag=!RedTulipInSlot20] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot20] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot20] ~ ~ ~ execute @s[tag=!PinkTulipInSlot20] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot20] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot20] ~ ~ ~ execute @s[tag=!RedMushroomInSlot20] ~ ~ ~ execute @s[tag=!GoldBlockInSlot20] ~ ~ ~ execute @s[tag=!IronBlockInSlot20] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot20] ~ ~ ~ execute @s[tag=!StoneSlabInSlot20] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot20] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot20] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot20] ~ ~ ~ execute @s[tag=!BrickSlabInSlot20] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot20] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot20] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot20] ~ ~ ~ execute @s[tag=!BricksInSlot20] ~ ~ ~ execute @s[tag=!TNTInSlot20] ~ ~ ~ execute @s[tag=!BookshelfInSlot20] ~ ~ ~ execute @s[tag=!MossStoneInSlot20] ~ ~ ~ execute @s[tag=!ObsidianInSlot20] ~ ~ ~ execute @s[tag=!TorchInSlot20] ~ ~ ~ execute @s[tag=!FireInSlot20] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot20] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot20] ~ ~ ~ execute @s[tag=!ChestInSlot20] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot20] ~ ~ ~ execute @s[tag=!DiamondOreInSlot20] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot20] ~ ~ ~ execute @s[tag=!CraftingTableInSlot20] ~ ~ ~ execute @s[tag=!WheatCropsInSlot20] ~ ~ ~ execute @s[tag=!FarmlandInSlot20] ~ ~ ~ execute @s[tag=!FurnaceInSlot20] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot20] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot20] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!LadderInSlot20] ~ ~ ~ execute @s[tag=!RailInSlot20] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot20] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot20] ~ ~ ~ execute @s[tag=!LeverInSlot20] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot20] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot20] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot20] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot20] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot20] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot20] ~ ~ ~ execute @s[tag=!StoneButtonInSlot20] ~ ~ ~ execute @s[tag=!SnowInSlot20] ~ ~ ~ execute @s[tag=!IceInSlot20] ~ ~ ~ execute @s[tag=!SnowBlockInSlot20] ~ ~ ~ execute @s[tag=!CactusInSlot20] ~ ~ ~ execute @s[tag=!SugarCanesInSlot20] ~ ~ ~ execute @s[tag=!JukeboxInSlot20] ~ ~ ~ execute @s[tag=!OakFenceInSlot20] ~ ~ ~ execute @s[tag=!PumpkinInSlot20] ~ ~ ~ execute @s[tag=!NetherrackInSlot20] ~ ~ ~ execute @s[tag=!SoulSandInSlot20] ~ ~ ~ execute @s[tag=!GlowstoneInSlot20] ~ ~ ~ execute @s[tag=!NetherPortalInSlot20] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot20] ~ ~ ~ execute @s[tag=!CakeBlockInSlot20] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot20] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot20] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot20] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot20] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot20] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot20] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot20] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot20] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot20] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot20] ~ ~ ~ execute @s[tag=!StoneBricksInSlot20] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot20] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot20] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot20] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot20] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot20] ~ ~ ~ execute @s[tag=!IronBarsInSlot20] ~ ~ ~ execute @s[tag=!GlassPaneInSlot20] ~ ~ ~ execute @s[tag=!MelonBlockInSlot20] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot20] ~ ~ ~ execute @s[tag=!MelonStemInSlot20] ~ ~ ~ execute @s[tag=!VinesInSlot20] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot20] ~ ~ ~ execute @s[tag=!BrickStairsInSlot20] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot20] ~ ~ ~ execute @s[tag=!MyceliumInSlot20] ~ ~ ~ execute @s[tag=!LilyPadInSlot20] ~ ~ ~ execute @s[tag=!NetherBrickInSlot20] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot20] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot20] ~ ~ ~ execute @s[tag=!NetherWartInSlot20] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot20] ~ ~ ~ execute @s[tag=!BrewingStandInSlot20] ~ ~ ~ execute @s[tag=!CauldronInSlot20] ~ ~ ~ execute @s[tag=!EndPortalInSlot20] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot20] ~ ~ ~ execute @s[tag=!EndStoneInSlot20] ~ ~ ~ execute @s[tag=!DragonEggInSlot20] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot20] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot20] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot20] ~ ~ ~ execute @s[tag=!CocoaInSlot20] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot20] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot20] ~ ~ ~ execute @s[tag=!EnderChestInSlot20] ~ ~ ~ execute @s[tag=!TripwireHookInSlot20] ~ ~ ~ execute @s[tag=!TripwireInSlot20] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot20] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot20] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot20] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot20] ~ ~ ~ execute @s[tag=!CommandBlockInSlot20] ~ ~ ~ execute @s[tag=!BeaconInSlot20] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot20] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot20] ~ ~ ~ execute @s[tag=!FlowerPotInSlot20] ~ ~ ~ execute @s[tag=!CarrotsInSlot20] ~ ~ ~ execute @s[tag=!PotatoesInSlot20] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot20] ~ ~ ~ execute @s[tag=!MobHeadInSlot20] ~ ~ ~ execute @s[tag=!AnvilInSlot20] ~ ~ ~ execute @s[tag=!TrappedChestInSlot20] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot20] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot20] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot20] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot20] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot20] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot20] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot20] ~ ~ ~ execute @s[tag=!HopperInSlot20] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot20] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot20] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot20] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot20] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot20] ~ ~ ~ execute @s[tag=!DropperInSlot20] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot20] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot20] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot20] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot20] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot20] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot20] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot20] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot20] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot20] ~ ~ ~ execute @s[tag=!BarrierInSlot20] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot20] ~ ~ ~ execute @s[tag=!PrismarineInSlot20] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot20] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot20] ~ ~ ~ execute @s[tag=!SeaLanternInSlot20] ~ ~ ~ execute @s[tag=!HayBaleInSlot20] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot20] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot20] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot20] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot20] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot20] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot20] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot20] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot20] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot20] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot20] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot20] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot20] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot20] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot20] ~ ~ ~ execute @s[tag=!RedCarpetInSlot20] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot20] ~ ~ ~ execute @s[tag=!HardenedClayInSlot20] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot20] ~ ~ ~ execute @s[tag=!PackedIceInSlot20] ~ ~ ~ execute @s[tag=!SunflowerInSlot20] ~ ~ ~ execute @s[tag=!LilacInSlot20] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot20] ~ ~ ~ execute @s[tag=!LargeFernInSlot20] ~ ~ ~ execute @s[tag=!RoseBushInSlot20] ~ ~ ~ execute @s[tag=!PeonyInSlot20] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot20] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot20] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot20] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot20] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot20] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot20] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot20] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot20] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot20] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot20] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot20] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot20] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot20] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot20] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot20] ~ ~ ~ execute @s[tag=!BirchFenceInSlot20] ~ ~ ~ execute @s[tag=!JungleFenceInSlot20] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot20] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot20] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot20] ~ ~ ~ execute @s[tag=!EndRodInSlot20] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot20] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot20] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot20] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot20] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot20] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot20] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot20] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot20] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot20] ~ ~ ~ execute @s[tag=!GrassPathInSlot20] ~ ~ ~ execute @s[tag=!EndGatewayInSlot20] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot20] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot20] ~ ~ ~ execute @s[tag=!FrostedIceInSlot20] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot20] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot20] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot20] ~ ~ ~ execute @s[tag=!BoneBlockInSlot20] ~ ~ ~ execute @s[tag=!StructureVoidInSlot20] ~ ~ ~ execute @s[tag=!ObserverInSlot20] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot20] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot20] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot20] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot20] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot20] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot20] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot20] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot20] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot20] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot20] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot20] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot20] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot20] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot20] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot20] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot20] ~ ~ ~ execute @s[tag=!RedConcreteInSlot20] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot20] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot20] ~ ~ ~ execute @s[tag=!StructureBlockInSlot20] ~ ~ ~ scoreboard players tag @s add AirInSlot20 