scoreboard players tag @s add AirInSlot13 {Inventory:[{Slot:13b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot13 {Inventory:[{Slot:13b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot13 {Inventory:[{Slot:13b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot13 {Inventory:[{Slot:13b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot13 {Inventory:[{Slot:13b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot13 {Inventory:[{Slot:13b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot13 {Inventory:[{Slot:13b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot13 {Inventory:[{Slot:13b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot13 {Inventory:[{Slot:13b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot13 {Inventory:[{Slot:13b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot13 {Inventory:[{Slot:13b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot13 {Inventory:[{Slot:13b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot13 {Inventory:[{Slot:13b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot13 {Inventory:[{Slot:13b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot13 {Inventory:[{Slot:13b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot13 {Inventory:[{Slot:13b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot13 {Inventory:[{Slot:13b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot13 {Inventory:[{Slot:13b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot13 {Inventory:[{Slot:13b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot13 {Inventory:[{Slot:13b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot13 {Inventory:[{Slot:13b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot13 {Inventory:[{Slot:13b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot13 {Inventory:[{Slot:13b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot13 {Inventory:[{Slot:13b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot13 {Inventory:[{Slot:13b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot13 {Inventory:[{Slot:13b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot13 {Inventory:[{Slot:13b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot13 {Inventory:[{Slot:13b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot13 {Inventory:[{Slot:13b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot13 {Inventory:[{Slot:13b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot13 {Inventory:[{Slot:13b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot13 {Inventory:[{Slot:13b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot13 {Inventory:[{Slot:13b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot13 {Inventory:[{Slot:13b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot13 {Inventory:[{Slot:13b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot13 {Inventory:[{Slot:13b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot13 {Inventory:[{Slot:13b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot13 {Inventory:[{Slot:13b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot13 {Inventory:[{Slot:13b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot13 {Inventory:[{Slot:13b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot13 {Inventory:[{Slot:13b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot13 {Inventory:[{Slot:13b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot13 {Inventory:[{Slot:13b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot13 {Inventory:[{Slot:13b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot13 {Inventory:[{Slot:13b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot13 {Inventory:[{Slot:13b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot13 {Inventory:[{Slot:13b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot13 {Inventory:[{Slot:13b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot13 {Inventory:[{Slot:13b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot13 {Inventory:[{Slot:13b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot13 {Inventory:[{Slot:13b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot13 {Inventory:[{Slot:13b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot13 {Inventory:[{Slot:13b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot13 {Inventory:[{Slot:13b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot13 {Inventory:[{Slot:13b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot13 {Inventory:[{Slot:13b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot13 {Inventory:[{Slot:13b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot13 {Inventory:[{Slot:13b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot13 {Inventory:[{Slot:13b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot13 {Inventory:[{Slot:13b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot13 {Inventory:[{Slot:13b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot13 {Inventory:[{Slot:13b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot13 {Inventory:[{Slot:13b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot13 {Inventory:[{Slot:13b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot13 {Inventory:[{Slot:13b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot13 {Inventory:[{Slot:13b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot13 {Inventory:[{Slot:13b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot13 {Inventory:[{Slot:13b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot13 {Inventory:[{Slot:13b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot13 {Inventory:[{Slot:13b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot13 {Inventory:[{Slot:13b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot13 {Inventory:[{Slot:13b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot13 {Inventory:[{Slot:13b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot13 {Inventory:[{Slot:13b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot13 {Inventory:[{Slot:13b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot13 {Inventory:[{Slot:13b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot13 {Inventory:[{Slot:13b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot13 {Inventory:[{Slot:13b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot13 {Inventory:[{Slot:13b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot13 {Inventory:[{Slot:13b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot13 {Inventory:[{Slot:13b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot13 {Inventory:[{Slot:13b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot13 {Inventory:[{Slot:13b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot13 {Inventory:[{Slot:13b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot13 {Inventory:[{Slot:13b,id:"minecraft:structure_block",Damage:0s}]}
