scoreboard players tag @s add AirInSlot34 {Inventory:[{Slot:34b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot34 {Inventory:[{Slot:34b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot34 {Inventory:[{Slot:34b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot34 {Inventory:[{Slot:34b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot34 {Inventory:[{Slot:34b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot34 {Inventory:[{Slot:34b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot34 {Inventory:[{Slot:34b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot34 {Inventory:[{Slot:34b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot34 {Inventory:[{Slot:34b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot34 {Inventory:[{Slot:34b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot34 {Inventory:[{Slot:34b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot34 {Inventory:[{Slot:34b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot34 {Inventory:[{Slot:34b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot34 {Inventory:[{Slot:34b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot34 {Inventory:[{Slot:34b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot34 {Inventory:[{Slot:34b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot34 {Inventory:[{Slot:34b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot34 {Inventory:[{Slot:34b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot34 {Inventory:[{Slot:34b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot34 {Inventory:[{Slot:34b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot34 {Inventory:[{Slot:34b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot34 {Inventory:[{Slot:34b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot34 {Inventory:[{Slot:34b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot34 {Inventory:[{Slot:34b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot34 {Inventory:[{Slot:34b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot34 {Inventory:[{Slot:34b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot34 {Inventory:[{Slot:34b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot34 {Inventory:[{Slot:34b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot34 {Inventory:[{Slot:34b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot34 {Inventory:[{Slot:34b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot34 {Inventory:[{Slot:34b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot34 {Inventory:[{Slot:34b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot34 {Inventory:[{Slot:34b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot34 {Inventory:[{Slot:34b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot34 {Inventory:[{Slot:34b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot34 {Inventory:[{Slot:34b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot34 {Inventory:[{Slot:34b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot34 {Inventory:[{Slot:34b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot34 {Inventory:[{Slot:34b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot34 {Inventory:[{Slot:34b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot34 {Inventory:[{Slot:34b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot34 {Inventory:[{Slot:34b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot34 {Inventory:[{Slot:34b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot34 {Inventory:[{Slot:34b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot34 {Inventory:[{Slot:34b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot34 {Inventory:[{Slot:34b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot34 {Inventory:[{Slot:34b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot34 {Inventory:[{Slot:34b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot34 {Inventory:[{Slot:34b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot34 {Inventory:[{Slot:34b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot34 {Inventory:[{Slot:34b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot34 {Inventory:[{Slot:34b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot34 {Inventory:[{Slot:34b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot34 {Inventory:[{Slot:34b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot34 {Inventory:[{Slot:34b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot34 {Inventory:[{Slot:34b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot34 {Inventory:[{Slot:34b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot34 {Inventory:[{Slot:34b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot34 {Inventory:[{Slot:34b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot34 {Inventory:[{Slot:34b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot34 {Inventory:[{Slot:34b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot34 {Inventory:[{Slot:34b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot34 {Inventory:[{Slot:34b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot34 {Inventory:[{Slot:34b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot34 {Inventory:[{Slot:34b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot34 {Inventory:[{Slot:34b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot34 {Inventory:[{Slot:34b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot34 {Inventory:[{Slot:34b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot34 {Inventory:[{Slot:34b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot34 {Inventory:[{Slot:34b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot34 {Inventory:[{Slot:34b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot34 {Inventory:[{Slot:34b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot34 {Inventory:[{Slot:34b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot34 {Inventory:[{Slot:34b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot34 {Inventory:[{Slot:34b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot34 {Inventory:[{Slot:34b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot34 {Inventory:[{Slot:34b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot34 {Inventory:[{Slot:34b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot34 {Inventory:[{Slot:34b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot34 {Inventory:[{Slot:34b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot34 {Inventory:[{Slot:34b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot34 {Inventory:[{Slot:34b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot34 {Inventory:[{Slot:34b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot34 {Inventory:[{Slot:34b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot34 {Inventory:[{Slot:34b,id:"minecraft:structure_block",Damage:0s}]}
