scoreboard players tag @s add AirInSlot28 {Inventory:[{Slot:28b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot28 {Inventory:[{Slot:28b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot28 {Inventory:[{Slot:28b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot28 {Inventory:[{Slot:28b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot28 {Inventory:[{Slot:28b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot28 {Inventory:[{Slot:28b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot28 {Inventory:[{Slot:28b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot28 {Inventory:[{Slot:28b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot28 {Inventory:[{Slot:28b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot28 {Inventory:[{Slot:28b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot28 {Inventory:[{Slot:28b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot28 {Inventory:[{Slot:28b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot28 {Inventory:[{Slot:28b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot28 {Inventory:[{Slot:28b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot28 {Inventory:[{Slot:28b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot28 {Inventory:[{Slot:28b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot28 {Inventory:[{Slot:28b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot28 {Inventory:[{Slot:28b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot28 {Inventory:[{Slot:28b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot28 {Inventory:[{Slot:28b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot28 {Inventory:[{Slot:28b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot28 {Inventory:[{Slot:28b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot28 {Inventory:[{Slot:28b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot28 {Inventory:[{Slot:28b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot28 {Inventory:[{Slot:28b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot28 {Inventory:[{Slot:28b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot28 {Inventory:[{Slot:28b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot28 {Inventory:[{Slot:28b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot28 {Inventory:[{Slot:28b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot28 {Inventory:[{Slot:28b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot28 {Inventory:[{Slot:28b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot28 {Inventory:[{Slot:28b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot28 {Inventory:[{Slot:28b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot28] ~ ~ ~ execute @s[tag=!StoneInSlot28] ~ ~ ~ execute @s[tag=!GraniteInSlot28] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot28] ~ ~ ~ execute @s[tag=!DioriteInSlot28] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot28] ~ ~ ~ execute @s[tag=!AndesiteInSlot28] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot28] ~ ~ ~ execute @s[tag=!GrassBlockInSlot28] ~ ~ ~ execute @s[tag=!DirtInSlot28] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot28] ~ ~ ~ execute @s[tag=!PodzolInSlot28] ~ ~ ~ execute @s[tag=!CobblestoneInSlot28] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot28] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot28] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot28] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot28] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot28] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot28] ~ ~ ~ execute @s[tag=!OakSaplingInSlot28] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot28] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot28] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot28] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot28] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot28] ~ ~ ~ execute @s[tag=!BedrockInSlot28] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot28] ~ ~ ~ execute @s[tag=!StillWaterInSlot28] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot28] ~ ~ ~ execute @s[tag=!StillLavaInSlot28] ~ ~ ~ execute @s[tag=!SandInSlot28] ~ ~ ~ execute @s[tag=!RedSandInSlot28] ~ ~ ~ execute @s[tag=!GravelInSlot28] ~ ~ ~ execute @s[tag=!GoldOreInSlot28] ~ ~ ~ execute @s[tag=!IronOreInSlot28] ~ ~ ~ execute @s[tag=!CoalOreInSlot28] ~ ~ ~ execute @s[tag=!OakWoodInSlot28] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot28] ~ ~ ~ execute @s[tag=!BirchWoodInSlot28] ~ ~ ~ execute @s[tag=!JungleWoodInSlot28] ~ ~ ~ execute @s[tag=!OakLeavesInSlot28] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot28] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot28] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot28] ~ ~ ~ execute @s[tag=!SpongeInSlot28] ~ ~ ~ execute @s[tag=!WetSpongeInSlot28] ~ ~ ~ execute @s[tag=!GlassInSlot28] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot28] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot28] ~ ~ ~ execute @s[tag=!DispenserInSlot28] ~ ~ ~ execute @s[tag=!SandstoneInSlot28] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot28] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot28] ~ ~ ~ execute @s[tag=!NoteBlockInSlot28] ~ ~ ~ execute @s[tag=!BedInSlot28] ~ ~ ~ execute @s[tag=!PoweredRailInSlot28] ~ ~ ~ execute @s[tag=!DetectorRailInSlot28] ~ ~ ~ execute @s[tag=!StickyPistonInSlot28] ~ ~ ~ execute @s[tag=!CobwebInSlot28] ~ ~ ~ execute @s[tag=!DeadShrubInSlot28] ~ ~ ~ execute @s[tag=!GrassInSlot28] ~ ~ ~ execute @s[tag=!FernInSlot28] ~ ~ ~ execute @s[tag=!DeadBushInSlot28] ~ ~ ~ execute @s[tag=!PistonInSlot28] ~ ~ ~ execute @s[tag=!PistonHeadInSlot28] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot28] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot28] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot28] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot28] ~ ~ ~ execute @s[tag=!YellowWoolInSlot28] ~ ~ ~ execute @s[tag=!LimeWoolInSlot28] ~ ~ ~ execute @s[tag=!PinkWoolInSlot28] ~ ~ ~ execute @s[tag=!GrayWoolInSlot28] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot28] ~ ~ ~ execute @s[tag=!CyanWoolInSlot28] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot28] ~ ~ ~ execute @s[tag=!BlueWoolInSlot28] ~ ~ ~ execute @s[tag=!BrownWoolInSlot28] ~ ~ ~ execute @s[tag=!GreenWoolInSlot28] ~ ~ ~ execute @s[tag=!RedWoolInSlot28] ~ ~ ~ execute @s[tag=!BlackWoolInSlot28] ~ ~ ~ execute @s[tag=!DandelionInSlot28] ~ ~ ~ execute @s[tag=!PoppyInSlot28] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot28] ~ ~ ~ execute @s[tag=!AlliumInSlot28] ~ ~ ~ execute @s[tag=!AzureBluetInSlot28] ~ ~ ~ execute @s[tag=!RedTulipInSlot28] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot28] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot28] ~ ~ ~ execute @s[tag=!PinkTulipInSlot28] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot28] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot28] ~ ~ ~ execute @s[tag=!RedMushroomInSlot28] ~ ~ ~ execute @s[tag=!GoldBlockInSlot28] ~ ~ ~ execute @s[tag=!IronBlockInSlot28] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot28] ~ ~ ~ execute @s[tag=!StoneSlabInSlot28] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot28] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot28] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot28] ~ ~ ~ execute @s[tag=!BrickSlabInSlot28] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot28] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot28] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot28] ~ ~ ~ execute @s[tag=!BricksInSlot28] ~ ~ ~ execute @s[tag=!TNTInSlot28] ~ ~ ~ execute @s[tag=!BookshelfInSlot28] ~ ~ ~ execute @s[tag=!MossStoneInSlot28] ~ ~ ~ execute @s[tag=!ObsidianInSlot28] ~ ~ ~ execute @s[tag=!TorchInSlot28] ~ ~ ~ execute @s[tag=!FireInSlot28] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot28] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot28] ~ ~ ~ execute @s[tag=!ChestInSlot28] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot28] ~ ~ ~ execute @s[tag=!DiamondOreInSlot28] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot28] ~ ~ ~ execute @s[tag=!CraftingTableInSlot28] ~ ~ ~ execute @s[tag=!WheatCropsInSlot28] ~ ~ ~ execute @s[tag=!FarmlandInSlot28] ~ ~ ~ execute @s[tag=!FurnaceInSlot28] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot28] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot28] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!LadderInSlot28] ~ ~ ~ execute @s[tag=!RailInSlot28] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot28] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot28] ~ ~ ~ execute @s[tag=!LeverInSlot28] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot28] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot28] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot28] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot28] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot28] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot28] ~ ~ ~ execute @s[tag=!StoneButtonInSlot28] ~ ~ ~ execute @s[tag=!SnowInSlot28] ~ ~ ~ execute @s[tag=!IceInSlot28] ~ ~ ~ execute @s[tag=!SnowBlockInSlot28] ~ ~ ~ execute @s[tag=!CactusInSlot28] ~ ~ ~ execute @s[tag=!SugarCanesInSlot28] ~ ~ ~ execute @s[tag=!JukeboxInSlot28] ~ ~ ~ execute @s[tag=!OakFenceInSlot28] ~ ~ ~ execute @s[tag=!PumpkinInSlot28] ~ ~ ~ execute @s[tag=!NetherrackInSlot28] ~ ~ ~ execute @s[tag=!SoulSandInSlot28] ~ ~ ~ execute @s[tag=!GlowstoneInSlot28] ~ ~ ~ execute @s[tag=!NetherPortalInSlot28] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot28] ~ ~ ~ execute @s[tag=!CakeBlockInSlot28] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot28] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot28] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot28] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot28] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot28] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot28] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot28] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot28] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot28] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot28] ~ ~ ~ execute @s[tag=!StoneBricksInSlot28] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot28] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot28] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot28] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot28] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot28] ~ ~ ~ execute @s[tag=!IronBarsInSlot28] ~ ~ ~ execute @s[tag=!GlassPaneInSlot28] ~ ~ ~ execute @s[tag=!MelonBlockInSlot28] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot28] ~ ~ ~ execute @s[tag=!MelonStemInSlot28] ~ ~ ~ execute @s[tag=!VinesInSlot28] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot28] ~ ~ ~ execute @s[tag=!BrickStairsInSlot28] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot28] ~ ~ ~ execute @s[tag=!MyceliumInSlot28] ~ ~ ~ execute @s[tag=!LilyPadInSlot28] ~ ~ ~ execute @s[tag=!NetherBrickInSlot28] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot28] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot28] ~ ~ ~ execute @s[tag=!NetherWartInSlot28] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot28] ~ ~ ~ execute @s[tag=!BrewingStandInSlot28] ~ ~ ~ execute @s[tag=!CauldronInSlot28] ~ ~ ~ execute @s[tag=!EndPortalInSlot28] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot28] ~ ~ ~ execute @s[tag=!EndStoneInSlot28] ~ ~ ~ execute @s[tag=!DragonEggInSlot28] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot28] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot28] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot28] ~ ~ ~ execute @s[tag=!CocoaInSlot28] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot28] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot28] ~ ~ ~ execute @s[tag=!EnderChestInSlot28] ~ ~ ~ execute @s[tag=!TripwireHookInSlot28] ~ ~ ~ execute @s[tag=!TripwireInSlot28] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot28] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot28] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot28] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot28] ~ ~ ~ execute @s[tag=!CommandBlockInSlot28] ~ ~ ~ execute @s[tag=!BeaconInSlot28] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot28] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot28] ~ ~ ~ execute @s[tag=!FlowerPotInSlot28] ~ ~ ~ execute @s[tag=!CarrotsInSlot28] ~ ~ ~ execute @s[tag=!PotatoesInSlot28] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot28] ~ ~ ~ execute @s[tag=!MobHeadInSlot28] ~ ~ ~ execute @s[tag=!AnvilInSlot28] ~ ~ ~ execute @s[tag=!TrappedChestInSlot28] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot28] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot28] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot28] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot28] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot28] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot28] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot28] ~ ~ ~ execute @s[tag=!HopperInSlot28] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot28] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot28] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot28] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot28] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot28] ~ ~ ~ execute @s[tag=!DropperInSlot28] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot28] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot28] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot28] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot28] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot28] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot28] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot28] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot28] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot28] ~ ~ ~ execute @s[tag=!BarrierInSlot28] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot28] ~ ~ ~ execute @s[tag=!PrismarineInSlot28] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot28] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot28] ~ ~ ~ execute @s[tag=!SeaLanternInSlot28] ~ ~ ~ execute @s[tag=!HayBaleInSlot28] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot28] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot28] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot28] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot28] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot28] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot28] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot28] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot28] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot28] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot28] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot28] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot28] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot28] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot28] ~ ~ ~ execute @s[tag=!RedCarpetInSlot28] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot28] ~ ~ ~ execute @s[tag=!HardenedClayInSlot28] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot28] ~ ~ ~ execute @s[tag=!PackedIceInSlot28] ~ ~ ~ execute @s[tag=!SunflowerInSlot28] ~ ~ ~ execute @s[tag=!LilacInSlot28] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot28] ~ ~ ~ execute @s[tag=!LargeFernInSlot28] ~ ~ ~ execute @s[tag=!RoseBushInSlot28] ~ ~ ~ execute @s[tag=!PeonyInSlot28] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot28] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot28] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot28] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot28] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot28] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot28] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot28] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot28] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot28] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot28] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot28] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot28] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot28] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot28] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot28] ~ ~ ~ execute @s[tag=!BirchFenceInSlot28] ~ ~ ~ execute @s[tag=!JungleFenceInSlot28] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot28] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot28] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot28] ~ ~ ~ execute @s[tag=!EndRodInSlot28] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot28] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot28] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot28] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot28] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot28] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot28] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot28] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot28] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot28] ~ ~ ~ execute @s[tag=!GrassPathInSlot28] ~ ~ ~ execute @s[tag=!EndGatewayInSlot28] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot28] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot28] ~ ~ ~ execute @s[tag=!FrostedIceInSlot28] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot28] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot28] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot28] ~ ~ ~ execute @s[tag=!BoneBlockInSlot28] ~ ~ ~ execute @s[tag=!StructureVoidInSlot28] ~ ~ ~ execute @s[tag=!ObserverInSlot28] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot28] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot28] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot28] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot28] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot28] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot28] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot28] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot28] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot28] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot28] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot28] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot28] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot28] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot28] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot28] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot28] ~ ~ ~ execute @s[tag=!RedConcreteInSlot28] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot28] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot28] ~ ~ ~ execute @s[tag=!StructureBlockInSlot28] ~ ~ ~ scoreboard players tag @s add AirInSlot28 