scoreboard players tag @a add AirInSlot28 {Inventory:[{Slot:28b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot28 {Inventory:[{Slot:28b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot28 {Inventory:[{Slot:28b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot28 {Inventory:[{Slot:28b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot28 {Inventory:[{Slot:28b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot28 {Inventory:[{Slot:28b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot28 {Inventory:[{Slot:28b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot28 {Inventory:[{Slot:28b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot28 {Inventory:[{Slot:28b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot28 {Inventory:[{Slot:28b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot28 {Inventory:[{Slot:28b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot28 {Inventory:[{Slot:28b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot28 {Inventory:[{Slot:28b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot28 {Inventory:[{Slot:28b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot28 {Inventory:[{Slot:28b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot28 {Inventory:[{Slot:28b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot28 {Inventory:[{Slot:28b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot28 {Inventory:[{Slot:28b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot28 {Inventory:[{Slot:28b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot28 {Inventory:[{Slot:28b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot28 {Inventory:[{Slot:28b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot28 {Inventory:[{Slot:28b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot28 {Inventory:[{Slot:28b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot28 {Inventory:[{Slot:28b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot28 {Inventory:[{Slot:28b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot28 {Inventory:[{Slot:28b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot28 {Inventory:[{Slot:28b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot28 {Inventory:[{Slot:28b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot28 {Inventory:[{Slot:28b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot28 {Inventory:[{Slot:28b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot28 {Inventory:[{Slot:28b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot28 {Inventory:[{Slot:28b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot28 {Inventory:[{Slot:28b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot28 {Inventory:[{Slot:28b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot28 {Inventory:[{Slot:28b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot28 {Inventory:[{Slot:28b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot28 {Inventory:[{Slot:28b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot28 {Inventory:[{Slot:28b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot28 {Inventory:[{Slot:28b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot28 {Inventory:[{Slot:28b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot28 {Inventory:[{Slot:28b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot28 {Inventory:[{Slot:28b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot28 {Inventory:[{Slot:28b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot28 {Inventory:[{Slot:28b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot28 {Inventory:[{Slot:28b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot28 {Inventory:[{Slot:28b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot28 {Inventory:[{Slot:28b,id:"minecraft:structure_block",Damage:0s}]}
