scoreboard players tag @s add AirInSlot16 {Inventory:[{Slot:16b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot16 {Inventory:[{Slot:16b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot16 {Inventory:[{Slot:16b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot16 {Inventory:[{Slot:16b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot16 {Inventory:[{Slot:16b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot16 {Inventory:[{Slot:16b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot16 {Inventory:[{Slot:16b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot16 {Inventory:[{Slot:16b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot16 {Inventory:[{Slot:16b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot16 {Inventory:[{Slot:16b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakLogFacingYInSlot16 {Inventory:[{Slot:16b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceLogFacingYInSlot16 {Inventory:[{Slot:16b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchLogFacingYInSlot16 {Inventory:[{Slot:16b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleLogFacingYInSlot16 {Inventory:[{Slot:16b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot16 {Inventory:[{Slot:16b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot16 {Inventory:[{Slot:16b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot16 {Inventory:[{Slot:16b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot16 {Inventory:[{Slot:16b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot16 {Inventory:[{Slot:16b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot16 {Inventory:[{Slot:16b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot16 {Inventory:[{Slot:16b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot16 {Inventory:[{Slot:16b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot16 {Inventory:[{Slot:16b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot16 {Inventory:[{Slot:16b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot16 {Inventory:[{Slot:16b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot16 {Inventory:[{Slot:16b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot16 {Inventory:[{Slot:16b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot16 {Inventory:[{Slot:16b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot16 {Inventory:[{Slot:16b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot16 {Inventory:[{Slot:16b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot16 {Inventory:[{Slot:16b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot16 {Inventory:[{Slot:16b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot16 {Inventory:[{Slot:16b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot16 {Inventory:[{Slot:16b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot16 {Inventory:[{Slot:16b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot16 {Inventory:[{Slot:16b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot16 {Inventory:[{Slot:16b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot16 {Inventory:[{Slot:16b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot16 {Inventory:[{Slot:16b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot16 {Inventory:[{Slot:16b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot16 {Inventory:[{Slot:16b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot16 {Inventory:[{Slot:16b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot16 {Inventory:[{Slot:16b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot16 {Inventory:[{Slot:16b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot16 {Inventory:[{Slot:16b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot16 {Inventory:[{Slot:16b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot16 {Inventory:[{Slot:16b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot16 {Inventory:[{Slot:16b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot16 {Inventory:[{Slot:16b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot16 {Inventory:[{Slot:16b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot16 {Inventory:[{Slot:16b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot16 {Inventory:[{Slot:16b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot16 {Inventory:[{Slot:16b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot16 {Inventory:[{Slot:16b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot16 {Inventory:[{Slot:16b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot16 {Inventory:[{Slot:16b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot16 {Inventory:[{Slot:16b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot16 {Inventory:[{Slot:16b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot16 {Inventory:[{Slot:16b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot16 {Inventory:[{Slot:16b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot16 {Inventory:[{Slot:16b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot16 {Inventory:[{Slot:16b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot16 {Inventory:[{Slot:16b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot16 {Inventory:[{Slot:16b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodFacingYInSlot16 {Inventory:[{Slot:16b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodFacingYInSlot16 {Inventory:[{Slot:16b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot16 {Inventory:[{Slot:16b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot16 {Inventory:[{Slot:16b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot16 {Inventory:[{Slot:16b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot16 {Inventory:[{Slot:16b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot16 {Inventory:[{Slot:16b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot16 {Inventory:[{Slot:16b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot16 {Inventory:[{Slot:16b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot16 {Inventory:[{Slot:16b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot16 {Inventory:[{Slot:16b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot16 {Inventory:[{Slot:16b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot16 {Inventory:[{Slot:16b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot16 {Inventory:[{Slot:16b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot16 {Inventory:[{Slot:16b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot16 {Inventory:[{Slot:16b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot16 {Inventory:[{Slot:16b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot16 {Inventory:[{Slot:16b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot16 {Inventory:[{Slot:16b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot16 {Inventory:[{Slot:16b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot16 {Inventory:[{Slot:16b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot16 {Inventory:[{Slot:16b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot16 {Inventory:[{Slot:16b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot16 {Inventory:[{Slot:16b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot16 {Inventory:[{Slot:16b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot16 {Inventory:[{Slot:16b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot16 {Inventory:[{Slot:16b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot16] ~ ~ ~ execute @s[tag=!StoneInSlot16] ~ ~ ~ execute @s[tag=!GraniteInSlot16] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot16] ~ ~ ~ execute @s[tag=!DioriteInSlot16] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot16] ~ ~ ~ execute @s[tag=!AndesiteInSlot16] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot16] ~ ~ ~ execute @s[tag=!GrassBlockInSlot16] ~ ~ ~ execute @s[tag=!DirtInSlot16] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot16] ~ ~ ~ execute @s[tag=!PodzolInSlot16] ~ ~ ~ execute @s[tag=!CobblestoneInSlot16] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot16] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot16] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot16] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot16] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot16] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot16] ~ ~ ~ execute @s[tag=!OakSaplingInSlot16] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot16] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot16] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot16] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot16] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot16] ~ ~ ~ execute @s[tag=!BedrockInSlot16] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot16] ~ ~ ~ execute @s[tag=!StillWaterInSlot16] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot16] ~ ~ ~ execute @s[tag=!StillLavaInSlot16] ~ ~ ~ execute @s[tag=!SandInSlot16] ~ ~ ~ execute @s[tag=!RedSandInSlot16] ~ ~ ~ execute @s[tag=!GravelInSlot16] ~ ~ ~ execute @s[tag=!GoldOreInSlot16] ~ ~ ~ execute @s[tag=!IronOreInSlot16] ~ ~ ~ execute @s[tag=!CoalOreInSlot16] ~ ~ ~ execute @s[tag=!OakLogFacingYInSlot16] ~ ~ ~ execute @s[tag=!SpruceLogFacingYInSlot16] ~ ~ ~ execute @s[tag=!BirchLogFacingYInSlot16] ~ ~ ~ execute @s[tag=!JungleLogFacingYInSlot16] ~ ~ ~ execute @s[tag=!OakLeavesInSlot16] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot16] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot16] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot16] ~ ~ ~ execute @s[tag=!SpongeInSlot16] ~ ~ ~ execute @s[tag=!WetSpongeInSlot16] ~ ~ ~ execute @s[tag=!GlassInSlot16] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot16] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot16] ~ ~ ~ execute @s[tag=!DispenserInSlot16] ~ ~ ~ execute @s[tag=!SandstoneInSlot16] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot16] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot16] ~ ~ ~ execute @s[tag=!NoteBlockInSlot16] ~ ~ ~ execute @s[tag=!BedInSlot16] ~ ~ ~ execute @s[tag=!PoweredRailInSlot16] ~ ~ ~ execute @s[tag=!DetectorRailInSlot16] ~ ~ ~ execute @s[tag=!StickyPistonInSlot16] ~ ~ ~ execute @s[tag=!CobwebInSlot16] ~ ~ ~ execute @s[tag=!DeadShrubInSlot16] ~ ~ ~ execute @s[tag=!GrassInSlot16] ~ ~ ~ execute @s[tag=!FernInSlot16] ~ ~ ~ execute @s[tag=!DeadBushInSlot16] ~ ~ ~ execute @s[tag=!PistonInSlot16] ~ ~ ~ execute @s[tag=!PistonHeadInSlot16] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot16] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot16] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot16] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot16] ~ ~ ~ execute @s[tag=!YellowWoolInSlot16] ~ ~ ~ execute @s[tag=!LimeWoolInSlot16] ~ ~ ~ execute @s[tag=!PinkWoolInSlot16] ~ ~ ~ execute @s[tag=!GrayWoolInSlot16] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot16] ~ ~ ~ execute @s[tag=!CyanWoolInSlot16] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot16] ~ ~ ~ execute @s[tag=!BlueWoolInSlot16] ~ ~ ~ execute @s[tag=!BrownWoolInSlot16] ~ ~ ~ execute @s[tag=!GreenWoolInSlot16] ~ ~ ~ execute @s[tag=!RedWoolInSlot16] ~ ~ ~ execute @s[tag=!BlackWoolInSlot16] ~ ~ ~ execute @s[tag=!DandelionInSlot16] ~ ~ ~ execute @s[tag=!PoppyInSlot16] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot16] ~ ~ ~ execute @s[tag=!AlliumInSlot16] ~ ~ ~ execute @s[tag=!AzureBluetInSlot16] ~ ~ ~ execute @s[tag=!RedTulipInSlot16] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot16] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot16] ~ ~ ~ execute @s[tag=!PinkTulipInSlot16] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot16] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot16] ~ ~ ~ execute @s[tag=!RedMushroomInSlot16] ~ ~ ~ execute @s[tag=!GoldBlockInSlot16] ~ ~ ~ execute @s[tag=!IronBlockInSlot16] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot16] ~ ~ ~ execute @s[tag=!StoneSlabInSlot16] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot16] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot16] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot16] ~ ~ ~ execute @s[tag=!BrickSlabInSlot16] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot16] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot16] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot16] ~ ~ ~ execute @s[tag=!BricksInSlot16] ~ ~ ~ execute @s[tag=!TNTInSlot16] ~ ~ ~ execute @s[tag=!BookshelfInSlot16] ~ ~ ~ execute @s[tag=!MossStoneInSlot16] ~ ~ ~ execute @s[tag=!ObsidianInSlot16] ~ ~ ~ execute @s[tag=!TorchInSlot16] ~ ~ ~ execute @s[tag=!FireInSlot16] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot16] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot16] ~ ~ ~ execute @s[tag=!ChestInSlot16] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot16] ~ ~ ~ execute @s[tag=!DiamondOreInSlot16] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot16] ~ ~ ~ execute @s[tag=!CraftingTableInSlot16] ~ ~ ~ execute @s[tag=!WheatCropsInSlot16] ~ ~ ~ execute @s[tag=!FarmlandInSlot16] ~ ~ ~ execute @s[tag=!FurnaceInSlot16] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot16] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot16] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!LadderInSlot16] ~ ~ ~ execute @s[tag=!RailInSlot16] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot16] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot16] ~ ~ ~ execute @s[tag=!LeverInSlot16] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot16] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot16] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot16] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot16] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot16] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot16] ~ ~ ~ execute @s[tag=!StoneButtonInSlot16] ~ ~ ~ execute @s[tag=!SnowInSlot16] ~ ~ ~ execute @s[tag=!IceInSlot16] ~ ~ ~ execute @s[tag=!SnowBlockInSlot16] ~ ~ ~ execute @s[tag=!CactusInSlot16] ~ ~ ~ execute @s[tag=!SugarCanesInSlot16] ~ ~ ~ execute @s[tag=!JukeboxInSlot16] ~ ~ ~ execute @s[tag=!OakFenceInSlot16] ~ ~ ~ execute @s[tag=!PumpkinInSlot16] ~ ~ ~ execute @s[tag=!NetherrackInSlot16] ~ ~ ~ execute @s[tag=!SoulSandInSlot16] ~ ~ ~ execute @s[tag=!GlowstoneInSlot16] ~ ~ ~ execute @s[tag=!NetherPortalInSlot16] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot16] ~ ~ ~ execute @s[tag=!CakeBlockInSlot16] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot16] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot16] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot16] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot16] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot16] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot16] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot16] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot16] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot16] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot16] ~ ~ ~ execute @s[tag=!StoneBricksInSlot16] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot16] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot16] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot16] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot16] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot16] ~ ~ ~ execute @s[tag=!IronBarsInSlot16] ~ ~ ~ execute @s[tag=!GlassPaneInSlot16] ~ ~ ~ execute @s[tag=!MelonBlockInSlot16] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot16] ~ ~ ~ execute @s[tag=!MelonStemInSlot16] ~ ~ ~ execute @s[tag=!VinesInSlot16] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot16] ~ ~ ~ execute @s[tag=!BrickStairsInSlot16] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot16] ~ ~ ~ execute @s[tag=!MyceliumInSlot16] ~ ~ ~ execute @s[tag=!LilyPadInSlot16] ~ ~ ~ execute @s[tag=!NetherBrickInSlot16] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot16] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot16] ~ ~ ~ execute @s[tag=!NetherWartInSlot16] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot16] ~ ~ ~ execute @s[tag=!BrewingStandInSlot16] ~ ~ ~ execute @s[tag=!CauldronInSlot16] ~ ~ ~ execute @s[tag=!EndPortalInSlot16] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot16] ~ ~ ~ execute @s[tag=!EndStoneInSlot16] ~ ~ ~ execute @s[tag=!DragonEggInSlot16] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot16] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot16] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot16] ~ ~ ~ execute @s[tag=!CocoaInSlot16] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot16] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot16] ~ ~ ~ execute @s[tag=!EnderChestInSlot16] ~ ~ ~ execute @s[tag=!TripwireHookInSlot16] ~ ~ ~ execute @s[tag=!TripwireInSlot16] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot16] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot16] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot16] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot16] ~ ~ ~ execute @s[tag=!CommandBlockInSlot16] ~ ~ ~ execute @s[tag=!BeaconInSlot16] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot16] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot16] ~ ~ ~ execute @s[tag=!FlowerPotInSlot16] ~ ~ ~ execute @s[tag=!CarrotsInSlot16] ~ ~ ~ execute @s[tag=!PotatoesInSlot16] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot16] ~ ~ ~ execute @s[tag=!MobHeadInSlot16] ~ ~ ~ execute @s[tag=!AnvilInSlot16] ~ ~ ~ execute @s[tag=!TrappedChestInSlot16] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot16] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot16] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot16] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot16] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot16] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot16] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot16] ~ ~ ~ execute @s[tag=!HopperInSlot16] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot16] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot16] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot16] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot16] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot16] ~ ~ ~ execute @s[tag=!DropperInSlot16] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot16] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot16] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot16] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot16] ~ ~ ~ execute @s[tag=!AcaciaWoodFacingYInSlot16] ~ ~ ~ execute @s[tag=!DarkOakWoodFacingYInSlot16] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot16] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot16] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot16] ~ ~ ~ execute @s[tag=!BarrierInSlot16] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot16] ~ ~ ~ execute @s[tag=!PrismarineInSlot16] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot16] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot16] ~ ~ ~ execute @s[tag=!SeaLanternInSlot16] ~ ~ ~ execute @s[tag=!HayBaleInSlot16] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot16] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot16] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot16] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot16] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot16] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot16] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot16] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot16] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot16] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot16] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot16] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot16] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot16] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot16] ~ ~ ~ execute @s[tag=!RedCarpetInSlot16] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot16] ~ ~ ~ execute @s[tag=!HardenedClayInSlot16] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot16] ~ ~ ~ execute @s[tag=!PackedIceInSlot16] ~ ~ ~ execute @s[tag=!SunflowerInSlot16] ~ ~ ~ execute @s[tag=!LilacInSlot16] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot16] ~ ~ ~ execute @s[tag=!LargeFernInSlot16] ~ ~ ~ execute @s[tag=!RoseBushInSlot16] ~ ~ ~ execute @s[tag=!PeonyInSlot16] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot16] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot16] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot16] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot16] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot16] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot16] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot16] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot16] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot16] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot16] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot16] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot16] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot16] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot16] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot16] ~ ~ ~ execute @s[tag=!BirchFenceInSlot16] ~ ~ ~ execute @s[tag=!JungleFenceInSlot16] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot16] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot16] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot16] ~ ~ ~ execute @s[tag=!EndRodInSlot16] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot16] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot16] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot16] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot16] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot16] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot16] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot16] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot16] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot16] ~ ~ ~ execute @s[tag=!GrassPathInSlot16] ~ ~ ~ execute @s[tag=!EndGatewayInSlot16] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot16] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot16] ~ ~ ~ execute @s[tag=!FrostedIceInSlot16] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot16] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot16] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot16] ~ ~ ~ execute @s[tag=!BoneBlockInSlot16] ~ ~ ~ execute @s[tag=!StructureVoidInSlot16] ~ ~ ~ execute @s[tag=!ObserverInSlot16] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot16] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot16] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot16] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot16] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot16] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot16] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot16] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot16] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot16] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot16] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot16] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot16] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot16] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot16] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot16] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot16] ~ ~ ~ execute @s[tag=!RedConcreteInSlot16] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot16] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot16] ~ ~ ~ execute @s[tag=!StructureBlockInSlot16] ~ ~ ~ scoreboard players tag @s add AirInSlot16 