scoreboard players tag @a add AirInSlot27 {Inventory:[{Slot:27b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot27 {Inventory:[{Slot:27b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot27 {Inventory:[{Slot:27b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot27 {Inventory:[{Slot:27b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot27 {Inventory:[{Slot:27b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot27 {Inventory:[{Slot:27b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot27 {Inventory:[{Slot:27b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot27 {Inventory:[{Slot:27b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot27 {Inventory:[{Slot:27b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot27 {Inventory:[{Slot:27b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot27 {Inventory:[{Slot:27b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot27 {Inventory:[{Slot:27b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot27 {Inventory:[{Slot:27b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot27 {Inventory:[{Slot:27b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot27 {Inventory:[{Slot:27b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot27 {Inventory:[{Slot:27b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot27 {Inventory:[{Slot:27b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot27 {Inventory:[{Slot:27b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot27 {Inventory:[{Slot:27b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot27 {Inventory:[{Slot:27b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot27 {Inventory:[{Slot:27b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot27 {Inventory:[{Slot:27b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot27 {Inventory:[{Slot:27b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot27 {Inventory:[{Slot:27b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot27 {Inventory:[{Slot:27b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot27 {Inventory:[{Slot:27b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot27 {Inventory:[{Slot:27b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot27 {Inventory:[{Slot:27b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot27 {Inventory:[{Slot:27b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot27 {Inventory:[{Slot:27b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot27 {Inventory:[{Slot:27b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot27 {Inventory:[{Slot:27b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot27 {Inventory:[{Slot:27b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot27 {Inventory:[{Slot:27b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot27 {Inventory:[{Slot:27b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot27 {Inventory:[{Slot:27b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot27 {Inventory:[{Slot:27b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot27 {Inventory:[{Slot:27b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot27 {Inventory:[{Slot:27b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot27 {Inventory:[{Slot:27b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot27 {Inventory:[{Slot:27b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot27 {Inventory:[{Slot:27b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot27 {Inventory:[{Slot:27b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot27 {Inventory:[{Slot:27b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot27 {Inventory:[{Slot:27b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot27 {Inventory:[{Slot:27b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot27 {Inventory:[{Slot:27b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot27 {Inventory:[{Slot:27b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot27 {Inventory:[{Slot:27b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot27 {Inventory:[{Slot:27b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot27 {Inventory:[{Slot:27b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot27 {Inventory:[{Slot:27b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot27 {Inventory:[{Slot:27b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot27 {Inventory:[{Slot:27b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot27 {Inventory:[{Slot:27b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot27 {Inventory:[{Slot:27b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot27 {Inventory:[{Slot:27b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot27 {Inventory:[{Slot:27b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot27 {Inventory:[{Slot:27b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot27 {Inventory:[{Slot:27b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot27 {Inventory:[{Slot:27b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot27 {Inventory:[{Slot:27b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot27 {Inventory:[{Slot:27b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot27 {Inventory:[{Slot:27b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot27 {Inventory:[{Slot:27b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot27 {Inventory:[{Slot:27b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot27 {Inventory:[{Slot:27b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot27 {Inventory:[{Slot:27b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot27 {Inventory:[{Slot:27b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot27 {Inventory:[{Slot:27b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot27 {Inventory:[{Slot:27b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot27 {Inventory:[{Slot:27b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot27 {Inventory:[{Slot:27b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot27 {Inventory:[{Slot:27b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot27 {Inventory:[{Slot:27b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot27 {Inventory:[{Slot:27b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot27 {Inventory:[{Slot:27b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot27 {Inventory:[{Slot:27b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot27 {Inventory:[{Slot:27b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot27 {Inventory:[{Slot:27b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot27 {Inventory:[{Slot:27b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot27 {Inventory:[{Slot:27b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot27 {Inventory:[{Slot:27b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot27 {Inventory:[{Slot:27b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot27 {Inventory:[{Slot:27b,id:"minecraft:structure_block",Damage:0s}]}
