scoreboard players tag @s add AirInSlot29 {Inventory:[{Slot:29b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot29 {Inventory:[{Slot:29b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot29 {Inventory:[{Slot:29b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot29 {Inventory:[{Slot:29b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot29 {Inventory:[{Slot:29b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot29 {Inventory:[{Slot:29b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot29 {Inventory:[{Slot:29b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot29 {Inventory:[{Slot:29b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot29 {Inventory:[{Slot:29b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot29 {Inventory:[{Slot:29b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot29 {Inventory:[{Slot:29b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot29 {Inventory:[{Slot:29b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot29 {Inventory:[{Slot:29b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot29 {Inventory:[{Slot:29b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot29 {Inventory:[{Slot:29b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot29 {Inventory:[{Slot:29b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot29 {Inventory:[{Slot:29b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot29 {Inventory:[{Slot:29b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot29 {Inventory:[{Slot:29b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot29 {Inventory:[{Slot:29b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot29 {Inventory:[{Slot:29b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot29 {Inventory:[{Slot:29b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot29 {Inventory:[{Slot:29b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot29 {Inventory:[{Slot:29b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot29 {Inventory:[{Slot:29b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot29 {Inventory:[{Slot:29b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot29 {Inventory:[{Slot:29b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot29 {Inventory:[{Slot:29b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot29 {Inventory:[{Slot:29b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot29 {Inventory:[{Slot:29b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot29 {Inventory:[{Slot:29b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot29 {Inventory:[{Slot:29b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot29 {Inventory:[{Slot:29b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot29 {Inventory:[{Slot:29b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot29 {Inventory:[{Slot:29b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot29 {Inventory:[{Slot:29b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot29 {Inventory:[{Slot:29b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot29 {Inventory:[{Slot:29b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot29 {Inventory:[{Slot:29b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot29 {Inventory:[{Slot:29b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot29 {Inventory:[{Slot:29b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot29 {Inventory:[{Slot:29b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot29 {Inventory:[{Slot:29b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot29 {Inventory:[{Slot:29b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot29 {Inventory:[{Slot:29b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot29 {Inventory:[{Slot:29b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot29 {Inventory:[{Slot:29b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot29 {Inventory:[{Slot:29b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot29 {Inventory:[{Slot:29b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot29 {Inventory:[{Slot:29b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot29 {Inventory:[{Slot:29b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot29 {Inventory:[{Slot:29b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot29 {Inventory:[{Slot:29b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot29 {Inventory:[{Slot:29b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot29 {Inventory:[{Slot:29b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot29 {Inventory:[{Slot:29b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot29 {Inventory:[{Slot:29b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot29 {Inventory:[{Slot:29b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot29 {Inventory:[{Slot:29b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot29 {Inventory:[{Slot:29b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot29 {Inventory:[{Slot:29b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot29 {Inventory:[{Slot:29b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot29 {Inventory:[{Slot:29b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot29 {Inventory:[{Slot:29b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot29 {Inventory:[{Slot:29b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot29 {Inventory:[{Slot:29b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot29 {Inventory:[{Slot:29b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot29 {Inventory:[{Slot:29b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot29 {Inventory:[{Slot:29b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot29 {Inventory:[{Slot:29b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot29 {Inventory:[{Slot:29b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot29 {Inventory:[{Slot:29b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot29 {Inventory:[{Slot:29b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot29 {Inventory:[{Slot:29b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot29 {Inventory:[{Slot:29b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot29 {Inventory:[{Slot:29b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot29 {Inventory:[{Slot:29b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot29 {Inventory:[{Slot:29b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot29 {Inventory:[{Slot:29b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot29 {Inventory:[{Slot:29b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot29 {Inventory:[{Slot:29b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot29 {Inventory:[{Slot:29b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot29 {Inventory:[{Slot:29b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot29 {Inventory:[{Slot:29b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot29 {Inventory:[{Slot:29b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot29] ~ ~ ~ execute @s[tag=!StoneInSlot29] ~ ~ ~ execute @s[tag=!GraniteInSlot29] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot29] ~ ~ ~ execute @s[tag=!DioriteInSlot29] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot29] ~ ~ ~ execute @s[tag=!AndesiteInSlot29] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot29] ~ ~ ~ execute @s[tag=!GrassBlockInSlot29] ~ ~ ~ execute @s[tag=!DirtInSlot29] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot29] ~ ~ ~ execute @s[tag=!PodzolInSlot29] ~ ~ ~ execute @s[tag=!CobblestoneInSlot29] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot29] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot29] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot29] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot29] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot29] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot29] ~ ~ ~ execute @s[tag=!OakSaplingInSlot29] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot29] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot29] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot29] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot29] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot29] ~ ~ ~ execute @s[tag=!BedrockInSlot29] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot29] ~ ~ ~ execute @s[tag=!StillWaterInSlot29] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot29] ~ ~ ~ execute @s[tag=!StillLavaInSlot29] ~ ~ ~ execute @s[tag=!SandInSlot29] ~ ~ ~ execute @s[tag=!RedSandInSlot29] ~ ~ ~ execute @s[tag=!GravelInSlot29] ~ ~ ~ execute @s[tag=!GoldOreInSlot29] ~ ~ ~ execute @s[tag=!IronOreInSlot29] ~ ~ ~ execute @s[tag=!CoalOreInSlot29] ~ ~ ~ execute @s[tag=!OakWoodInSlot29] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot29] ~ ~ ~ execute @s[tag=!BirchWoodInSlot29] ~ ~ ~ execute @s[tag=!JungleWoodInSlot29] ~ ~ ~ execute @s[tag=!OakLeavesInSlot29] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot29] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot29] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot29] ~ ~ ~ execute @s[tag=!SpongeInSlot29] ~ ~ ~ execute @s[tag=!WetSpongeInSlot29] ~ ~ ~ execute @s[tag=!GlassInSlot29] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot29] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot29] ~ ~ ~ execute @s[tag=!DispenserInSlot29] ~ ~ ~ execute @s[tag=!SandstoneInSlot29] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot29] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot29] ~ ~ ~ execute @s[tag=!NoteBlockInSlot29] ~ ~ ~ execute @s[tag=!BedInSlot29] ~ ~ ~ execute @s[tag=!PoweredRailInSlot29] ~ ~ ~ execute @s[tag=!DetectorRailInSlot29] ~ ~ ~ execute @s[tag=!StickyPistonInSlot29] ~ ~ ~ execute @s[tag=!CobwebInSlot29] ~ ~ ~ execute @s[tag=!DeadShrubInSlot29] ~ ~ ~ execute @s[tag=!GrassInSlot29] ~ ~ ~ execute @s[tag=!FernInSlot29] ~ ~ ~ execute @s[tag=!DeadBushInSlot29] ~ ~ ~ execute @s[tag=!PistonInSlot29] ~ ~ ~ execute @s[tag=!PistonHeadInSlot29] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot29] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot29] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot29] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot29] ~ ~ ~ execute @s[tag=!YellowWoolInSlot29] ~ ~ ~ execute @s[tag=!LimeWoolInSlot29] ~ ~ ~ execute @s[tag=!PinkWoolInSlot29] ~ ~ ~ execute @s[tag=!GrayWoolInSlot29] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot29] ~ ~ ~ execute @s[tag=!CyanWoolInSlot29] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot29] ~ ~ ~ execute @s[tag=!BlueWoolInSlot29] ~ ~ ~ execute @s[tag=!BrownWoolInSlot29] ~ ~ ~ execute @s[tag=!GreenWoolInSlot29] ~ ~ ~ execute @s[tag=!RedWoolInSlot29] ~ ~ ~ execute @s[tag=!BlackWoolInSlot29] ~ ~ ~ execute @s[tag=!DandelionInSlot29] ~ ~ ~ execute @s[tag=!PoppyInSlot29] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot29] ~ ~ ~ execute @s[tag=!AlliumInSlot29] ~ ~ ~ execute @s[tag=!AzureBluetInSlot29] ~ ~ ~ execute @s[tag=!RedTulipInSlot29] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot29] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot29] ~ ~ ~ execute @s[tag=!PinkTulipInSlot29] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot29] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot29] ~ ~ ~ execute @s[tag=!RedMushroomInSlot29] ~ ~ ~ execute @s[tag=!GoldBlockInSlot29] ~ ~ ~ execute @s[tag=!IronBlockInSlot29] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot29] ~ ~ ~ execute @s[tag=!StoneSlabInSlot29] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot29] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot29] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot29] ~ ~ ~ execute @s[tag=!BrickSlabInSlot29] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot29] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot29] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot29] ~ ~ ~ execute @s[tag=!BricksInSlot29] ~ ~ ~ execute @s[tag=!TNTInSlot29] ~ ~ ~ execute @s[tag=!BookshelfInSlot29] ~ ~ ~ execute @s[tag=!MossStoneInSlot29] ~ ~ ~ execute @s[tag=!ObsidianInSlot29] ~ ~ ~ execute @s[tag=!TorchInSlot29] ~ ~ ~ execute @s[tag=!FireInSlot29] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot29] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot29] ~ ~ ~ execute @s[tag=!ChestInSlot29] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot29] ~ ~ ~ execute @s[tag=!DiamondOreInSlot29] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot29] ~ ~ ~ execute @s[tag=!CraftingTableInSlot29] ~ ~ ~ execute @s[tag=!WheatCropsInSlot29] ~ ~ ~ execute @s[tag=!FarmlandInSlot29] ~ ~ ~ execute @s[tag=!FurnaceInSlot29] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot29] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot29] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!LadderInSlot29] ~ ~ ~ execute @s[tag=!RailInSlot29] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot29] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot29] ~ ~ ~ execute @s[tag=!LeverInSlot29] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot29] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot29] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot29] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot29] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot29] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot29] ~ ~ ~ execute @s[tag=!StoneButtonInSlot29] ~ ~ ~ execute @s[tag=!SnowInSlot29] ~ ~ ~ execute @s[tag=!IceInSlot29] ~ ~ ~ execute @s[tag=!SnowBlockInSlot29] ~ ~ ~ execute @s[tag=!CactusInSlot29] ~ ~ ~ execute @s[tag=!SugarCanesInSlot29] ~ ~ ~ execute @s[tag=!JukeboxInSlot29] ~ ~ ~ execute @s[tag=!OakFenceInSlot29] ~ ~ ~ execute @s[tag=!PumpkinInSlot29] ~ ~ ~ execute @s[tag=!NetherrackInSlot29] ~ ~ ~ execute @s[tag=!SoulSandInSlot29] ~ ~ ~ execute @s[tag=!GlowstoneInSlot29] ~ ~ ~ execute @s[tag=!NetherPortalInSlot29] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot29] ~ ~ ~ execute @s[tag=!CakeBlockInSlot29] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot29] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot29] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot29] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot29] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot29] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot29] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot29] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot29] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot29] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot29] ~ ~ ~ execute @s[tag=!StoneBricksInSlot29] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot29] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot29] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot29] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot29] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot29] ~ ~ ~ execute @s[tag=!IronBarsInSlot29] ~ ~ ~ execute @s[tag=!GlassPaneInSlot29] ~ ~ ~ execute @s[tag=!MelonBlockInSlot29] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot29] ~ ~ ~ execute @s[tag=!MelonStemInSlot29] ~ ~ ~ execute @s[tag=!VinesInSlot29] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot29] ~ ~ ~ execute @s[tag=!BrickStairsInSlot29] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot29] ~ ~ ~ execute @s[tag=!MyceliumInSlot29] ~ ~ ~ execute @s[tag=!LilyPadInSlot29] ~ ~ ~ execute @s[tag=!NetherBrickInSlot29] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot29] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot29] ~ ~ ~ execute @s[tag=!NetherWartInSlot29] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot29] ~ ~ ~ execute @s[tag=!BrewingStandInSlot29] ~ ~ ~ execute @s[tag=!CauldronInSlot29] ~ ~ ~ execute @s[tag=!EndPortalInSlot29] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot29] ~ ~ ~ execute @s[tag=!EndStoneInSlot29] ~ ~ ~ execute @s[tag=!DragonEggInSlot29] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot29] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot29] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot29] ~ ~ ~ execute @s[tag=!CocoaInSlot29] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot29] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot29] ~ ~ ~ execute @s[tag=!EnderChestInSlot29] ~ ~ ~ execute @s[tag=!TripwireHookInSlot29] ~ ~ ~ execute @s[tag=!TripwireInSlot29] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot29] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot29] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot29] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot29] ~ ~ ~ execute @s[tag=!CommandBlockInSlot29] ~ ~ ~ execute @s[tag=!BeaconInSlot29] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot29] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot29] ~ ~ ~ execute @s[tag=!FlowerPotInSlot29] ~ ~ ~ execute @s[tag=!CarrotsInSlot29] ~ ~ ~ execute @s[tag=!PotatoesInSlot29] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot29] ~ ~ ~ execute @s[tag=!MobHeadInSlot29] ~ ~ ~ execute @s[tag=!AnvilInSlot29] ~ ~ ~ execute @s[tag=!TrappedChestInSlot29] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot29] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot29] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot29] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot29] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot29] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot29] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot29] ~ ~ ~ execute @s[tag=!HopperInSlot29] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot29] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot29] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot29] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot29] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot29] ~ ~ ~ execute @s[tag=!DropperInSlot29] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot29] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot29] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot29] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot29] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot29] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot29] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot29] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot29] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot29] ~ ~ ~ execute @s[tag=!BarrierInSlot29] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot29] ~ ~ ~ execute @s[tag=!PrismarineInSlot29] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot29] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot29] ~ ~ ~ execute @s[tag=!SeaLanternInSlot29] ~ ~ ~ execute @s[tag=!HayBaleInSlot29] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot29] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot29] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot29] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot29] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot29] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot29] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot29] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot29] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot29] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot29] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot29] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot29] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot29] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot29] ~ ~ ~ execute @s[tag=!RedCarpetInSlot29] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot29] ~ ~ ~ execute @s[tag=!HardenedClayInSlot29] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot29] ~ ~ ~ execute @s[tag=!PackedIceInSlot29] ~ ~ ~ execute @s[tag=!SunflowerInSlot29] ~ ~ ~ execute @s[tag=!LilacInSlot29] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot29] ~ ~ ~ execute @s[tag=!LargeFernInSlot29] ~ ~ ~ execute @s[tag=!RoseBushInSlot29] ~ ~ ~ execute @s[tag=!PeonyInSlot29] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot29] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot29] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot29] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot29] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot29] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot29] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot29] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot29] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot29] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot29] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot29] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot29] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot29] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot29] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot29] ~ ~ ~ execute @s[tag=!BirchFenceInSlot29] ~ ~ ~ execute @s[tag=!JungleFenceInSlot29] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot29] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot29] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot29] ~ ~ ~ execute @s[tag=!EndRodInSlot29] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot29] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot29] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot29] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot29] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot29] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot29] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot29] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot29] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot29] ~ ~ ~ execute @s[tag=!GrassPathInSlot29] ~ ~ ~ execute @s[tag=!EndGatewayInSlot29] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot29] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot29] ~ ~ ~ execute @s[tag=!FrostedIceInSlot29] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot29] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot29] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot29] ~ ~ ~ execute @s[tag=!BoneBlockInSlot29] ~ ~ ~ execute @s[tag=!StructureVoidInSlot29] ~ ~ ~ execute @s[tag=!ObserverInSlot29] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot29] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot29] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot29] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot29] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot29] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot29] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot29] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot29] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot29] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot29] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot29] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot29] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot29] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot29] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot29] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot29] ~ ~ ~ execute @s[tag=!RedConcreteInSlot29] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot29] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot29] ~ ~ ~ execute @s[tag=!StructureBlockInSlot29] ~ ~ ~ scoreboard players tag @s add AirInSlot29 