scoreboard players tag @s add AirInSlot35 {Inventory:[{Slot:35b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot35 {Inventory:[{Slot:35b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot35 {Inventory:[{Slot:35b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot35 {Inventory:[{Slot:35b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot35 {Inventory:[{Slot:35b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot35 {Inventory:[{Slot:35b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot35 {Inventory:[{Slot:35b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot35 {Inventory:[{Slot:35b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot35 {Inventory:[{Slot:35b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot35 {Inventory:[{Slot:35b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot35 {Inventory:[{Slot:35b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot35 {Inventory:[{Slot:35b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot35 {Inventory:[{Slot:35b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot35 {Inventory:[{Slot:35b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot35 {Inventory:[{Slot:35b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot35 {Inventory:[{Slot:35b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot35 {Inventory:[{Slot:35b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot35 {Inventory:[{Slot:35b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot35 {Inventory:[{Slot:35b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot35 {Inventory:[{Slot:35b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot35 {Inventory:[{Slot:35b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot35 {Inventory:[{Slot:35b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot35 {Inventory:[{Slot:35b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot35 {Inventory:[{Slot:35b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot35 {Inventory:[{Slot:35b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot35 {Inventory:[{Slot:35b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot35 {Inventory:[{Slot:35b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot35 {Inventory:[{Slot:35b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot35 {Inventory:[{Slot:35b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot35 {Inventory:[{Slot:35b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot35 {Inventory:[{Slot:35b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot35 {Inventory:[{Slot:35b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot35 {Inventory:[{Slot:35b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot35 {Inventory:[{Slot:35b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot35 {Inventory:[{Slot:35b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot35 {Inventory:[{Slot:35b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot35 {Inventory:[{Slot:35b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot35 {Inventory:[{Slot:35b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot35 {Inventory:[{Slot:35b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot35 {Inventory:[{Slot:35b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot35 {Inventory:[{Slot:35b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot35 {Inventory:[{Slot:35b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot35 {Inventory:[{Slot:35b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot35 {Inventory:[{Slot:35b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot35 {Inventory:[{Slot:35b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot35 {Inventory:[{Slot:35b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot35 {Inventory:[{Slot:35b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot35 {Inventory:[{Slot:35b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot35 {Inventory:[{Slot:35b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot35 {Inventory:[{Slot:35b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot35 {Inventory:[{Slot:35b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot35 {Inventory:[{Slot:35b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot35 {Inventory:[{Slot:35b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot35 {Inventory:[{Slot:35b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot35 {Inventory:[{Slot:35b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot35 {Inventory:[{Slot:35b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot35 {Inventory:[{Slot:35b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot35 {Inventory:[{Slot:35b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot35 {Inventory:[{Slot:35b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot35 {Inventory:[{Slot:35b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot35 {Inventory:[{Slot:35b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot35 {Inventory:[{Slot:35b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot35 {Inventory:[{Slot:35b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot35 {Inventory:[{Slot:35b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot35 {Inventory:[{Slot:35b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot35 {Inventory:[{Slot:35b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot35 {Inventory:[{Slot:35b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot35 {Inventory:[{Slot:35b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot35 {Inventory:[{Slot:35b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot35 {Inventory:[{Slot:35b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot35 {Inventory:[{Slot:35b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot35 {Inventory:[{Slot:35b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot35 {Inventory:[{Slot:35b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot35 {Inventory:[{Slot:35b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot35 {Inventory:[{Slot:35b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot35 {Inventory:[{Slot:35b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot35 {Inventory:[{Slot:35b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot35 {Inventory:[{Slot:35b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot35 {Inventory:[{Slot:35b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot35 {Inventory:[{Slot:35b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot35 {Inventory:[{Slot:35b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot35 {Inventory:[{Slot:35b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot35 {Inventory:[{Slot:35b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot35 {Inventory:[{Slot:35b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot35 {Inventory:[{Slot:35b,id:"minecraft:structure_block",Damage:0s}]}
