scoreboard players tag @a add AirInSlot26 {Inventory:[{Slot:26b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot26 {Inventory:[{Slot:26b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot26 {Inventory:[{Slot:26b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot26 {Inventory:[{Slot:26b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot26 {Inventory:[{Slot:26b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot26 {Inventory:[{Slot:26b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot26 {Inventory:[{Slot:26b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot26 {Inventory:[{Slot:26b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot26 {Inventory:[{Slot:26b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot26 {Inventory:[{Slot:26b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot26 {Inventory:[{Slot:26b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot26 {Inventory:[{Slot:26b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot26 {Inventory:[{Slot:26b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot26 {Inventory:[{Slot:26b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot26 {Inventory:[{Slot:26b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot26 {Inventory:[{Slot:26b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot26 {Inventory:[{Slot:26b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot26 {Inventory:[{Slot:26b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot26 {Inventory:[{Slot:26b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot26 {Inventory:[{Slot:26b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot26 {Inventory:[{Slot:26b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot26 {Inventory:[{Slot:26b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot26 {Inventory:[{Slot:26b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot26 {Inventory:[{Slot:26b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot26 {Inventory:[{Slot:26b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot26 {Inventory:[{Slot:26b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot26 {Inventory:[{Slot:26b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot26 {Inventory:[{Slot:26b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot26 {Inventory:[{Slot:26b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot26 {Inventory:[{Slot:26b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot26 {Inventory:[{Slot:26b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot26 {Inventory:[{Slot:26b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot26 {Inventory:[{Slot:26b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:structure_block",Damage:0s}]}
