scoreboard players tag @s add AirInSlot33 {Inventory:[{Slot:33b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot33 {Inventory:[{Slot:33b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot33 {Inventory:[{Slot:33b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot33 {Inventory:[{Slot:33b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot33 {Inventory:[{Slot:33b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot33 {Inventory:[{Slot:33b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot33 {Inventory:[{Slot:33b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot33 {Inventory:[{Slot:33b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot33 {Inventory:[{Slot:33b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot33 {Inventory:[{Slot:33b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot33 {Inventory:[{Slot:33b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot33 {Inventory:[{Slot:33b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot33 {Inventory:[{Slot:33b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot33 {Inventory:[{Slot:33b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot33 {Inventory:[{Slot:33b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot33 {Inventory:[{Slot:33b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot33 {Inventory:[{Slot:33b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot33 {Inventory:[{Slot:33b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot33 {Inventory:[{Slot:33b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot33 {Inventory:[{Slot:33b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot33 {Inventory:[{Slot:33b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot33 {Inventory:[{Slot:33b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot33 {Inventory:[{Slot:33b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot33 {Inventory:[{Slot:33b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot33 {Inventory:[{Slot:33b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot33 {Inventory:[{Slot:33b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot33 {Inventory:[{Slot:33b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot33 {Inventory:[{Slot:33b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot33 {Inventory:[{Slot:33b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot33 {Inventory:[{Slot:33b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot33 {Inventory:[{Slot:33b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot33 {Inventory:[{Slot:33b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot33 {Inventory:[{Slot:33b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot33 {Inventory:[{Slot:33b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot33 {Inventory:[{Slot:33b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot33 {Inventory:[{Slot:33b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot33 {Inventory:[{Slot:33b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot33 {Inventory:[{Slot:33b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot33 {Inventory:[{Slot:33b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot33 {Inventory:[{Slot:33b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot33 {Inventory:[{Slot:33b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot33 {Inventory:[{Slot:33b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot33 {Inventory:[{Slot:33b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot33 {Inventory:[{Slot:33b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot33 {Inventory:[{Slot:33b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot33 {Inventory:[{Slot:33b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot33 {Inventory:[{Slot:33b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot33 {Inventory:[{Slot:33b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot33 {Inventory:[{Slot:33b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot33 {Inventory:[{Slot:33b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot33 {Inventory:[{Slot:33b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot33 {Inventory:[{Slot:33b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot33 {Inventory:[{Slot:33b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot33 {Inventory:[{Slot:33b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot33 {Inventory:[{Slot:33b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot33 {Inventory:[{Slot:33b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot33 {Inventory:[{Slot:33b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot33 {Inventory:[{Slot:33b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot33 {Inventory:[{Slot:33b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot33 {Inventory:[{Slot:33b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot33 {Inventory:[{Slot:33b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot33 {Inventory:[{Slot:33b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot33 {Inventory:[{Slot:33b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot33 {Inventory:[{Slot:33b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot33 {Inventory:[{Slot:33b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot33 {Inventory:[{Slot:33b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot33 {Inventory:[{Slot:33b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot33 {Inventory:[{Slot:33b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot33 {Inventory:[{Slot:33b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot33 {Inventory:[{Slot:33b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot33 {Inventory:[{Slot:33b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot33 {Inventory:[{Slot:33b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot33 {Inventory:[{Slot:33b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot33 {Inventory:[{Slot:33b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot33 {Inventory:[{Slot:33b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot33 {Inventory:[{Slot:33b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot33 {Inventory:[{Slot:33b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot33 {Inventory:[{Slot:33b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot33 {Inventory:[{Slot:33b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot33 {Inventory:[{Slot:33b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot33 {Inventory:[{Slot:33b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot33 {Inventory:[{Slot:33b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot33 {Inventory:[{Slot:33b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot33 {Inventory:[{Slot:33b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot33 {Inventory:[{Slot:33b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot33] ~ ~ ~ execute @s[tag=!StoneInSlot33] ~ ~ ~ execute @s[tag=!GraniteInSlot33] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot33] ~ ~ ~ execute @s[tag=!DioriteInSlot33] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot33] ~ ~ ~ execute @s[tag=!AndesiteInSlot33] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot33] ~ ~ ~ execute @s[tag=!GrassBlockInSlot33] ~ ~ ~ execute @s[tag=!DirtInSlot33] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot33] ~ ~ ~ execute @s[tag=!PodzolInSlot33] ~ ~ ~ execute @s[tag=!CobblestoneInSlot33] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot33] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot33] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot33] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot33] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot33] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot33] ~ ~ ~ execute @s[tag=!OakSaplingInSlot33] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot33] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot33] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot33] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot33] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot33] ~ ~ ~ execute @s[tag=!BedrockInSlot33] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot33] ~ ~ ~ execute @s[tag=!StillWaterInSlot33] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot33] ~ ~ ~ execute @s[tag=!StillLavaInSlot33] ~ ~ ~ execute @s[tag=!SandInSlot33] ~ ~ ~ execute @s[tag=!RedSandInSlot33] ~ ~ ~ execute @s[tag=!GravelInSlot33] ~ ~ ~ execute @s[tag=!GoldOreInSlot33] ~ ~ ~ execute @s[tag=!IronOreInSlot33] ~ ~ ~ execute @s[tag=!CoalOreInSlot33] ~ ~ ~ execute @s[tag=!OakWoodInSlot33] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot33] ~ ~ ~ execute @s[tag=!BirchWoodInSlot33] ~ ~ ~ execute @s[tag=!JungleWoodInSlot33] ~ ~ ~ execute @s[tag=!OakLeavesInSlot33] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot33] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot33] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot33] ~ ~ ~ execute @s[tag=!SpongeInSlot33] ~ ~ ~ execute @s[tag=!WetSpongeInSlot33] ~ ~ ~ execute @s[tag=!GlassInSlot33] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot33] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot33] ~ ~ ~ execute @s[tag=!DispenserInSlot33] ~ ~ ~ execute @s[tag=!SandstoneInSlot33] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot33] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot33] ~ ~ ~ execute @s[tag=!NoteBlockInSlot33] ~ ~ ~ execute @s[tag=!BedInSlot33] ~ ~ ~ execute @s[tag=!PoweredRailInSlot33] ~ ~ ~ execute @s[tag=!DetectorRailInSlot33] ~ ~ ~ execute @s[tag=!StickyPistonInSlot33] ~ ~ ~ execute @s[tag=!CobwebInSlot33] ~ ~ ~ execute @s[tag=!DeadShrubInSlot33] ~ ~ ~ execute @s[tag=!GrassInSlot33] ~ ~ ~ execute @s[tag=!FernInSlot33] ~ ~ ~ execute @s[tag=!DeadBushInSlot33] ~ ~ ~ execute @s[tag=!PistonInSlot33] ~ ~ ~ execute @s[tag=!PistonHeadInSlot33] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot33] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot33] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot33] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot33] ~ ~ ~ execute @s[tag=!YellowWoolInSlot33] ~ ~ ~ execute @s[tag=!LimeWoolInSlot33] ~ ~ ~ execute @s[tag=!PinkWoolInSlot33] ~ ~ ~ execute @s[tag=!GrayWoolInSlot33] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot33] ~ ~ ~ execute @s[tag=!CyanWoolInSlot33] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot33] ~ ~ ~ execute @s[tag=!BlueWoolInSlot33] ~ ~ ~ execute @s[tag=!BrownWoolInSlot33] ~ ~ ~ execute @s[tag=!GreenWoolInSlot33] ~ ~ ~ execute @s[tag=!RedWoolInSlot33] ~ ~ ~ execute @s[tag=!BlackWoolInSlot33] ~ ~ ~ execute @s[tag=!DandelionInSlot33] ~ ~ ~ execute @s[tag=!PoppyInSlot33] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot33] ~ ~ ~ execute @s[tag=!AlliumInSlot33] ~ ~ ~ execute @s[tag=!AzureBluetInSlot33] ~ ~ ~ execute @s[tag=!RedTulipInSlot33] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot33] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot33] ~ ~ ~ execute @s[tag=!PinkTulipInSlot33] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot33] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot33] ~ ~ ~ execute @s[tag=!RedMushroomInSlot33] ~ ~ ~ execute @s[tag=!GoldBlockInSlot33] ~ ~ ~ execute @s[tag=!IronBlockInSlot33] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot33] ~ ~ ~ execute @s[tag=!StoneSlabInSlot33] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot33] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot33] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot33] ~ ~ ~ execute @s[tag=!BrickSlabInSlot33] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot33] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot33] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot33] ~ ~ ~ execute @s[tag=!BricksInSlot33] ~ ~ ~ execute @s[tag=!TNTInSlot33] ~ ~ ~ execute @s[tag=!BookshelfInSlot33] ~ ~ ~ execute @s[tag=!MossStoneInSlot33] ~ ~ ~ execute @s[tag=!ObsidianInSlot33] ~ ~ ~ execute @s[tag=!TorchInSlot33] ~ ~ ~ execute @s[tag=!FireInSlot33] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot33] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot33] ~ ~ ~ execute @s[tag=!ChestInSlot33] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot33] ~ ~ ~ execute @s[tag=!DiamondOreInSlot33] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot33] ~ ~ ~ execute @s[tag=!CraftingTableInSlot33] ~ ~ ~ execute @s[tag=!WheatCropsInSlot33] ~ ~ ~ execute @s[tag=!FarmlandInSlot33] ~ ~ ~ execute @s[tag=!FurnaceInSlot33] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot33] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot33] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!LadderInSlot33] ~ ~ ~ execute @s[tag=!RailInSlot33] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot33] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot33] ~ ~ ~ execute @s[tag=!LeverInSlot33] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot33] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot33] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot33] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot33] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot33] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot33] ~ ~ ~ execute @s[tag=!StoneButtonInSlot33] ~ ~ ~ execute @s[tag=!SnowInSlot33] ~ ~ ~ execute @s[tag=!IceInSlot33] ~ ~ ~ execute @s[tag=!SnowBlockInSlot33] ~ ~ ~ execute @s[tag=!CactusInSlot33] ~ ~ ~ execute @s[tag=!SugarCanesInSlot33] ~ ~ ~ execute @s[tag=!JukeboxInSlot33] ~ ~ ~ execute @s[tag=!OakFenceInSlot33] ~ ~ ~ execute @s[tag=!PumpkinInSlot33] ~ ~ ~ execute @s[tag=!NetherrackInSlot33] ~ ~ ~ execute @s[tag=!SoulSandInSlot33] ~ ~ ~ execute @s[tag=!GlowstoneInSlot33] ~ ~ ~ execute @s[tag=!NetherPortalInSlot33] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot33] ~ ~ ~ execute @s[tag=!CakeBlockInSlot33] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot33] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot33] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot33] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot33] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot33] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot33] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot33] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot33] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot33] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot33] ~ ~ ~ execute @s[tag=!StoneBricksInSlot33] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot33] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot33] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot33] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot33] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot33] ~ ~ ~ execute @s[tag=!IronBarsInSlot33] ~ ~ ~ execute @s[tag=!GlassPaneInSlot33] ~ ~ ~ execute @s[tag=!MelonBlockInSlot33] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot33] ~ ~ ~ execute @s[tag=!MelonStemInSlot33] ~ ~ ~ execute @s[tag=!VinesInSlot33] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot33] ~ ~ ~ execute @s[tag=!BrickStairsInSlot33] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot33] ~ ~ ~ execute @s[tag=!MyceliumInSlot33] ~ ~ ~ execute @s[tag=!LilyPadInSlot33] ~ ~ ~ execute @s[tag=!NetherBrickInSlot33] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot33] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot33] ~ ~ ~ execute @s[tag=!NetherWartInSlot33] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot33] ~ ~ ~ execute @s[tag=!BrewingStandInSlot33] ~ ~ ~ execute @s[tag=!CauldronInSlot33] ~ ~ ~ execute @s[tag=!EndPortalInSlot33] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot33] ~ ~ ~ execute @s[tag=!EndStoneInSlot33] ~ ~ ~ execute @s[tag=!DragonEggInSlot33] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot33] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot33] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot33] ~ ~ ~ execute @s[tag=!CocoaInSlot33] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot33] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot33] ~ ~ ~ execute @s[tag=!EnderChestInSlot33] ~ ~ ~ execute @s[tag=!TripwireHookInSlot33] ~ ~ ~ execute @s[tag=!TripwireInSlot33] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot33] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot33] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot33] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot33] ~ ~ ~ execute @s[tag=!CommandBlockInSlot33] ~ ~ ~ execute @s[tag=!BeaconInSlot33] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot33] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot33] ~ ~ ~ execute @s[tag=!FlowerPotInSlot33] ~ ~ ~ execute @s[tag=!CarrotsInSlot33] ~ ~ ~ execute @s[tag=!PotatoesInSlot33] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot33] ~ ~ ~ execute @s[tag=!MobHeadInSlot33] ~ ~ ~ execute @s[tag=!AnvilInSlot33] ~ ~ ~ execute @s[tag=!TrappedChestInSlot33] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot33] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot33] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot33] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot33] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot33] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot33] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot33] ~ ~ ~ execute @s[tag=!HopperInSlot33] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot33] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot33] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot33] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot33] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot33] ~ ~ ~ execute @s[tag=!DropperInSlot33] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot33] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot33] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot33] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot33] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot33] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot33] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot33] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot33] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot33] ~ ~ ~ execute @s[tag=!BarrierInSlot33] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot33] ~ ~ ~ execute @s[tag=!PrismarineInSlot33] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot33] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot33] ~ ~ ~ execute @s[tag=!SeaLanternInSlot33] ~ ~ ~ execute @s[tag=!HayBaleInSlot33] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot33] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot33] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot33] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot33] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot33] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot33] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot33] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot33] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot33] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot33] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot33] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot33] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot33] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot33] ~ ~ ~ execute @s[tag=!RedCarpetInSlot33] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot33] ~ ~ ~ execute @s[tag=!HardenedClayInSlot33] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot33] ~ ~ ~ execute @s[tag=!PackedIceInSlot33] ~ ~ ~ execute @s[tag=!SunflowerInSlot33] ~ ~ ~ execute @s[tag=!LilacInSlot33] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot33] ~ ~ ~ execute @s[tag=!LargeFernInSlot33] ~ ~ ~ execute @s[tag=!RoseBushInSlot33] ~ ~ ~ execute @s[tag=!PeonyInSlot33] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot33] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot33] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot33] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot33] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot33] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot33] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot33] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot33] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot33] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot33] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot33] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot33] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot33] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot33] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot33] ~ ~ ~ execute @s[tag=!BirchFenceInSlot33] ~ ~ ~ execute @s[tag=!JungleFenceInSlot33] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot33] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot33] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot33] ~ ~ ~ execute @s[tag=!EndRodInSlot33] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot33] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot33] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot33] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot33] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot33] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot33] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot33] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot33] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot33] ~ ~ ~ execute @s[tag=!GrassPathInSlot33] ~ ~ ~ execute @s[tag=!EndGatewayInSlot33] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot33] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot33] ~ ~ ~ execute @s[tag=!FrostedIceInSlot33] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot33] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot33] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot33] ~ ~ ~ execute @s[tag=!BoneBlockInSlot33] ~ ~ ~ execute @s[tag=!StructureVoidInSlot33] ~ ~ ~ execute @s[tag=!ObserverInSlot33] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot33] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot33] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot33] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot33] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot33] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot33] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot33] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot33] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot33] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot33] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot33] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot33] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot33] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot33] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot33] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot33] ~ ~ ~ execute @s[tag=!RedConcreteInSlot33] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot33] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot33] ~ ~ ~ execute @s[tag=!StructureBlockInSlot33] ~ ~ ~ scoreboard players tag @s add AirInSlot33 