scoreboard players tag @s add AirInSlot19 {Inventory:[{Slot:19b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot19 {Inventory:[{Slot:19b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot19 {Inventory:[{Slot:19b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot19 {Inventory:[{Slot:19b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot19 {Inventory:[{Slot:19b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot19 {Inventory:[{Slot:19b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot19 {Inventory:[{Slot:19b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot19 {Inventory:[{Slot:19b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot19 {Inventory:[{Slot:19b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot19 {Inventory:[{Slot:19b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot19 {Inventory:[{Slot:19b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot19 {Inventory:[{Slot:19b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot19 {Inventory:[{Slot:19b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot19 {Inventory:[{Slot:19b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot19 {Inventory:[{Slot:19b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot19 {Inventory:[{Slot:19b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot19 {Inventory:[{Slot:19b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot19 {Inventory:[{Slot:19b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot19 {Inventory:[{Slot:19b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot19 {Inventory:[{Slot:19b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot19 {Inventory:[{Slot:19b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot19 {Inventory:[{Slot:19b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot19 {Inventory:[{Slot:19b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot19 {Inventory:[{Slot:19b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot19 {Inventory:[{Slot:19b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot19 {Inventory:[{Slot:19b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot19 {Inventory:[{Slot:19b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot19 {Inventory:[{Slot:19b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot19 {Inventory:[{Slot:19b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot19 {Inventory:[{Slot:19b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot19 {Inventory:[{Slot:19b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot19 {Inventory:[{Slot:19b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot19 {Inventory:[{Slot:19b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot19 {Inventory:[{Slot:19b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot19 {Inventory:[{Slot:19b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot19 {Inventory:[{Slot:19b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot19 {Inventory:[{Slot:19b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot19 {Inventory:[{Slot:19b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot19 {Inventory:[{Slot:19b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot19 {Inventory:[{Slot:19b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot19 {Inventory:[{Slot:19b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot19 {Inventory:[{Slot:19b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot19 {Inventory:[{Slot:19b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot19 {Inventory:[{Slot:19b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot19 {Inventory:[{Slot:19b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot19 {Inventory:[{Slot:19b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot19 {Inventory:[{Slot:19b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot19 {Inventory:[{Slot:19b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot19 {Inventory:[{Slot:19b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot19 {Inventory:[{Slot:19b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot19 {Inventory:[{Slot:19b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot19 {Inventory:[{Slot:19b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot19 {Inventory:[{Slot:19b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot19 {Inventory:[{Slot:19b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot19 {Inventory:[{Slot:19b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot19 {Inventory:[{Slot:19b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot19 {Inventory:[{Slot:19b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot19 {Inventory:[{Slot:19b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot19 {Inventory:[{Slot:19b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot19 {Inventory:[{Slot:19b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot19 {Inventory:[{Slot:19b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot19 {Inventory:[{Slot:19b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot19 {Inventory:[{Slot:19b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot19 {Inventory:[{Slot:19b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot19 {Inventory:[{Slot:19b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot19 {Inventory:[{Slot:19b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot19 {Inventory:[{Slot:19b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot19 {Inventory:[{Slot:19b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot19 {Inventory:[{Slot:19b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot19 {Inventory:[{Slot:19b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot19 {Inventory:[{Slot:19b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot19 {Inventory:[{Slot:19b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot19 {Inventory:[{Slot:19b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot19 {Inventory:[{Slot:19b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot19 {Inventory:[{Slot:19b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot19 {Inventory:[{Slot:19b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot19 {Inventory:[{Slot:19b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot19 {Inventory:[{Slot:19b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot19 {Inventory:[{Slot:19b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot19 {Inventory:[{Slot:19b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot19 {Inventory:[{Slot:19b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot19 {Inventory:[{Slot:19b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot19 {Inventory:[{Slot:19b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot19 {Inventory:[{Slot:19b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot19 {Inventory:[{Slot:19b,id:"minecraft:structure_block",Damage:0s}]}
