scoreboard players tag @s add AirInSlot0 {Inventory:[{Slot:0b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot0 {Inventory:[{Slot:0b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot0 {Inventory:[{Slot:0b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot0 {Inventory:[{Slot:0b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot0 {Inventory:[{Slot:0b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot0 {Inventory:[{Slot:0b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot0 {Inventory:[{Slot:0b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot0 {Inventory:[{Slot:0b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot0 {Inventory:[{Slot:0b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot0 {Inventory:[{Slot:0b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot0 {Inventory:[{Slot:0b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot0 {Inventory:[{Slot:0b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot0 {Inventory:[{Slot:0b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot0 {Inventory:[{Slot:0b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot0 {Inventory:[{Slot:0b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot0 {Inventory:[{Slot:0b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot0 {Inventory:[{Slot:0b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot0 {Inventory:[{Slot:0b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot0 {Inventory:[{Slot:0b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot0 {Inventory:[{Slot:0b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot0 {Inventory:[{Slot:0b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot0 {Inventory:[{Slot:0b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot0 {Inventory:[{Slot:0b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot0 {Inventory:[{Slot:0b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot0 {Inventory:[{Slot:0b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot0 {Inventory:[{Slot:0b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot0 {Inventory:[{Slot:0b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot0 {Inventory:[{Slot:0b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot0 {Inventory:[{Slot:0b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot0 {Inventory:[{Slot:0b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot0 {Inventory:[{Slot:0b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot0 {Inventory:[{Slot:0b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot0 {Inventory:[{Slot:0b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot0 {Inventory:[{Slot:0b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot0 {Inventory:[{Slot:0b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot0 {Inventory:[{Slot:0b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot0 {Inventory:[{Slot:0b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot0 {Inventory:[{Slot:0b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot0 {Inventory:[{Slot:0b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot0 {Inventory:[{Slot:0b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot0 {Inventory:[{Slot:0b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot0 {Inventory:[{Slot:0b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot0 {Inventory:[{Slot:0b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot0 {Inventory:[{Slot:0b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot0 {Inventory:[{Slot:0b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot0 {Inventory:[{Slot:0b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot0 {Inventory:[{Slot:0b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot0 {Inventory:[{Slot:0b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot0 {Inventory:[{Slot:0b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot0 {Inventory:[{Slot:0b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot0 {Inventory:[{Slot:0b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot0 {Inventory:[{Slot:0b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot0 {Inventory:[{Slot:0b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot0 {Inventory:[{Slot:0b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot0 {Inventory:[{Slot:0b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot0 {Inventory:[{Slot:0b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot0 {Inventory:[{Slot:0b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot0 {Inventory:[{Slot:0b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot0 {Inventory:[{Slot:0b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot0 {Inventory:[{Slot:0b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot0 {Inventory:[{Slot:0b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot0 {Inventory:[{Slot:0b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot0 {Inventory:[{Slot:0b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot0 {Inventory:[{Slot:0b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot0 {Inventory:[{Slot:0b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot0 {Inventory:[{Slot:0b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot0 {Inventory:[{Slot:0b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot0 {Inventory:[{Slot:0b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot0 {Inventory:[{Slot:0b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot0 {Inventory:[{Slot:0b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot0 {Inventory:[{Slot:0b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot0 {Inventory:[{Slot:0b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot0 {Inventory:[{Slot:0b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot0 {Inventory:[{Slot:0b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot0 {Inventory:[{Slot:0b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot0 {Inventory:[{Slot:0b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot0 {Inventory:[{Slot:0b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot0 {Inventory:[{Slot:0b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot0 {Inventory:[{Slot:0b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot0 {Inventory:[{Slot:0b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot0 {Inventory:[{Slot:0b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot0 {Inventory:[{Slot:0b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot0 {Inventory:[{Slot:0b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot0 {Inventory:[{Slot:0b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot0 {Inventory:[{Slot:0b,id:"minecraft:structure_block",Damage:0s}]}
