scoreboard players tag @s add AirInSlot23 {Inventory:[{Slot:23b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot23 {Inventory:[{Slot:23b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot23 {Inventory:[{Slot:23b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot23 {Inventory:[{Slot:23b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot23 {Inventory:[{Slot:23b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot23 {Inventory:[{Slot:23b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot23 {Inventory:[{Slot:23b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot23 {Inventory:[{Slot:23b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot23 {Inventory:[{Slot:23b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot23 {Inventory:[{Slot:23b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakLogFacingYInSlot23 {Inventory:[{Slot:23b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceLogFacingYInSlot23 {Inventory:[{Slot:23b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchLogFacingYInSlot23 {Inventory:[{Slot:23b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleLogFacingYInSlot23 {Inventory:[{Slot:23b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot23 {Inventory:[{Slot:23b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot23 {Inventory:[{Slot:23b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot23 {Inventory:[{Slot:23b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot23 {Inventory:[{Slot:23b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot23 {Inventory:[{Slot:23b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot23 {Inventory:[{Slot:23b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot23 {Inventory:[{Slot:23b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot23 {Inventory:[{Slot:23b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot23 {Inventory:[{Slot:23b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot23 {Inventory:[{Slot:23b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot23 {Inventory:[{Slot:23b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot23 {Inventory:[{Slot:23b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot23 {Inventory:[{Slot:23b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot23 {Inventory:[{Slot:23b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot23 {Inventory:[{Slot:23b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot23 {Inventory:[{Slot:23b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot23 {Inventory:[{Slot:23b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot23 {Inventory:[{Slot:23b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot23 {Inventory:[{Slot:23b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot23 {Inventory:[{Slot:23b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot23 {Inventory:[{Slot:23b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot23 {Inventory:[{Slot:23b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot23 {Inventory:[{Slot:23b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot23 {Inventory:[{Slot:23b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot23 {Inventory:[{Slot:23b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot23 {Inventory:[{Slot:23b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot23 {Inventory:[{Slot:23b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot23 {Inventory:[{Slot:23b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot23 {Inventory:[{Slot:23b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot23 {Inventory:[{Slot:23b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot23 {Inventory:[{Slot:23b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot23 {Inventory:[{Slot:23b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot23 {Inventory:[{Slot:23b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot23 {Inventory:[{Slot:23b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot23 {Inventory:[{Slot:23b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot23 {Inventory:[{Slot:23b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot23 {Inventory:[{Slot:23b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot23 {Inventory:[{Slot:23b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot23 {Inventory:[{Slot:23b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot23 {Inventory:[{Slot:23b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot23 {Inventory:[{Slot:23b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot23 {Inventory:[{Slot:23b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot23 {Inventory:[{Slot:23b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot23 {Inventory:[{Slot:23b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot23 {Inventory:[{Slot:23b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot23 {Inventory:[{Slot:23b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot23 {Inventory:[{Slot:23b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot23 {Inventory:[{Slot:23b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot23 {Inventory:[{Slot:23b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot23 {Inventory:[{Slot:23b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodFacingYInSlot23 {Inventory:[{Slot:23b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodFacingYInSlot23 {Inventory:[{Slot:23b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot23 {Inventory:[{Slot:23b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot23 {Inventory:[{Slot:23b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot23 {Inventory:[{Slot:23b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot23 {Inventory:[{Slot:23b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot23 {Inventory:[{Slot:23b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot23 {Inventory:[{Slot:23b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot23 {Inventory:[{Slot:23b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot23 {Inventory:[{Slot:23b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot23 {Inventory:[{Slot:23b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot23 {Inventory:[{Slot:23b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot23 {Inventory:[{Slot:23b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot23 {Inventory:[{Slot:23b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot23 {Inventory:[{Slot:23b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot23 {Inventory:[{Slot:23b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot23 {Inventory:[{Slot:23b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot23 {Inventory:[{Slot:23b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot23 {Inventory:[{Slot:23b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot23 {Inventory:[{Slot:23b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot23 {Inventory:[{Slot:23b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot23 {Inventory:[{Slot:23b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot23 {Inventory:[{Slot:23b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot23 {Inventory:[{Slot:23b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot23 {Inventory:[{Slot:23b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot23 {Inventory:[{Slot:23b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot23 {Inventory:[{Slot:23b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot23] ~ ~ ~ execute @s[tag=!StoneInSlot23] ~ ~ ~ execute @s[tag=!GraniteInSlot23] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot23] ~ ~ ~ execute @s[tag=!DioriteInSlot23] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot23] ~ ~ ~ execute @s[tag=!AndesiteInSlot23] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot23] ~ ~ ~ execute @s[tag=!GrassBlockInSlot23] ~ ~ ~ execute @s[tag=!DirtInSlot23] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot23] ~ ~ ~ execute @s[tag=!PodzolInSlot23] ~ ~ ~ execute @s[tag=!CobblestoneInSlot23] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot23] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot23] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot23] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot23] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot23] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot23] ~ ~ ~ execute @s[tag=!OakSaplingInSlot23] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot23] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot23] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot23] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot23] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot23] ~ ~ ~ execute @s[tag=!BedrockInSlot23] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot23] ~ ~ ~ execute @s[tag=!StillWaterInSlot23] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot23] ~ ~ ~ execute @s[tag=!StillLavaInSlot23] ~ ~ ~ execute @s[tag=!SandInSlot23] ~ ~ ~ execute @s[tag=!RedSandInSlot23] ~ ~ ~ execute @s[tag=!GravelInSlot23] ~ ~ ~ execute @s[tag=!GoldOreInSlot23] ~ ~ ~ execute @s[tag=!IronOreInSlot23] ~ ~ ~ execute @s[tag=!CoalOreInSlot23] ~ ~ ~ execute @s[tag=!OakLogFacingYInSlot23] ~ ~ ~ execute @s[tag=!SpruceLogFacingYInSlot23] ~ ~ ~ execute @s[tag=!BirchLogFacingYInSlot23] ~ ~ ~ execute @s[tag=!JungleLogFacingYInSlot23] ~ ~ ~ execute @s[tag=!OakLeavesInSlot23] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot23] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot23] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot23] ~ ~ ~ execute @s[tag=!SpongeInSlot23] ~ ~ ~ execute @s[tag=!WetSpongeInSlot23] ~ ~ ~ execute @s[tag=!GlassInSlot23] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot23] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot23] ~ ~ ~ execute @s[tag=!DispenserInSlot23] ~ ~ ~ execute @s[tag=!SandstoneInSlot23] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot23] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot23] ~ ~ ~ execute @s[tag=!NoteBlockInSlot23] ~ ~ ~ execute @s[tag=!BedInSlot23] ~ ~ ~ execute @s[tag=!PoweredRailInSlot23] ~ ~ ~ execute @s[tag=!DetectorRailInSlot23] ~ ~ ~ execute @s[tag=!StickyPistonInSlot23] ~ ~ ~ execute @s[tag=!CobwebInSlot23] ~ ~ ~ execute @s[tag=!DeadShrubInSlot23] ~ ~ ~ execute @s[tag=!GrassInSlot23] ~ ~ ~ execute @s[tag=!FernInSlot23] ~ ~ ~ execute @s[tag=!DeadBushInSlot23] ~ ~ ~ execute @s[tag=!PistonInSlot23] ~ ~ ~ execute @s[tag=!PistonHeadInSlot23] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot23] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot23] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot23] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot23] ~ ~ ~ execute @s[tag=!YellowWoolInSlot23] ~ ~ ~ execute @s[tag=!LimeWoolInSlot23] ~ ~ ~ execute @s[tag=!PinkWoolInSlot23] ~ ~ ~ execute @s[tag=!GrayWoolInSlot23] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot23] ~ ~ ~ execute @s[tag=!CyanWoolInSlot23] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot23] ~ ~ ~ execute @s[tag=!BlueWoolInSlot23] ~ ~ ~ execute @s[tag=!BrownWoolInSlot23] ~ ~ ~ execute @s[tag=!GreenWoolInSlot23] ~ ~ ~ execute @s[tag=!RedWoolInSlot23] ~ ~ ~ execute @s[tag=!BlackWoolInSlot23] ~ ~ ~ execute @s[tag=!DandelionInSlot23] ~ ~ ~ execute @s[tag=!PoppyInSlot23] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot23] ~ ~ ~ execute @s[tag=!AlliumInSlot23] ~ ~ ~ execute @s[tag=!AzureBluetInSlot23] ~ ~ ~ execute @s[tag=!RedTulipInSlot23] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot23] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot23] ~ ~ ~ execute @s[tag=!PinkTulipInSlot23] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot23] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot23] ~ ~ ~ execute @s[tag=!RedMushroomInSlot23] ~ ~ ~ execute @s[tag=!GoldBlockInSlot23] ~ ~ ~ execute @s[tag=!IronBlockInSlot23] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot23] ~ ~ ~ execute @s[tag=!StoneSlabInSlot23] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot23] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot23] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot23] ~ ~ ~ execute @s[tag=!BrickSlabInSlot23] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot23] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot23] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot23] ~ ~ ~ execute @s[tag=!BricksInSlot23] ~ ~ ~ execute @s[tag=!TNTInSlot23] ~ ~ ~ execute @s[tag=!BookshelfInSlot23] ~ ~ ~ execute @s[tag=!MossStoneInSlot23] ~ ~ ~ execute @s[tag=!ObsidianInSlot23] ~ ~ ~ execute @s[tag=!TorchInSlot23] ~ ~ ~ execute @s[tag=!FireInSlot23] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot23] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot23] ~ ~ ~ execute @s[tag=!ChestInSlot23] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot23] ~ ~ ~ execute @s[tag=!DiamondOreInSlot23] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot23] ~ ~ ~ execute @s[tag=!CraftingTableInSlot23] ~ ~ ~ execute @s[tag=!WheatCropsInSlot23] ~ ~ ~ execute @s[tag=!FarmlandInSlot23] ~ ~ ~ execute @s[tag=!FurnaceInSlot23] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot23] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot23] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!LadderInSlot23] ~ ~ ~ execute @s[tag=!RailInSlot23] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot23] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot23] ~ ~ ~ execute @s[tag=!LeverInSlot23] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot23] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot23] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot23] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot23] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot23] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot23] ~ ~ ~ execute @s[tag=!StoneButtonInSlot23] ~ ~ ~ execute @s[tag=!SnowInSlot23] ~ ~ ~ execute @s[tag=!IceInSlot23] ~ ~ ~ execute @s[tag=!SnowBlockInSlot23] ~ ~ ~ execute @s[tag=!CactusInSlot23] ~ ~ ~ execute @s[tag=!SugarCanesInSlot23] ~ ~ ~ execute @s[tag=!JukeboxInSlot23] ~ ~ ~ execute @s[tag=!OakFenceInSlot23] ~ ~ ~ execute @s[tag=!PumpkinInSlot23] ~ ~ ~ execute @s[tag=!NetherrackInSlot23] ~ ~ ~ execute @s[tag=!SoulSandInSlot23] ~ ~ ~ execute @s[tag=!GlowstoneInSlot23] ~ ~ ~ execute @s[tag=!NetherPortalInSlot23] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot23] ~ ~ ~ execute @s[tag=!CakeBlockInSlot23] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot23] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot23] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot23] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot23] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot23] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot23] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot23] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot23] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot23] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot23] ~ ~ ~ execute @s[tag=!StoneBricksInSlot23] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot23] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot23] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot23] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot23] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot23] ~ ~ ~ execute @s[tag=!IronBarsInSlot23] ~ ~ ~ execute @s[tag=!GlassPaneInSlot23] ~ ~ ~ execute @s[tag=!MelonBlockInSlot23] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot23] ~ ~ ~ execute @s[tag=!MelonStemInSlot23] ~ ~ ~ execute @s[tag=!VinesInSlot23] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot23] ~ ~ ~ execute @s[tag=!BrickStairsInSlot23] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot23] ~ ~ ~ execute @s[tag=!MyceliumInSlot23] ~ ~ ~ execute @s[tag=!LilyPadInSlot23] ~ ~ ~ execute @s[tag=!NetherBrickInSlot23] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot23] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot23] ~ ~ ~ execute @s[tag=!NetherWartInSlot23] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot23] ~ ~ ~ execute @s[tag=!BrewingStandInSlot23] ~ ~ ~ execute @s[tag=!CauldronInSlot23] ~ ~ ~ execute @s[tag=!EndPortalInSlot23] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot23] ~ ~ ~ execute @s[tag=!EndStoneInSlot23] ~ ~ ~ execute @s[tag=!DragonEggInSlot23] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot23] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot23] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot23] ~ ~ ~ execute @s[tag=!CocoaInSlot23] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot23] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot23] ~ ~ ~ execute @s[tag=!EnderChestInSlot23] ~ ~ ~ execute @s[tag=!TripwireHookInSlot23] ~ ~ ~ execute @s[tag=!TripwireInSlot23] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot23] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot23] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot23] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot23] ~ ~ ~ execute @s[tag=!CommandBlockInSlot23] ~ ~ ~ execute @s[tag=!BeaconInSlot23] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot23] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot23] ~ ~ ~ execute @s[tag=!FlowerPotInSlot23] ~ ~ ~ execute @s[tag=!CarrotsInSlot23] ~ ~ ~ execute @s[tag=!PotatoesInSlot23] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot23] ~ ~ ~ execute @s[tag=!MobHeadInSlot23] ~ ~ ~ execute @s[tag=!AnvilInSlot23] ~ ~ ~ execute @s[tag=!TrappedChestInSlot23] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot23] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot23] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot23] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot23] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot23] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot23] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot23] ~ ~ ~ execute @s[tag=!HopperInSlot23] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot23] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot23] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot23] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot23] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot23] ~ ~ ~ execute @s[tag=!DropperInSlot23] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot23] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot23] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot23] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot23] ~ ~ ~ execute @s[tag=!AcaciaWoodFacingYInSlot23] ~ ~ ~ execute @s[tag=!DarkOakWoodFacingYInSlot23] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot23] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot23] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot23] ~ ~ ~ execute @s[tag=!BarrierInSlot23] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot23] ~ ~ ~ execute @s[tag=!PrismarineInSlot23] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot23] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot23] ~ ~ ~ execute @s[tag=!SeaLanternInSlot23] ~ ~ ~ execute @s[tag=!HayBaleInSlot23] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot23] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot23] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot23] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot23] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot23] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot23] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot23] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot23] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot23] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot23] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot23] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot23] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot23] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot23] ~ ~ ~ execute @s[tag=!RedCarpetInSlot23] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot23] ~ ~ ~ execute @s[tag=!HardenedClayInSlot23] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot23] ~ ~ ~ execute @s[tag=!PackedIceInSlot23] ~ ~ ~ execute @s[tag=!SunflowerInSlot23] ~ ~ ~ execute @s[tag=!LilacInSlot23] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot23] ~ ~ ~ execute @s[tag=!LargeFernInSlot23] ~ ~ ~ execute @s[tag=!RoseBushInSlot23] ~ ~ ~ execute @s[tag=!PeonyInSlot23] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot23] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot23] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot23] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot23] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot23] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot23] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot23] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot23] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot23] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot23] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot23] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot23] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot23] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot23] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot23] ~ ~ ~ execute @s[tag=!BirchFenceInSlot23] ~ ~ ~ execute @s[tag=!JungleFenceInSlot23] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot23] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot23] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot23] ~ ~ ~ execute @s[tag=!EndRodInSlot23] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot23] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot23] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot23] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot23] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot23] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot23] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot23] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot23] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot23] ~ ~ ~ execute @s[tag=!GrassPathInSlot23] ~ ~ ~ execute @s[tag=!EndGatewayInSlot23] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot23] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot23] ~ ~ ~ execute @s[tag=!FrostedIceInSlot23] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot23] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot23] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot23] ~ ~ ~ execute @s[tag=!BoneBlockInSlot23] ~ ~ ~ execute @s[tag=!StructureVoidInSlot23] ~ ~ ~ execute @s[tag=!ObserverInSlot23] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot23] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot23] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot23] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot23] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot23] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot23] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot23] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot23] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot23] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot23] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot23] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot23] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot23] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot23] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot23] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot23] ~ ~ ~ execute @s[tag=!RedConcreteInSlot23] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot23] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot23] ~ ~ ~ execute @s[tag=!StructureBlockInSlot23] ~ ~ ~ scoreboard players tag @s add AirInSlot23 