scoreboard players tag @s add AirInSlot5 {Inventory:[{Slot:5b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot5 {Inventory:[{Slot:5b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot5 {Inventory:[{Slot:5b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot5 {Inventory:[{Slot:5b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot5 {Inventory:[{Slot:5b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot5 {Inventory:[{Slot:5b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot5 {Inventory:[{Slot:5b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot5 {Inventory:[{Slot:5b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot5 {Inventory:[{Slot:5b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot5 {Inventory:[{Slot:5b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakLogFacingYInSlot5 {Inventory:[{Slot:5b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceLogFacingYInSlot5 {Inventory:[{Slot:5b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchLogFacingYInSlot5 {Inventory:[{Slot:5b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleLogFacingYInSlot5 {Inventory:[{Slot:5b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot5 {Inventory:[{Slot:5b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot5 {Inventory:[{Slot:5b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot5 {Inventory:[{Slot:5b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot5 {Inventory:[{Slot:5b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot5 {Inventory:[{Slot:5b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot5 {Inventory:[{Slot:5b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot5 {Inventory:[{Slot:5b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot5 {Inventory:[{Slot:5b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot5 {Inventory:[{Slot:5b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot5 {Inventory:[{Slot:5b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot5 {Inventory:[{Slot:5b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot5 {Inventory:[{Slot:5b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot5 {Inventory:[{Slot:5b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot5 {Inventory:[{Slot:5b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot5 {Inventory:[{Slot:5b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot5 {Inventory:[{Slot:5b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot5 {Inventory:[{Slot:5b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot5 {Inventory:[{Slot:5b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot5 {Inventory:[{Slot:5b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot5 {Inventory:[{Slot:5b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot5 {Inventory:[{Slot:5b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot5 {Inventory:[{Slot:5b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot5 {Inventory:[{Slot:5b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot5 {Inventory:[{Slot:5b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot5 {Inventory:[{Slot:5b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot5 {Inventory:[{Slot:5b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot5 {Inventory:[{Slot:5b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot5 {Inventory:[{Slot:5b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot5 {Inventory:[{Slot:5b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot5 {Inventory:[{Slot:5b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot5 {Inventory:[{Slot:5b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot5 {Inventory:[{Slot:5b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot5 {Inventory:[{Slot:5b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot5 {Inventory:[{Slot:5b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot5 {Inventory:[{Slot:5b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot5 {Inventory:[{Slot:5b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot5 {Inventory:[{Slot:5b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot5 {Inventory:[{Slot:5b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot5 {Inventory:[{Slot:5b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot5 {Inventory:[{Slot:5b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot5 {Inventory:[{Slot:5b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot5 {Inventory:[{Slot:5b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot5 {Inventory:[{Slot:5b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot5 {Inventory:[{Slot:5b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot5 {Inventory:[{Slot:5b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot5 {Inventory:[{Slot:5b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot5 {Inventory:[{Slot:5b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot5 {Inventory:[{Slot:5b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot5 {Inventory:[{Slot:5b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot5 {Inventory:[{Slot:5b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodFacingYInSlot5 {Inventory:[{Slot:5b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodFacingYInSlot5 {Inventory:[{Slot:5b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot5 {Inventory:[{Slot:5b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot5 {Inventory:[{Slot:5b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot5 {Inventory:[{Slot:5b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot5 {Inventory:[{Slot:5b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot5 {Inventory:[{Slot:5b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot5 {Inventory:[{Slot:5b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot5 {Inventory:[{Slot:5b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot5 {Inventory:[{Slot:5b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot5 {Inventory:[{Slot:5b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot5 {Inventory:[{Slot:5b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot5 {Inventory:[{Slot:5b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot5 {Inventory:[{Slot:5b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot5 {Inventory:[{Slot:5b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot5 {Inventory:[{Slot:5b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot5 {Inventory:[{Slot:5b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot5 {Inventory:[{Slot:5b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot5 {Inventory:[{Slot:5b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot5 {Inventory:[{Slot:5b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot5 {Inventory:[{Slot:5b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot5 {Inventory:[{Slot:5b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot5 {Inventory:[{Slot:5b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot5 {Inventory:[{Slot:5b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot5 {Inventory:[{Slot:5b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot5 {Inventory:[{Slot:5b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot5 {Inventory:[{Slot:5b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot5] ~ ~ ~ execute @s[tag=!StoneInSlot5] ~ ~ ~ execute @s[tag=!GraniteInSlot5] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot5] ~ ~ ~ execute @s[tag=!DioriteInSlot5] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot5] ~ ~ ~ execute @s[tag=!AndesiteInSlot5] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot5] ~ ~ ~ execute @s[tag=!GrassBlockInSlot5] ~ ~ ~ execute @s[tag=!DirtInSlot5] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot5] ~ ~ ~ execute @s[tag=!PodzolInSlot5] ~ ~ ~ execute @s[tag=!CobblestoneInSlot5] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot5] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot5] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot5] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot5] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot5] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot5] ~ ~ ~ execute @s[tag=!OakSaplingInSlot5] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot5] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot5] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot5] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot5] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot5] ~ ~ ~ execute @s[tag=!BedrockInSlot5] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot5] ~ ~ ~ execute @s[tag=!StillWaterInSlot5] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot5] ~ ~ ~ execute @s[tag=!StillLavaInSlot5] ~ ~ ~ execute @s[tag=!SandInSlot5] ~ ~ ~ execute @s[tag=!RedSandInSlot5] ~ ~ ~ execute @s[tag=!GravelInSlot5] ~ ~ ~ execute @s[tag=!GoldOreInSlot5] ~ ~ ~ execute @s[tag=!IronOreInSlot5] ~ ~ ~ execute @s[tag=!CoalOreInSlot5] ~ ~ ~ execute @s[tag=!OakLogFacingYInSlot5] ~ ~ ~ execute @s[tag=!SpruceLogFacingYInSlot5] ~ ~ ~ execute @s[tag=!BirchLogFacingYInSlot5] ~ ~ ~ execute @s[tag=!JungleLogFacingYInSlot5] ~ ~ ~ execute @s[tag=!OakLeavesInSlot5] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot5] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot5] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot5] ~ ~ ~ execute @s[tag=!SpongeInSlot5] ~ ~ ~ execute @s[tag=!WetSpongeInSlot5] ~ ~ ~ execute @s[tag=!GlassInSlot5] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot5] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot5] ~ ~ ~ execute @s[tag=!DispenserInSlot5] ~ ~ ~ execute @s[tag=!SandstoneInSlot5] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot5] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot5] ~ ~ ~ execute @s[tag=!NoteBlockInSlot5] ~ ~ ~ execute @s[tag=!BedInSlot5] ~ ~ ~ execute @s[tag=!PoweredRailInSlot5] ~ ~ ~ execute @s[tag=!DetectorRailInSlot5] ~ ~ ~ execute @s[tag=!StickyPistonInSlot5] ~ ~ ~ execute @s[tag=!CobwebInSlot5] ~ ~ ~ execute @s[tag=!DeadShrubInSlot5] ~ ~ ~ execute @s[tag=!GrassInSlot5] ~ ~ ~ execute @s[tag=!FernInSlot5] ~ ~ ~ execute @s[tag=!DeadBushInSlot5] ~ ~ ~ execute @s[tag=!PistonInSlot5] ~ ~ ~ execute @s[tag=!PistonHeadInSlot5] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot5] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot5] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot5] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot5] ~ ~ ~ execute @s[tag=!YellowWoolInSlot5] ~ ~ ~ execute @s[tag=!LimeWoolInSlot5] ~ ~ ~ execute @s[tag=!PinkWoolInSlot5] ~ ~ ~ execute @s[tag=!GrayWoolInSlot5] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot5] ~ ~ ~ execute @s[tag=!CyanWoolInSlot5] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot5] ~ ~ ~ execute @s[tag=!BlueWoolInSlot5] ~ ~ ~ execute @s[tag=!BrownWoolInSlot5] ~ ~ ~ execute @s[tag=!GreenWoolInSlot5] ~ ~ ~ execute @s[tag=!RedWoolInSlot5] ~ ~ ~ execute @s[tag=!BlackWoolInSlot5] ~ ~ ~ execute @s[tag=!DandelionInSlot5] ~ ~ ~ execute @s[tag=!PoppyInSlot5] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot5] ~ ~ ~ execute @s[tag=!AlliumInSlot5] ~ ~ ~ execute @s[tag=!AzureBluetInSlot5] ~ ~ ~ execute @s[tag=!RedTulipInSlot5] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot5] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot5] ~ ~ ~ execute @s[tag=!PinkTulipInSlot5] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot5] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot5] ~ ~ ~ execute @s[tag=!RedMushroomInSlot5] ~ ~ ~ execute @s[tag=!GoldBlockInSlot5] ~ ~ ~ execute @s[tag=!IronBlockInSlot5] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot5] ~ ~ ~ execute @s[tag=!StoneSlabInSlot5] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot5] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot5] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot5] ~ ~ ~ execute @s[tag=!BrickSlabInSlot5] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot5] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot5] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot5] ~ ~ ~ execute @s[tag=!BricksInSlot5] ~ ~ ~ execute @s[tag=!TNTInSlot5] ~ ~ ~ execute @s[tag=!BookshelfInSlot5] ~ ~ ~ execute @s[tag=!MossStoneInSlot5] ~ ~ ~ execute @s[tag=!ObsidianInSlot5] ~ ~ ~ execute @s[tag=!TorchInSlot5] ~ ~ ~ execute @s[tag=!FireInSlot5] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot5] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot5] ~ ~ ~ execute @s[tag=!ChestInSlot5] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot5] ~ ~ ~ execute @s[tag=!DiamondOreInSlot5] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot5] ~ ~ ~ execute @s[tag=!CraftingTableInSlot5] ~ ~ ~ execute @s[tag=!WheatCropsInSlot5] ~ ~ ~ execute @s[tag=!FarmlandInSlot5] ~ ~ ~ execute @s[tag=!FurnaceInSlot5] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot5] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot5] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!LadderInSlot5] ~ ~ ~ execute @s[tag=!RailInSlot5] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot5] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot5] ~ ~ ~ execute @s[tag=!LeverInSlot5] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot5] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot5] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot5] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot5] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot5] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot5] ~ ~ ~ execute @s[tag=!StoneButtonInSlot5] ~ ~ ~ execute @s[tag=!SnowInSlot5] ~ ~ ~ execute @s[tag=!IceInSlot5] ~ ~ ~ execute @s[tag=!SnowBlockInSlot5] ~ ~ ~ execute @s[tag=!CactusInSlot5] ~ ~ ~ execute @s[tag=!SugarCanesInSlot5] ~ ~ ~ execute @s[tag=!JukeboxInSlot5] ~ ~ ~ execute @s[tag=!OakFenceInSlot5] ~ ~ ~ execute @s[tag=!PumpkinInSlot5] ~ ~ ~ execute @s[tag=!NetherrackInSlot5] ~ ~ ~ execute @s[tag=!SoulSandInSlot5] ~ ~ ~ execute @s[tag=!GlowstoneInSlot5] ~ ~ ~ execute @s[tag=!NetherPortalInSlot5] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot5] ~ ~ ~ execute @s[tag=!CakeBlockInSlot5] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot5] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot5] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot5] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot5] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot5] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot5] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot5] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot5] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot5] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot5] ~ ~ ~ execute @s[tag=!StoneBricksInSlot5] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot5] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot5] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot5] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot5] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot5] ~ ~ ~ execute @s[tag=!IronBarsInSlot5] ~ ~ ~ execute @s[tag=!GlassPaneInSlot5] ~ ~ ~ execute @s[tag=!MelonBlockInSlot5] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot5] ~ ~ ~ execute @s[tag=!MelonStemInSlot5] ~ ~ ~ execute @s[tag=!VinesInSlot5] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot5] ~ ~ ~ execute @s[tag=!BrickStairsInSlot5] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot5] ~ ~ ~ execute @s[tag=!MyceliumInSlot5] ~ ~ ~ execute @s[tag=!LilyPadInSlot5] ~ ~ ~ execute @s[tag=!NetherBrickInSlot5] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot5] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot5] ~ ~ ~ execute @s[tag=!NetherWartInSlot5] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot5] ~ ~ ~ execute @s[tag=!BrewingStandInSlot5] ~ ~ ~ execute @s[tag=!CauldronInSlot5] ~ ~ ~ execute @s[tag=!EndPortalInSlot5] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot5] ~ ~ ~ execute @s[tag=!EndStoneInSlot5] ~ ~ ~ execute @s[tag=!DragonEggInSlot5] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot5] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot5] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot5] ~ ~ ~ execute @s[tag=!CocoaInSlot5] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot5] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot5] ~ ~ ~ execute @s[tag=!EnderChestInSlot5] ~ ~ ~ execute @s[tag=!TripwireHookInSlot5] ~ ~ ~ execute @s[tag=!TripwireInSlot5] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot5] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot5] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot5] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot5] ~ ~ ~ execute @s[tag=!CommandBlockInSlot5] ~ ~ ~ execute @s[tag=!BeaconInSlot5] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot5] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot5] ~ ~ ~ execute @s[tag=!FlowerPotInSlot5] ~ ~ ~ execute @s[tag=!CarrotsInSlot5] ~ ~ ~ execute @s[tag=!PotatoesInSlot5] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot5] ~ ~ ~ execute @s[tag=!MobHeadInSlot5] ~ ~ ~ execute @s[tag=!AnvilInSlot5] ~ ~ ~ execute @s[tag=!TrappedChestInSlot5] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot5] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot5] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot5] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot5] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot5] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot5] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot5] ~ ~ ~ execute @s[tag=!HopperInSlot5] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot5] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot5] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot5] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot5] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot5] ~ ~ ~ execute @s[tag=!DropperInSlot5] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot5] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot5] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot5] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot5] ~ ~ ~ execute @s[tag=!AcaciaWoodFacingYInSlot5] ~ ~ ~ execute @s[tag=!DarkOakWoodFacingYInSlot5] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot5] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot5] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot5] ~ ~ ~ execute @s[tag=!BarrierInSlot5] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot5] ~ ~ ~ execute @s[tag=!PrismarineInSlot5] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot5] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot5] ~ ~ ~ execute @s[tag=!SeaLanternInSlot5] ~ ~ ~ execute @s[tag=!HayBaleInSlot5] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot5] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot5] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot5] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot5] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot5] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot5] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot5] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot5] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot5] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot5] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot5] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot5] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot5] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot5] ~ ~ ~ execute @s[tag=!RedCarpetInSlot5] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot5] ~ ~ ~ execute @s[tag=!HardenedClayInSlot5] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot5] ~ ~ ~ execute @s[tag=!PackedIceInSlot5] ~ ~ ~ execute @s[tag=!SunflowerInSlot5] ~ ~ ~ execute @s[tag=!LilacInSlot5] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot5] ~ ~ ~ execute @s[tag=!LargeFernInSlot5] ~ ~ ~ execute @s[tag=!RoseBushInSlot5] ~ ~ ~ execute @s[tag=!PeonyInSlot5] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot5] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot5] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot5] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot5] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot5] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot5] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot5] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot5] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot5] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot5] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot5] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot5] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot5] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot5] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot5] ~ ~ ~ execute @s[tag=!BirchFenceInSlot5] ~ ~ ~ execute @s[tag=!JungleFenceInSlot5] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot5] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot5] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot5] ~ ~ ~ execute @s[tag=!EndRodInSlot5] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot5] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot5] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot5] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot5] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot5] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot5] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot5] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot5] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot5] ~ ~ ~ execute @s[tag=!GrassPathInSlot5] ~ ~ ~ execute @s[tag=!EndGatewayInSlot5] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot5] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot5] ~ ~ ~ execute @s[tag=!FrostedIceInSlot5] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot5] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot5] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot5] ~ ~ ~ execute @s[tag=!BoneBlockInSlot5] ~ ~ ~ execute @s[tag=!StructureVoidInSlot5] ~ ~ ~ execute @s[tag=!ObserverInSlot5] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot5] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot5] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot5] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot5] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot5] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot5] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot5] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot5] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot5] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot5] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot5] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot5] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot5] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot5] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot5] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot5] ~ ~ ~ execute @s[tag=!RedConcreteInSlot5] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot5] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot5] ~ ~ ~ execute @s[tag=!StructureBlockInSlot5] ~ ~ ~ scoreboard players tag @s add AirInSlot5 