scoreboard players tag @s add AirInSlot10 {Inventory:[{Slot:10b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot10 {Inventory:[{Slot:10b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot10 {Inventory:[{Slot:10b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot10 {Inventory:[{Slot:10b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot10 {Inventory:[{Slot:10b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot10 {Inventory:[{Slot:10b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot10 {Inventory:[{Slot:10b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot10 {Inventory:[{Slot:10b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot10 {Inventory:[{Slot:10b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot10 {Inventory:[{Slot:10b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakLogFacingYInSlot10 {Inventory:[{Slot:10b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceLogFacingYInSlot10 {Inventory:[{Slot:10b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchLogFacingYInSlot10 {Inventory:[{Slot:10b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleLogFacingYInSlot10 {Inventory:[{Slot:10b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot10 {Inventory:[{Slot:10b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot10 {Inventory:[{Slot:10b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot10 {Inventory:[{Slot:10b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot10 {Inventory:[{Slot:10b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot10 {Inventory:[{Slot:10b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot10 {Inventory:[{Slot:10b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot10 {Inventory:[{Slot:10b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot10 {Inventory:[{Slot:10b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot10 {Inventory:[{Slot:10b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot10 {Inventory:[{Slot:10b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot10 {Inventory:[{Slot:10b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot10 {Inventory:[{Slot:10b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot10 {Inventory:[{Slot:10b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot10 {Inventory:[{Slot:10b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot10 {Inventory:[{Slot:10b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot10 {Inventory:[{Slot:10b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot10 {Inventory:[{Slot:10b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot10 {Inventory:[{Slot:10b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot10 {Inventory:[{Slot:10b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot10 {Inventory:[{Slot:10b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot10 {Inventory:[{Slot:10b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot10 {Inventory:[{Slot:10b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot10 {Inventory:[{Slot:10b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot10 {Inventory:[{Slot:10b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot10 {Inventory:[{Slot:10b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot10 {Inventory:[{Slot:10b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot10 {Inventory:[{Slot:10b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot10 {Inventory:[{Slot:10b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot10 {Inventory:[{Slot:10b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot10 {Inventory:[{Slot:10b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot10 {Inventory:[{Slot:10b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot10 {Inventory:[{Slot:10b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot10 {Inventory:[{Slot:10b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot10 {Inventory:[{Slot:10b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot10 {Inventory:[{Slot:10b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot10 {Inventory:[{Slot:10b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot10 {Inventory:[{Slot:10b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot10 {Inventory:[{Slot:10b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot10 {Inventory:[{Slot:10b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot10 {Inventory:[{Slot:10b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot10 {Inventory:[{Slot:10b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot10 {Inventory:[{Slot:10b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot10 {Inventory:[{Slot:10b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot10 {Inventory:[{Slot:10b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot10 {Inventory:[{Slot:10b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot10 {Inventory:[{Slot:10b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot10 {Inventory:[{Slot:10b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot10 {Inventory:[{Slot:10b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot10 {Inventory:[{Slot:10b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot10 {Inventory:[{Slot:10b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodFacingYInSlot10 {Inventory:[{Slot:10b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodFacingYInSlot10 {Inventory:[{Slot:10b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot10 {Inventory:[{Slot:10b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot10 {Inventory:[{Slot:10b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot10 {Inventory:[{Slot:10b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot10 {Inventory:[{Slot:10b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot10 {Inventory:[{Slot:10b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot10 {Inventory:[{Slot:10b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot10 {Inventory:[{Slot:10b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot10 {Inventory:[{Slot:10b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot10 {Inventory:[{Slot:10b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot10 {Inventory:[{Slot:10b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot10 {Inventory:[{Slot:10b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot10 {Inventory:[{Slot:10b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot10 {Inventory:[{Slot:10b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot10 {Inventory:[{Slot:10b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot10 {Inventory:[{Slot:10b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot10 {Inventory:[{Slot:10b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot10 {Inventory:[{Slot:10b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot10 {Inventory:[{Slot:10b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot10 {Inventory:[{Slot:10b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot10 {Inventory:[{Slot:10b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot10 {Inventory:[{Slot:10b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot10 {Inventory:[{Slot:10b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot10 {Inventory:[{Slot:10b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot10 {Inventory:[{Slot:10b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot10 {Inventory:[{Slot:10b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot10] ~ ~ ~ execute @s[tag=!StoneInSlot10] ~ ~ ~ execute @s[tag=!GraniteInSlot10] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot10] ~ ~ ~ execute @s[tag=!DioriteInSlot10] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot10] ~ ~ ~ execute @s[tag=!AndesiteInSlot10] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot10] ~ ~ ~ execute @s[tag=!GrassBlockInSlot10] ~ ~ ~ execute @s[tag=!DirtInSlot10] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot10] ~ ~ ~ execute @s[tag=!PodzolInSlot10] ~ ~ ~ execute @s[tag=!CobblestoneInSlot10] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot10] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot10] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot10] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot10] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot10] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot10] ~ ~ ~ execute @s[tag=!OakSaplingInSlot10] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot10] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot10] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot10] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot10] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot10] ~ ~ ~ execute @s[tag=!BedrockInSlot10] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot10] ~ ~ ~ execute @s[tag=!StillWaterInSlot10] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot10] ~ ~ ~ execute @s[tag=!StillLavaInSlot10] ~ ~ ~ execute @s[tag=!SandInSlot10] ~ ~ ~ execute @s[tag=!RedSandInSlot10] ~ ~ ~ execute @s[tag=!GravelInSlot10] ~ ~ ~ execute @s[tag=!GoldOreInSlot10] ~ ~ ~ execute @s[tag=!IronOreInSlot10] ~ ~ ~ execute @s[tag=!CoalOreInSlot10] ~ ~ ~ execute @s[tag=!OakLogFacingYInSlot10] ~ ~ ~ execute @s[tag=!SpruceLogFacingYInSlot10] ~ ~ ~ execute @s[tag=!BirchLogFacingYInSlot10] ~ ~ ~ execute @s[tag=!JungleLogFacingYInSlot10] ~ ~ ~ execute @s[tag=!OakLeavesInSlot10] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot10] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot10] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot10] ~ ~ ~ execute @s[tag=!SpongeInSlot10] ~ ~ ~ execute @s[tag=!WetSpongeInSlot10] ~ ~ ~ execute @s[tag=!GlassInSlot10] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot10] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot10] ~ ~ ~ execute @s[tag=!DispenserInSlot10] ~ ~ ~ execute @s[tag=!SandstoneInSlot10] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot10] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot10] ~ ~ ~ execute @s[tag=!NoteBlockInSlot10] ~ ~ ~ execute @s[tag=!BedInSlot10] ~ ~ ~ execute @s[tag=!PoweredRailInSlot10] ~ ~ ~ execute @s[tag=!DetectorRailInSlot10] ~ ~ ~ execute @s[tag=!StickyPistonInSlot10] ~ ~ ~ execute @s[tag=!CobwebInSlot10] ~ ~ ~ execute @s[tag=!DeadShrubInSlot10] ~ ~ ~ execute @s[tag=!GrassInSlot10] ~ ~ ~ execute @s[tag=!FernInSlot10] ~ ~ ~ execute @s[tag=!DeadBushInSlot10] ~ ~ ~ execute @s[tag=!PistonInSlot10] ~ ~ ~ execute @s[tag=!PistonHeadInSlot10] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot10] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot10] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot10] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot10] ~ ~ ~ execute @s[tag=!YellowWoolInSlot10] ~ ~ ~ execute @s[tag=!LimeWoolInSlot10] ~ ~ ~ execute @s[tag=!PinkWoolInSlot10] ~ ~ ~ execute @s[tag=!GrayWoolInSlot10] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot10] ~ ~ ~ execute @s[tag=!CyanWoolInSlot10] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot10] ~ ~ ~ execute @s[tag=!BlueWoolInSlot10] ~ ~ ~ execute @s[tag=!BrownWoolInSlot10] ~ ~ ~ execute @s[tag=!GreenWoolInSlot10] ~ ~ ~ execute @s[tag=!RedWoolInSlot10] ~ ~ ~ execute @s[tag=!BlackWoolInSlot10] ~ ~ ~ execute @s[tag=!DandelionInSlot10] ~ ~ ~ execute @s[tag=!PoppyInSlot10] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot10] ~ ~ ~ execute @s[tag=!AlliumInSlot10] ~ ~ ~ execute @s[tag=!AzureBluetInSlot10] ~ ~ ~ execute @s[tag=!RedTulipInSlot10] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot10] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot10] ~ ~ ~ execute @s[tag=!PinkTulipInSlot10] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot10] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot10] ~ ~ ~ execute @s[tag=!RedMushroomInSlot10] ~ ~ ~ execute @s[tag=!GoldBlockInSlot10] ~ ~ ~ execute @s[tag=!IronBlockInSlot10] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot10] ~ ~ ~ execute @s[tag=!StoneSlabInSlot10] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot10] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot10] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot10] ~ ~ ~ execute @s[tag=!BrickSlabInSlot10] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot10] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot10] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot10] ~ ~ ~ execute @s[tag=!BricksInSlot10] ~ ~ ~ execute @s[tag=!TNTInSlot10] ~ ~ ~ execute @s[tag=!BookshelfInSlot10] ~ ~ ~ execute @s[tag=!MossStoneInSlot10] ~ ~ ~ execute @s[tag=!ObsidianInSlot10] ~ ~ ~ execute @s[tag=!TorchInSlot10] ~ ~ ~ execute @s[tag=!FireInSlot10] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot10] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot10] ~ ~ ~ execute @s[tag=!ChestInSlot10] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot10] ~ ~ ~ execute @s[tag=!DiamondOreInSlot10] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot10] ~ ~ ~ execute @s[tag=!CraftingTableInSlot10] ~ ~ ~ execute @s[tag=!WheatCropsInSlot10] ~ ~ ~ execute @s[tag=!FarmlandInSlot10] ~ ~ ~ execute @s[tag=!FurnaceInSlot10] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot10] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot10] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!LadderInSlot10] ~ ~ ~ execute @s[tag=!RailInSlot10] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot10] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot10] ~ ~ ~ execute @s[tag=!LeverInSlot10] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot10] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot10] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot10] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot10] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot10] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot10] ~ ~ ~ execute @s[tag=!StoneButtonInSlot10] ~ ~ ~ execute @s[tag=!SnowInSlot10] ~ ~ ~ execute @s[tag=!IceInSlot10] ~ ~ ~ execute @s[tag=!SnowBlockInSlot10] ~ ~ ~ execute @s[tag=!CactusInSlot10] ~ ~ ~ execute @s[tag=!SugarCanesInSlot10] ~ ~ ~ execute @s[tag=!JukeboxInSlot10] ~ ~ ~ execute @s[tag=!OakFenceInSlot10] ~ ~ ~ execute @s[tag=!PumpkinInSlot10] ~ ~ ~ execute @s[tag=!NetherrackInSlot10] ~ ~ ~ execute @s[tag=!SoulSandInSlot10] ~ ~ ~ execute @s[tag=!GlowstoneInSlot10] ~ ~ ~ execute @s[tag=!NetherPortalInSlot10] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot10] ~ ~ ~ execute @s[tag=!CakeBlockInSlot10] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot10] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot10] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot10] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot10] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot10] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot10] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot10] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot10] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot10] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot10] ~ ~ ~ execute @s[tag=!StoneBricksInSlot10] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot10] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot10] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot10] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot10] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot10] ~ ~ ~ execute @s[tag=!IronBarsInSlot10] ~ ~ ~ execute @s[tag=!GlassPaneInSlot10] ~ ~ ~ execute @s[tag=!MelonBlockInSlot10] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot10] ~ ~ ~ execute @s[tag=!MelonStemInSlot10] ~ ~ ~ execute @s[tag=!VinesInSlot10] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot10] ~ ~ ~ execute @s[tag=!BrickStairsInSlot10] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot10] ~ ~ ~ execute @s[tag=!MyceliumInSlot10] ~ ~ ~ execute @s[tag=!LilyPadInSlot10] ~ ~ ~ execute @s[tag=!NetherBrickInSlot10] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot10] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot10] ~ ~ ~ execute @s[tag=!NetherWartInSlot10] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot10] ~ ~ ~ execute @s[tag=!BrewingStandInSlot10] ~ ~ ~ execute @s[tag=!CauldronInSlot10] ~ ~ ~ execute @s[tag=!EndPortalInSlot10] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot10] ~ ~ ~ execute @s[tag=!EndStoneInSlot10] ~ ~ ~ execute @s[tag=!DragonEggInSlot10] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot10] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot10] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot10] ~ ~ ~ execute @s[tag=!CocoaInSlot10] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot10] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot10] ~ ~ ~ execute @s[tag=!EnderChestInSlot10] ~ ~ ~ execute @s[tag=!TripwireHookInSlot10] ~ ~ ~ execute @s[tag=!TripwireInSlot10] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot10] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot10] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot10] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot10] ~ ~ ~ execute @s[tag=!CommandBlockInSlot10] ~ ~ ~ execute @s[tag=!BeaconInSlot10] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot10] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot10] ~ ~ ~ execute @s[tag=!FlowerPotInSlot10] ~ ~ ~ execute @s[tag=!CarrotsInSlot10] ~ ~ ~ execute @s[tag=!PotatoesInSlot10] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot10] ~ ~ ~ execute @s[tag=!MobHeadInSlot10] ~ ~ ~ execute @s[tag=!AnvilInSlot10] ~ ~ ~ execute @s[tag=!TrappedChestInSlot10] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot10] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot10] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot10] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot10] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot10] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot10] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot10] ~ ~ ~ execute @s[tag=!HopperInSlot10] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot10] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot10] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot10] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot10] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot10] ~ ~ ~ execute @s[tag=!DropperInSlot10] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot10] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot10] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot10] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot10] ~ ~ ~ execute @s[tag=!AcaciaWoodFacingYInSlot10] ~ ~ ~ execute @s[tag=!DarkOakWoodFacingYInSlot10] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot10] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot10] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot10] ~ ~ ~ execute @s[tag=!BarrierInSlot10] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot10] ~ ~ ~ execute @s[tag=!PrismarineInSlot10] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot10] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot10] ~ ~ ~ execute @s[tag=!SeaLanternInSlot10] ~ ~ ~ execute @s[tag=!HayBaleInSlot10] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot10] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot10] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot10] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot10] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot10] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot10] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot10] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot10] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot10] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot10] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot10] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot10] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot10] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot10] ~ ~ ~ execute @s[tag=!RedCarpetInSlot10] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot10] ~ ~ ~ execute @s[tag=!HardenedClayInSlot10] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot10] ~ ~ ~ execute @s[tag=!PackedIceInSlot10] ~ ~ ~ execute @s[tag=!SunflowerInSlot10] ~ ~ ~ execute @s[tag=!LilacInSlot10] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot10] ~ ~ ~ execute @s[tag=!LargeFernInSlot10] ~ ~ ~ execute @s[tag=!RoseBushInSlot10] ~ ~ ~ execute @s[tag=!PeonyInSlot10] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot10] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot10] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot10] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot10] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot10] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot10] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot10] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot10] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot10] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot10] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot10] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot10] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot10] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot10] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot10] ~ ~ ~ execute @s[tag=!BirchFenceInSlot10] ~ ~ ~ execute @s[tag=!JungleFenceInSlot10] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot10] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot10] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot10] ~ ~ ~ execute @s[tag=!EndRodInSlot10] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot10] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot10] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot10] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot10] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot10] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot10] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot10] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot10] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot10] ~ ~ ~ execute @s[tag=!GrassPathInSlot10] ~ ~ ~ execute @s[tag=!EndGatewayInSlot10] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot10] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot10] ~ ~ ~ execute @s[tag=!FrostedIceInSlot10] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot10] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot10] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot10] ~ ~ ~ execute @s[tag=!BoneBlockInSlot10] ~ ~ ~ execute @s[tag=!StructureVoidInSlot10] ~ ~ ~ execute @s[tag=!ObserverInSlot10] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot10] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot10] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot10] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot10] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot10] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot10] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot10] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot10] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot10] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot10] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot10] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot10] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot10] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot10] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot10] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot10] ~ ~ ~ execute @s[tag=!RedConcreteInSlot10] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot10] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot10] ~ ~ ~ execute @s[tag=!StructureBlockInSlot10] ~ ~ ~ scoreboard players tag @s add AirInSlot10 