scoreboard players tag @s add AirInSlot9 {Inventory:[{Slot:9b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot9 {Inventory:[{Slot:9b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot9 {Inventory:[{Slot:9b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot9 {Inventory:[{Slot:9b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot9 {Inventory:[{Slot:9b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot9 {Inventory:[{Slot:9b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot9 {Inventory:[{Slot:9b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot9 {Inventory:[{Slot:9b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot9 {Inventory:[{Slot:9b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot9 {Inventory:[{Slot:9b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot9 {Inventory:[{Slot:9b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot9 {Inventory:[{Slot:9b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot9 {Inventory:[{Slot:9b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot9 {Inventory:[{Slot:9b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot9 {Inventory:[{Slot:9b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot9 {Inventory:[{Slot:9b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot9 {Inventory:[{Slot:9b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot9 {Inventory:[{Slot:9b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot9 {Inventory:[{Slot:9b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot9 {Inventory:[{Slot:9b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot9 {Inventory:[{Slot:9b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot9 {Inventory:[{Slot:9b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot9 {Inventory:[{Slot:9b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot9 {Inventory:[{Slot:9b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot9 {Inventory:[{Slot:9b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot9 {Inventory:[{Slot:9b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot9 {Inventory:[{Slot:9b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot9 {Inventory:[{Slot:9b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot9 {Inventory:[{Slot:9b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot9 {Inventory:[{Slot:9b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot9 {Inventory:[{Slot:9b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot9 {Inventory:[{Slot:9b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot9 {Inventory:[{Slot:9b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot9 {Inventory:[{Slot:9b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot9 {Inventory:[{Slot:9b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot9 {Inventory:[{Slot:9b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot9 {Inventory:[{Slot:9b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot9 {Inventory:[{Slot:9b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot9 {Inventory:[{Slot:9b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot9 {Inventory:[{Slot:9b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot9 {Inventory:[{Slot:9b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot9 {Inventory:[{Slot:9b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot9 {Inventory:[{Slot:9b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot9 {Inventory:[{Slot:9b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot9 {Inventory:[{Slot:9b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot9 {Inventory:[{Slot:9b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot9 {Inventory:[{Slot:9b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot9 {Inventory:[{Slot:9b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot9 {Inventory:[{Slot:9b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot9 {Inventory:[{Slot:9b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot9 {Inventory:[{Slot:9b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot9 {Inventory:[{Slot:9b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot9 {Inventory:[{Slot:9b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot9 {Inventory:[{Slot:9b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot9 {Inventory:[{Slot:9b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot9 {Inventory:[{Slot:9b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot9 {Inventory:[{Slot:9b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot9 {Inventory:[{Slot:9b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot9 {Inventory:[{Slot:9b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot9 {Inventory:[{Slot:9b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot9 {Inventory:[{Slot:9b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot9 {Inventory:[{Slot:9b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot9 {Inventory:[{Slot:9b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot9 {Inventory:[{Slot:9b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot9 {Inventory:[{Slot:9b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot9 {Inventory:[{Slot:9b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot9 {Inventory:[{Slot:9b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot9 {Inventory:[{Slot:9b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot9 {Inventory:[{Slot:9b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot9 {Inventory:[{Slot:9b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot9 {Inventory:[{Slot:9b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot9 {Inventory:[{Slot:9b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot9 {Inventory:[{Slot:9b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot9 {Inventory:[{Slot:9b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot9 {Inventory:[{Slot:9b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot9 {Inventory:[{Slot:9b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot9 {Inventory:[{Slot:9b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot9 {Inventory:[{Slot:9b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot9 {Inventory:[{Slot:9b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot9 {Inventory:[{Slot:9b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot9 {Inventory:[{Slot:9b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot9 {Inventory:[{Slot:9b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot9 {Inventory:[{Slot:9b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot9 {Inventory:[{Slot:9b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot9 {Inventory:[{Slot:9b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot9] ~ ~ ~ execute @s[tag=!StoneInSlot9] ~ ~ ~ execute @s[tag=!GraniteInSlot9] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot9] ~ ~ ~ execute @s[tag=!DioriteInSlot9] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot9] ~ ~ ~ execute @s[tag=!AndesiteInSlot9] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot9] ~ ~ ~ execute @s[tag=!GrassBlockInSlot9] ~ ~ ~ execute @s[tag=!DirtInSlot9] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot9] ~ ~ ~ execute @s[tag=!PodzolInSlot9] ~ ~ ~ execute @s[tag=!CobblestoneInSlot9] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot9] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot9] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot9] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot9] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot9] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot9] ~ ~ ~ execute @s[tag=!OakSaplingInSlot9] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot9] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot9] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot9] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot9] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot9] ~ ~ ~ execute @s[tag=!BedrockInSlot9] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot9] ~ ~ ~ execute @s[tag=!StillWaterInSlot9] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot9] ~ ~ ~ execute @s[tag=!StillLavaInSlot9] ~ ~ ~ execute @s[tag=!SandInSlot9] ~ ~ ~ execute @s[tag=!RedSandInSlot9] ~ ~ ~ execute @s[tag=!GravelInSlot9] ~ ~ ~ execute @s[tag=!GoldOreInSlot9] ~ ~ ~ execute @s[tag=!IronOreInSlot9] ~ ~ ~ execute @s[tag=!CoalOreInSlot9] ~ ~ ~ execute @s[tag=!OakWoodInSlot9] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot9] ~ ~ ~ execute @s[tag=!BirchWoodInSlot9] ~ ~ ~ execute @s[tag=!JungleWoodInSlot9] ~ ~ ~ execute @s[tag=!OakLeavesInSlot9] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot9] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot9] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot9] ~ ~ ~ execute @s[tag=!SpongeInSlot9] ~ ~ ~ execute @s[tag=!WetSpongeInSlot9] ~ ~ ~ execute @s[tag=!GlassInSlot9] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot9] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot9] ~ ~ ~ execute @s[tag=!DispenserInSlot9] ~ ~ ~ execute @s[tag=!SandstoneInSlot9] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot9] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot9] ~ ~ ~ execute @s[tag=!NoteBlockInSlot9] ~ ~ ~ execute @s[tag=!BedInSlot9] ~ ~ ~ execute @s[tag=!PoweredRailInSlot9] ~ ~ ~ execute @s[tag=!DetectorRailInSlot9] ~ ~ ~ execute @s[tag=!StickyPistonInSlot9] ~ ~ ~ execute @s[tag=!CobwebInSlot9] ~ ~ ~ execute @s[tag=!DeadShrubInSlot9] ~ ~ ~ execute @s[tag=!GrassInSlot9] ~ ~ ~ execute @s[tag=!FernInSlot9] ~ ~ ~ execute @s[tag=!DeadBushInSlot9] ~ ~ ~ execute @s[tag=!PistonInSlot9] ~ ~ ~ execute @s[tag=!PistonHeadInSlot9] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot9] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot9] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot9] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot9] ~ ~ ~ execute @s[tag=!YellowWoolInSlot9] ~ ~ ~ execute @s[tag=!LimeWoolInSlot9] ~ ~ ~ execute @s[tag=!PinkWoolInSlot9] ~ ~ ~ execute @s[tag=!GrayWoolInSlot9] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot9] ~ ~ ~ execute @s[tag=!CyanWoolInSlot9] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot9] ~ ~ ~ execute @s[tag=!BlueWoolInSlot9] ~ ~ ~ execute @s[tag=!BrownWoolInSlot9] ~ ~ ~ execute @s[tag=!GreenWoolInSlot9] ~ ~ ~ execute @s[tag=!RedWoolInSlot9] ~ ~ ~ execute @s[tag=!BlackWoolInSlot9] ~ ~ ~ execute @s[tag=!DandelionInSlot9] ~ ~ ~ execute @s[tag=!PoppyInSlot9] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot9] ~ ~ ~ execute @s[tag=!AlliumInSlot9] ~ ~ ~ execute @s[tag=!AzureBluetInSlot9] ~ ~ ~ execute @s[tag=!RedTulipInSlot9] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot9] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot9] ~ ~ ~ execute @s[tag=!PinkTulipInSlot9] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot9] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot9] ~ ~ ~ execute @s[tag=!RedMushroomInSlot9] ~ ~ ~ execute @s[tag=!GoldBlockInSlot9] ~ ~ ~ execute @s[tag=!IronBlockInSlot9] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot9] ~ ~ ~ execute @s[tag=!StoneSlabInSlot9] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot9] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot9] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot9] ~ ~ ~ execute @s[tag=!BrickSlabInSlot9] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot9] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot9] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot9] ~ ~ ~ execute @s[tag=!BricksInSlot9] ~ ~ ~ execute @s[tag=!TNTInSlot9] ~ ~ ~ execute @s[tag=!BookshelfInSlot9] ~ ~ ~ execute @s[tag=!MossStoneInSlot9] ~ ~ ~ execute @s[tag=!ObsidianInSlot9] ~ ~ ~ execute @s[tag=!TorchInSlot9] ~ ~ ~ execute @s[tag=!FireInSlot9] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot9] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot9] ~ ~ ~ execute @s[tag=!ChestInSlot9] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot9] ~ ~ ~ execute @s[tag=!DiamondOreInSlot9] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot9] ~ ~ ~ execute @s[tag=!CraftingTableInSlot9] ~ ~ ~ execute @s[tag=!WheatCropsInSlot9] ~ ~ ~ execute @s[tag=!FarmlandInSlot9] ~ ~ ~ execute @s[tag=!FurnaceInSlot9] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot9] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot9] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!LadderInSlot9] ~ ~ ~ execute @s[tag=!RailInSlot9] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot9] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot9] ~ ~ ~ execute @s[tag=!LeverInSlot9] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot9] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot9] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot9] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot9] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot9] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot9] ~ ~ ~ execute @s[tag=!StoneButtonInSlot9] ~ ~ ~ execute @s[tag=!SnowInSlot9] ~ ~ ~ execute @s[tag=!IceInSlot9] ~ ~ ~ execute @s[tag=!SnowBlockInSlot9] ~ ~ ~ execute @s[tag=!CactusInSlot9] ~ ~ ~ execute @s[tag=!SugarCanesInSlot9] ~ ~ ~ execute @s[tag=!JukeboxInSlot9] ~ ~ ~ execute @s[tag=!OakFenceInSlot9] ~ ~ ~ execute @s[tag=!PumpkinInSlot9] ~ ~ ~ execute @s[tag=!NetherrackInSlot9] ~ ~ ~ execute @s[tag=!SoulSandInSlot9] ~ ~ ~ execute @s[tag=!GlowstoneInSlot9] ~ ~ ~ execute @s[tag=!NetherPortalInSlot9] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot9] ~ ~ ~ execute @s[tag=!CakeBlockInSlot9] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot9] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot9] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot9] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot9] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot9] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot9] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot9] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot9] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot9] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot9] ~ ~ ~ execute @s[tag=!StoneBricksInSlot9] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot9] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot9] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot9] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot9] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot9] ~ ~ ~ execute @s[tag=!IronBarsInSlot9] ~ ~ ~ execute @s[tag=!GlassPaneInSlot9] ~ ~ ~ execute @s[tag=!MelonBlockInSlot9] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot9] ~ ~ ~ execute @s[tag=!MelonStemInSlot9] ~ ~ ~ execute @s[tag=!VinesInSlot9] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot9] ~ ~ ~ execute @s[tag=!BrickStairsInSlot9] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot9] ~ ~ ~ execute @s[tag=!MyceliumInSlot9] ~ ~ ~ execute @s[tag=!LilyPadInSlot9] ~ ~ ~ execute @s[tag=!NetherBrickInSlot9] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot9] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot9] ~ ~ ~ execute @s[tag=!NetherWartInSlot9] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot9] ~ ~ ~ execute @s[tag=!BrewingStandInSlot9] ~ ~ ~ execute @s[tag=!CauldronInSlot9] ~ ~ ~ execute @s[tag=!EndPortalInSlot9] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot9] ~ ~ ~ execute @s[tag=!EndStoneInSlot9] ~ ~ ~ execute @s[tag=!DragonEggInSlot9] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot9] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot9] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot9] ~ ~ ~ execute @s[tag=!CocoaInSlot9] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot9] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot9] ~ ~ ~ execute @s[tag=!EnderChestInSlot9] ~ ~ ~ execute @s[tag=!TripwireHookInSlot9] ~ ~ ~ execute @s[tag=!TripwireInSlot9] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot9] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot9] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot9] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot9] ~ ~ ~ execute @s[tag=!CommandBlockInSlot9] ~ ~ ~ execute @s[tag=!BeaconInSlot9] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot9] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot9] ~ ~ ~ execute @s[tag=!FlowerPotInSlot9] ~ ~ ~ execute @s[tag=!CarrotsInSlot9] ~ ~ ~ execute @s[tag=!PotatoesInSlot9] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot9] ~ ~ ~ execute @s[tag=!MobHeadInSlot9] ~ ~ ~ execute @s[tag=!AnvilInSlot9] ~ ~ ~ execute @s[tag=!TrappedChestInSlot9] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot9] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot9] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot9] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot9] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot9] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot9] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot9] ~ ~ ~ execute @s[tag=!HopperInSlot9] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot9] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot9] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot9] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot9] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot9] ~ ~ ~ execute @s[tag=!DropperInSlot9] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot9] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot9] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot9] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot9] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot9] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot9] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot9] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot9] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot9] ~ ~ ~ execute @s[tag=!BarrierInSlot9] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot9] ~ ~ ~ execute @s[tag=!PrismarineInSlot9] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot9] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot9] ~ ~ ~ execute @s[tag=!SeaLanternInSlot9] ~ ~ ~ execute @s[tag=!HayBaleInSlot9] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot9] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot9] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot9] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot9] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot9] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot9] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot9] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot9] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot9] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot9] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot9] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot9] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot9] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot9] ~ ~ ~ execute @s[tag=!RedCarpetInSlot9] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot9] ~ ~ ~ execute @s[tag=!HardenedClayInSlot9] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot9] ~ ~ ~ execute @s[tag=!PackedIceInSlot9] ~ ~ ~ execute @s[tag=!SunflowerInSlot9] ~ ~ ~ execute @s[tag=!LilacInSlot9] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot9] ~ ~ ~ execute @s[tag=!LargeFernInSlot9] ~ ~ ~ execute @s[tag=!RoseBushInSlot9] ~ ~ ~ execute @s[tag=!PeonyInSlot9] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot9] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot9] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot9] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot9] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot9] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot9] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot9] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot9] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot9] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot9] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot9] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot9] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot9] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot9] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot9] ~ ~ ~ execute @s[tag=!BirchFenceInSlot9] ~ ~ ~ execute @s[tag=!JungleFenceInSlot9] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot9] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot9] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot9] ~ ~ ~ execute @s[tag=!EndRodInSlot9] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot9] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot9] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot9] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot9] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot9] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot9] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot9] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot9] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot9] ~ ~ ~ execute @s[tag=!GrassPathInSlot9] ~ ~ ~ execute @s[tag=!EndGatewayInSlot9] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot9] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot9] ~ ~ ~ execute @s[tag=!FrostedIceInSlot9] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot9] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot9] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot9] ~ ~ ~ execute @s[tag=!BoneBlockInSlot9] ~ ~ ~ execute @s[tag=!StructureVoidInSlot9] ~ ~ ~ execute @s[tag=!ObserverInSlot9] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot9] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot9] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot9] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot9] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot9] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot9] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot9] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot9] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot9] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot9] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot9] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot9] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot9] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot9] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot9] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot9] ~ ~ ~ execute @s[tag=!RedConcreteInSlot9] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot9] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot9] ~ ~ ~ execute @s[tag=!StructureBlockInSlot9] ~ ~ ~ scoreboard players tag @s add AirInSlot9 