scoreboard players tag @s add AirInSlot32 {Inventory:[{Slot:32b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot32 {Inventory:[{Slot:32b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot32 {Inventory:[{Slot:32b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot32 {Inventory:[{Slot:32b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot32 {Inventory:[{Slot:32b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot32 {Inventory:[{Slot:32b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot32 {Inventory:[{Slot:32b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot32 {Inventory:[{Slot:32b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot32 {Inventory:[{Slot:32b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot32 {Inventory:[{Slot:32b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot32 {Inventory:[{Slot:32b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot32 {Inventory:[{Slot:32b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot32 {Inventory:[{Slot:32b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot32 {Inventory:[{Slot:32b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot32 {Inventory:[{Slot:32b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot32 {Inventory:[{Slot:32b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot32 {Inventory:[{Slot:32b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot32 {Inventory:[{Slot:32b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot32 {Inventory:[{Slot:32b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot32 {Inventory:[{Slot:32b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot32 {Inventory:[{Slot:32b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot32 {Inventory:[{Slot:32b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot32 {Inventory:[{Slot:32b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot32 {Inventory:[{Slot:32b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot32 {Inventory:[{Slot:32b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot32 {Inventory:[{Slot:32b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot32 {Inventory:[{Slot:32b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot32 {Inventory:[{Slot:32b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot32 {Inventory:[{Slot:32b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot32 {Inventory:[{Slot:32b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot32 {Inventory:[{Slot:32b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot32 {Inventory:[{Slot:32b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot32 {Inventory:[{Slot:32b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot32 {Inventory:[{Slot:32b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot32 {Inventory:[{Slot:32b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot32 {Inventory:[{Slot:32b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot32 {Inventory:[{Slot:32b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot32 {Inventory:[{Slot:32b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot32 {Inventory:[{Slot:32b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot32 {Inventory:[{Slot:32b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot32 {Inventory:[{Slot:32b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot32 {Inventory:[{Slot:32b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot32 {Inventory:[{Slot:32b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot32 {Inventory:[{Slot:32b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot32 {Inventory:[{Slot:32b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot32 {Inventory:[{Slot:32b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot32 {Inventory:[{Slot:32b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot32 {Inventory:[{Slot:32b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot32 {Inventory:[{Slot:32b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot32 {Inventory:[{Slot:32b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot32 {Inventory:[{Slot:32b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot32 {Inventory:[{Slot:32b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot32 {Inventory:[{Slot:32b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot32 {Inventory:[{Slot:32b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot32 {Inventory:[{Slot:32b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot32 {Inventory:[{Slot:32b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot32 {Inventory:[{Slot:32b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot32 {Inventory:[{Slot:32b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot32 {Inventory:[{Slot:32b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot32 {Inventory:[{Slot:32b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot32 {Inventory:[{Slot:32b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot32 {Inventory:[{Slot:32b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot32 {Inventory:[{Slot:32b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot32 {Inventory:[{Slot:32b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot32 {Inventory:[{Slot:32b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot32 {Inventory:[{Slot:32b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot32 {Inventory:[{Slot:32b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot32 {Inventory:[{Slot:32b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot32 {Inventory:[{Slot:32b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot32 {Inventory:[{Slot:32b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot32 {Inventory:[{Slot:32b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot32 {Inventory:[{Slot:32b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot32 {Inventory:[{Slot:32b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot32 {Inventory:[{Slot:32b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot32 {Inventory:[{Slot:32b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot32 {Inventory:[{Slot:32b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot32 {Inventory:[{Slot:32b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot32 {Inventory:[{Slot:32b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot32 {Inventory:[{Slot:32b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot32 {Inventory:[{Slot:32b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot32 {Inventory:[{Slot:32b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot32 {Inventory:[{Slot:32b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot32 {Inventory:[{Slot:32b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot32 {Inventory:[{Slot:32b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot32 {Inventory:[{Slot:32b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot32] ~ ~ ~ execute @s[tag=!StoneInSlot32] ~ ~ ~ execute @s[tag=!GraniteInSlot32] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot32] ~ ~ ~ execute @s[tag=!DioriteInSlot32] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot32] ~ ~ ~ execute @s[tag=!AndesiteInSlot32] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot32] ~ ~ ~ execute @s[tag=!GrassBlockInSlot32] ~ ~ ~ execute @s[tag=!DirtInSlot32] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot32] ~ ~ ~ execute @s[tag=!PodzolInSlot32] ~ ~ ~ execute @s[tag=!CobblestoneInSlot32] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot32] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot32] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot32] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot32] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot32] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot32] ~ ~ ~ execute @s[tag=!OakSaplingInSlot32] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot32] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot32] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot32] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot32] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot32] ~ ~ ~ execute @s[tag=!BedrockInSlot32] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot32] ~ ~ ~ execute @s[tag=!StillWaterInSlot32] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot32] ~ ~ ~ execute @s[tag=!StillLavaInSlot32] ~ ~ ~ execute @s[tag=!SandInSlot32] ~ ~ ~ execute @s[tag=!RedSandInSlot32] ~ ~ ~ execute @s[tag=!GravelInSlot32] ~ ~ ~ execute @s[tag=!GoldOreInSlot32] ~ ~ ~ execute @s[tag=!IronOreInSlot32] ~ ~ ~ execute @s[tag=!CoalOreInSlot32] ~ ~ ~ execute @s[tag=!OakWoodInSlot32] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot32] ~ ~ ~ execute @s[tag=!BirchWoodInSlot32] ~ ~ ~ execute @s[tag=!JungleWoodInSlot32] ~ ~ ~ execute @s[tag=!OakLeavesInSlot32] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot32] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot32] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot32] ~ ~ ~ execute @s[tag=!SpongeInSlot32] ~ ~ ~ execute @s[tag=!WetSpongeInSlot32] ~ ~ ~ execute @s[tag=!GlassInSlot32] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot32] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot32] ~ ~ ~ execute @s[tag=!DispenserInSlot32] ~ ~ ~ execute @s[tag=!SandstoneInSlot32] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot32] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot32] ~ ~ ~ execute @s[tag=!NoteBlockInSlot32] ~ ~ ~ execute @s[tag=!BedInSlot32] ~ ~ ~ execute @s[tag=!PoweredRailInSlot32] ~ ~ ~ execute @s[tag=!DetectorRailInSlot32] ~ ~ ~ execute @s[tag=!StickyPistonInSlot32] ~ ~ ~ execute @s[tag=!CobwebInSlot32] ~ ~ ~ execute @s[tag=!DeadShrubInSlot32] ~ ~ ~ execute @s[tag=!GrassInSlot32] ~ ~ ~ execute @s[tag=!FernInSlot32] ~ ~ ~ execute @s[tag=!DeadBushInSlot32] ~ ~ ~ execute @s[tag=!PistonInSlot32] ~ ~ ~ execute @s[tag=!PistonHeadInSlot32] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot32] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot32] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot32] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot32] ~ ~ ~ execute @s[tag=!YellowWoolInSlot32] ~ ~ ~ execute @s[tag=!LimeWoolInSlot32] ~ ~ ~ execute @s[tag=!PinkWoolInSlot32] ~ ~ ~ execute @s[tag=!GrayWoolInSlot32] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot32] ~ ~ ~ execute @s[tag=!CyanWoolInSlot32] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot32] ~ ~ ~ execute @s[tag=!BlueWoolInSlot32] ~ ~ ~ execute @s[tag=!BrownWoolInSlot32] ~ ~ ~ execute @s[tag=!GreenWoolInSlot32] ~ ~ ~ execute @s[tag=!RedWoolInSlot32] ~ ~ ~ execute @s[tag=!BlackWoolInSlot32] ~ ~ ~ execute @s[tag=!DandelionInSlot32] ~ ~ ~ execute @s[tag=!PoppyInSlot32] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot32] ~ ~ ~ execute @s[tag=!AlliumInSlot32] ~ ~ ~ execute @s[tag=!AzureBluetInSlot32] ~ ~ ~ execute @s[tag=!RedTulipInSlot32] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot32] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot32] ~ ~ ~ execute @s[tag=!PinkTulipInSlot32] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot32] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot32] ~ ~ ~ execute @s[tag=!RedMushroomInSlot32] ~ ~ ~ execute @s[tag=!GoldBlockInSlot32] ~ ~ ~ execute @s[tag=!IronBlockInSlot32] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot32] ~ ~ ~ execute @s[tag=!StoneSlabInSlot32] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot32] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot32] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot32] ~ ~ ~ execute @s[tag=!BrickSlabInSlot32] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot32] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot32] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot32] ~ ~ ~ execute @s[tag=!BricksInSlot32] ~ ~ ~ execute @s[tag=!TNTInSlot32] ~ ~ ~ execute @s[tag=!BookshelfInSlot32] ~ ~ ~ execute @s[tag=!MossStoneInSlot32] ~ ~ ~ execute @s[tag=!ObsidianInSlot32] ~ ~ ~ execute @s[tag=!TorchInSlot32] ~ ~ ~ execute @s[tag=!FireInSlot32] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot32] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot32] ~ ~ ~ execute @s[tag=!ChestInSlot32] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot32] ~ ~ ~ execute @s[tag=!DiamondOreInSlot32] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot32] ~ ~ ~ execute @s[tag=!CraftingTableInSlot32] ~ ~ ~ execute @s[tag=!WheatCropsInSlot32] ~ ~ ~ execute @s[tag=!FarmlandInSlot32] ~ ~ ~ execute @s[tag=!FurnaceInSlot32] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot32] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot32] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!LadderInSlot32] ~ ~ ~ execute @s[tag=!RailInSlot32] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot32] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot32] ~ ~ ~ execute @s[tag=!LeverInSlot32] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot32] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot32] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot32] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot32] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot32] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot32] ~ ~ ~ execute @s[tag=!StoneButtonInSlot32] ~ ~ ~ execute @s[tag=!SnowInSlot32] ~ ~ ~ execute @s[tag=!IceInSlot32] ~ ~ ~ execute @s[tag=!SnowBlockInSlot32] ~ ~ ~ execute @s[tag=!CactusInSlot32] ~ ~ ~ execute @s[tag=!SugarCanesInSlot32] ~ ~ ~ execute @s[tag=!JukeboxInSlot32] ~ ~ ~ execute @s[tag=!OakFenceInSlot32] ~ ~ ~ execute @s[tag=!PumpkinInSlot32] ~ ~ ~ execute @s[tag=!NetherrackInSlot32] ~ ~ ~ execute @s[tag=!SoulSandInSlot32] ~ ~ ~ execute @s[tag=!GlowstoneInSlot32] ~ ~ ~ execute @s[tag=!NetherPortalInSlot32] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot32] ~ ~ ~ execute @s[tag=!CakeBlockInSlot32] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot32] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot32] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot32] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot32] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot32] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot32] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot32] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot32] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot32] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot32] ~ ~ ~ execute @s[tag=!StoneBricksInSlot32] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot32] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot32] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot32] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot32] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot32] ~ ~ ~ execute @s[tag=!IronBarsInSlot32] ~ ~ ~ execute @s[tag=!GlassPaneInSlot32] ~ ~ ~ execute @s[tag=!MelonBlockInSlot32] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot32] ~ ~ ~ execute @s[tag=!MelonStemInSlot32] ~ ~ ~ execute @s[tag=!VinesInSlot32] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot32] ~ ~ ~ execute @s[tag=!BrickStairsInSlot32] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot32] ~ ~ ~ execute @s[tag=!MyceliumInSlot32] ~ ~ ~ execute @s[tag=!LilyPadInSlot32] ~ ~ ~ execute @s[tag=!NetherBrickInSlot32] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot32] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot32] ~ ~ ~ execute @s[tag=!NetherWartInSlot32] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot32] ~ ~ ~ execute @s[tag=!BrewingStandInSlot32] ~ ~ ~ execute @s[tag=!CauldronInSlot32] ~ ~ ~ execute @s[tag=!EndPortalInSlot32] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot32] ~ ~ ~ execute @s[tag=!EndStoneInSlot32] ~ ~ ~ execute @s[tag=!DragonEggInSlot32] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot32] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot32] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot32] ~ ~ ~ execute @s[tag=!CocoaInSlot32] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot32] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot32] ~ ~ ~ execute @s[tag=!EnderChestInSlot32] ~ ~ ~ execute @s[tag=!TripwireHookInSlot32] ~ ~ ~ execute @s[tag=!TripwireInSlot32] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot32] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot32] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot32] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot32] ~ ~ ~ execute @s[tag=!CommandBlockInSlot32] ~ ~ ~ execute @s[tag=!BeaconInSlot32] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot32] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot32] ~ ~ ~ execute @s[tag=!FlowerPotInSlot32] ~ ~ ~ execute @s[tag=!CarrotsInSlot32] ~ ~ ~ execute @s[tag=!PotatoesInSlot32] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot32] ~ ~ ~ execute @s[tag=!MobHeadInSlot32] ~ ~ ~ execute @s[tag=!AnvilInSlot32] ~ ~ ~ execute @s[tag=!TrappedChestInSlot32] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot32] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot32] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot32] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot32] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot32] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot32] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot32] ~ ~ ~ execute @s[tag=!HopperInSlot32] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot32] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot32] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot32] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot32] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot32] ~ ~ ~ execute @s[tag=!DropperInSlot32] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot32] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot32] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot32] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot32] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot32] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot32] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot32] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot32] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot32] ~ ~ ~ execute @s[tag=!BarrierInSlot32] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot32] ~ ~ ~ execute @s[tag=!PrismarineInSlot32] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot32] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot32] ~ ~ ~ execute @s[tag=!SeaLanternInSlot32] ~ ~ ~ execute @s[tag=!HayBaleInSlot32] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot32] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot32] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot32] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot32] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot32] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot32] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot32] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot32] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot32] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot32] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot32] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot32] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot32] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot32] ~ ~ ~ execute @s[tag=!RedCarpetInSlot32] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot32] ~ ~ ~ execute @s[tag=!HardenedClayInSlot32] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot32] ~ ~ ~ execute @s[tag=!PackedIceInSlot32] ~ ~ ~ execute @s[tag=!SunflowerInSlot32] ~ ~ ~ execute @s[tag=!LilacInSlot32] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot32] ~ ~ ~ execute @s[tag=!LargeFernInSlot32] ~ ~ ~ execute @s[tag=!RoseBushInSlot32] ~ ~ ~ execute @s[tag=!PeonyInSlot32] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot32] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot32] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot32] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot32] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot32] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot32] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot32] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot32] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot32] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot32] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot32] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot32] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot32] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot32] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot32] ~ ~ ~ execute @s[tag=!BirchFenceInSlot32] ~ ~ ~ execute @s[tag=!JungleFenceInSlot32] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot32] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot32] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot32] ~ ~ ~ execute @s[tag=!EndRodInSlot32] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot32] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot32] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot32] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot32] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot32] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot32] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot32] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot32] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot32] ~ ~ ~ execute @s[tag=!GrassPathInSlot32] ~ ~ ~ execute @s[tag=!EndGatewayInSlot32] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot32] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot32] ~ ~ ~ execute @s[tag=!FrostedIceInSlot32] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot32] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot32] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot32] ~ ~ ~ execute @s[tag=!BoneBlockInSlot32] ~ ~ ~ execute @s[tag=!StructureVoidInSlot32] ~ ~ ~ execute @s[tag=!ObserverInSlot32] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot32] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot32] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot32] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot32] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot32] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot32] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot32] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot32] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot32] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot32] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot32] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot32] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot32] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot32] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot32] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot32] ~ ~ ~ execute @s[tag=!RedConcreteInSlot32] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot32] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot32] ~ ~ ~ execute @s[tag=!StructureBlockInSlot32] ~ ~ ~ scoreboard players tag @s add AirInSlot32 