scoreboard players tag @s add AirInSlot26 {Inventory:[{Slot:26b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot26 {Inventory:[{Slot:26b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot26 {Inventory:[{Slot:26b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot26 {Inventory:[{Slot:26b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakLogFacingYInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceLogFacingYInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchLogFacingYInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleLogFacingYInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot26 {Inventory:[{Slot:26b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot26 {Inventory:[{Slot:26b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot26 {Inventory:[{Slot:26b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot26 {Inventory:[{Slot:26b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot26 {Inventory:[{Slot:26b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot26 {Inventory:[{Slot:26b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot26 {Inventory:[{Slot:26b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot26 {Inventory:[{Slot:26b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot26 {Inventory:[{Slot:26b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot26 {Inventory:[{Slot:26b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot26 {Inventory:[{Slot:26b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot26 {Inventory:[{Slot:26b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot26 {Inventory:[{Slot:26b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot26 {Inventory:[{Slot:26b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot26 {Inventory:[{Slot:26b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot26 {Inventory:[{Slot:26b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot26 {Inventory:[{Slot:26b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot26 {Inventory:[{Slot:26b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot26 {Inventory:[{Slot:26b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot26 {Inventory:[{Slot:26b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot26 {Inventory:[{Slot:26b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot26 {Inventory:[{Slot:26b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot26 {Inventory:[{Slot:26b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot26 {Inventory:[{Slot:26b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot26 {Inventory:[{Slot:26b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot26 {Inventory:[{Slot:26b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodFacingYInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodFacingYInSlot26 {Inventory:[{Slot:26b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot26 {Inventory:[{Slot:26b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot26 {Inventory:[{Slot:26b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot26 {Inventory:[{Slot:26b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot26 {Inventory:[{Slot:26b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot26 {Inventory:[{Slot:26b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot26 {Inventory:[{Slot:26b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot26 {Inventory:[{Slot:26b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot26 {Inventory:[{Slot:26b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot26 {Inventory:[{Slot:26b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot26 {Inventory:[{Slot:26b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot26 {Inventory:[{Slot:26b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot26 {Inventory:[{Slot:26b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot26 {Inventory:[{Slot:26b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot26 {Inventory:[{Slot:26b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot26 {Inventory:[{Slot:26b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot26 {Inventory:[{Slot:26b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot26 {Inventory:[{Slot:26b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot26] ~ ~ ~ execute @s[tag=!StoneInSlot26] ~ ~ ~ execute @s[tag=!GraniteInSlot26] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot26] ~ ~ ~ execute @s[tag=!DioriteInSlot26] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot26] ~ ~ ~ execute @s[tag=!AndesiteInSlot26] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot26] ~ ~ ~ execute @s[tag=!GrassBlockInSlot26] ~ ~ ~ execute @s[tag=!DirtInSlot26] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot26] ~ ~ ~ execute @s[tag=!PodzolInSlot26] ~ ~ ~ execute @s[tag=!CobblestoneInSlot26] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot26] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot26] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot26] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot26] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot26] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot26] ~ ~ ~ execute @s[tag=!OakSaplingInSlot26] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot26] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot26] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot26] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot26] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot26] ~ ~ ~ execute @s[tag=!BedrockInSlot26] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot26] ~ ~ ~ execute @s[tag=!StillWaterInSlot26] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot26] ~ ~ ~ execute @s[tag=!StillLavaInSlot26] ~ ~ ~ execute @s[tag=!SandInSlot26] ~ ~ ~ execute @s[tag=!RedSandInSlot26] ~ ~ ~ execute @s[tag=!GravelInSlot26] ~ ~ ~ execute @s[tag=!GoldOreInSlot26] ~ ~ ~ execute @s[tag=!IronOreInSlot26] ~ ~ ~ execute @s[tag=!CoalOreInSlot26] ~ ~ ~ execute @s[tag=!OakLogFacingYInSlot26] ~ ~ ~ execute @s[tag=!SpruceLogFacingYInSlot26] ~ ~ ~ execute @s[tag=!BirchLogFacingYInSlot26] ~ ~ ~ execute @s[tag=!JungleLogFacingYInSlot26] ~ ~ ~ execute @s[tag=!OakLeavesInSlot26] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot26] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot26] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot26] ~ ~ ~ execute @s[tag=!SpongeInSlot26] ~ ~ ~ execute @s[tag=!WetSpongeInSlot26] ~ ~ ~ execute @s[tag=!GlassInSlot26] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot26] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot26] ~ ~ ~ execute @s[tag=!DispenserInSlot26] ~ ~ ~ execute @s[tag=!SandstoneInSlot26] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot26] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot26] ~ ~ ~ execute @s[tag=!NoteBlockInSlot26] ~ ~ ~ execute @s[tag=!BedInSlot26] ~ ~ ~ execute @s[tag=!PoweredRailInSlot26] ~ ~ ~ execute @s[tag=!DetectorRailInSlot26] ~ ~ ~ execute @s[tag=!StickyPistonInSlot26] ~ ~ ~ execute @s[tag=!CobwebInSlot26] ~ ~ ~ execute @s[tag=!DeadShrubInSlot26] ~ ~ ~ execute @s[tag=!GrassInSlot26] ~ ~ ~ execute @s[tag=!FernInSlot26] ~ ~ ~ execute @s[tag=!DeadBushInSlot26] ~ ~ ~ execute @s[tag=!PistonInSlot26] ~ ~ ~ execute @s[tag=!PistonHeadInSlot26] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot26] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot26] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot26] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot26] ~ ~ ~ execute @s[tag=!YellowWoolInSlot26] ~ ~ ~ execute @s[tag=!LimeWoolInSlot26] ~ ~ ~ execute @s[tag=!PinkWoolInSlot26] ~ ~ ~ execute @s[tag=!GrayWoolInSlot26] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot26] ~ ~ ~ execute @s[tag=!CyanWoolInSlot26] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot26] ~ ~ ~ execute @s[tag=!BlueWoolInSlot26] ~ ~ ~ execute @s[tag=!BrownWoolInSlot26] ~ ~ ~ execute @s[tag=!GreenWoolInSlot26] ~ ~ ~ execute @s[tag=!RedWoolInSlot26] ~ ~ ~ execute @s[tag=!BlackWoolInSlot26] ~ ~ ~ execute @s[tag=!DandelionInSlot26] ~ ~ ~ execute @s[tag=!PoppyInSlot26] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot26] ~ ~ ~ execute @s[tag=!AlliumInSlot26] ~ ~ ~ execute @s[tag=!AzureBluetInSlot26] ~ ~ ~ execute @s[tag=!RedTulipInSlot26] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot26] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot26] ~ ~ ~ execute @s[tag=!PinkTulipInSlot26] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot26] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot26] ~ ~ ~ execute @s[tag=!RedMushroomInSlot26] ~ ~ ~ execute @s[tag=!GoldBlockInSlot26] ~ ~ ~ execute @s[tag=!IronBlockInSlot26] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot26] ~ ~ ~ execute @s[tag=!StoneSlabInSlot26] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot26] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot26] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot26] ~ ~ ~ execute @s[tag=!BrickSlabInSlot26] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot26] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot26] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot26] ~ ~ ~ execute @s[tag=!BricksInSlot26] ~ ~ ~ execute @s[tag=!TNTInSlot26] ~ ~ ~ execute @s[tag=!BookshelfInSlot26] ~ ~ ~ execute @s[tag=!MossStoneInSlot26] ~ ~ ~ execute @s[tag=!ObsidianInSlot26] ~ ~ ~ execute @s[tag=!TorchInSlot26] ~ ~ ~ execute @s[tag=!FireInSlot26] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot26] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot26] ~ ~ ~ execute @s[tag=!ChestInSlot26] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot26] ~ ~ ~ execute @s[tag=!DiamondOreInSlot26] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot26] ~ ~ ~ execute @s[tag=!CraftingTableInSlot26] ~ ~ ~ execute @s[tag=!WheatCropsInSlot26] ~ ~ ~ execute @s[tag=!FarmlandInSlot26] ~ ~ ~ execute @s[tag=!FurnaceInSlot26] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot26] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot26] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!LadderInSlot26] ~ ~ ~ execute @s[tag=!RailInSlot26] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot26] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot26] ~ ~ ~ execute @s[tag=!LeverInSlot26] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot26] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot26] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot26] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot26] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot26] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot26] ~ ~ ~ execute @s[tag=!StoneButtonInSlot26] ~ ~ ~ execute @s[tag=!SnowInSlot26] ~ ~ ~ execute @s[tag=!IceInSlot26] ~ ~ ~ execute @s[tag=!SnowBlockInSlot26] ~ ~ ~ execute @s[tag=!CactusInSlot26] ~ ~ ~ execute @s[tag=!SugarCanesInSlot26] ~ ~ ~ execute @s[tag=!JukeboxInSlot26] ~ ~ ~ execute @s[tag=!OakFenceInSlot26] ~ ~ ~ execute @s[tag=!PumpkinInSlot26] ~ ~ ~ execute @s[tag=!NetherrackInSlot26] ~ ~ ~ execute @s[tag=!SoulSandInSlot26] ~ ~ ~ execute @s[tag=!GlowstoneInSlot26] ~ ~ ~ execute @s[tag=!NetherPortalInSlot26] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot26] ~ ~ ~ execute @s[tag=!CakeBlockInSlot26] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot26] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot26] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot26] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot26] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot26] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot26] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot26] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot26] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot26] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot26] ~ ~ ~ execute @s[tag=!StoneBricksInSlot26] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot26] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot26] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot26] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot26] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot26] ~ ~ ~ execute @s[tag=!IronBarsInSlot26] ~ ~ ~ execute @s[tag=!GlassPaneInSlot26] ~ ~ ~ execute @s[tag=!MelonBlockInSlot26] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot26] ~ ~ ~ execute @s[tag=!MelonStemInSlot26] ~ ~ ~ execute @s[tag=!VinesInSlot26] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot26] ~ ~ ~ execute @s[tag=!BrickStairsInSlot26] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot26] ~ ~ ~ execute @s[tag=!MyceliumInSlot26] ~ ~ ~ execute @s[tag=!LilyPadInSlot26] ~ ~ ~ execute @s[tag=!NetherBrickInSlot26] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot26] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot26] ~ ~ ~ execute @s[tag=!NetherWartInSlot26] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot26] ~ ~ ~ execute @s[tag=!BrewingStandInSlot26] ~ ~ ~ execute @s[tag=!CauldronInSlot26] ~ ~ ~ execute @s[tag=!EndPortalInSlot26] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot26] ~ ~ ~ execute @s[tag=!EndStoneInSlot26] ~ ~ ~ execute @s[tag=!DragonEggInSlot26] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot26] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot26] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot26] ~ ~ ~ execute @s[tag=!CocoaInSlot26] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot26] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot26] ~ ~ ~ execute @s[tag=!EnderChestInSlot26] ~ ~ ~ execute @s[tag=!TripwireHookInSlot26] ~ ~ ~ execute @s[tag=!TripwireInSlot26] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot26] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot26] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot26] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot26] ~ ~ ~ execute @s[tag=!CommandBlockInSlot26] ~ ~ ~ execute @s[tag=!BeaconInSlot26] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot26] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot26] ~ ~ ~ execute @s[tag=!FlowerPotInSlot26] ~ ~ ~ execute @s[tag=!CarrotsInSlot26] ~ ~ ~ execute @s[tag=!PotatoesInSlot26] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot26] ~ ~ ~ execute @s[tag=!MobHeadInSlot26] ~ ~ ~ execute @s[tag=!AnvilInSlot26] ~ ~ ~ execute @s[tag=!TrappedChestInSlot26] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot26] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot26] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot26] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot26] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot26] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot26] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot26] ~ ~ ~ execute @s[tag=!HopperInSlot26] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot26] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot26] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot26] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot26] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot26] ~ ~ ~ execute @s[tag=!DropperInSlot26] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot26] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot26] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot26] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot26] ~ ~ ~ execute @s[tag=!AcaciaWoodFacingYInSlot26] ~ ~ ~ execute @s[tag=!DarkOakWoodFacingYInSlot26] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot26] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot26] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot26] ~ ~ ~ execute @s[tag=!BarrierInSlot26] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot26] ~ ~ ~ execute @s[tag=!PrismarineInSlot26] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot26] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot26] ~ ~ ~ execute @s[tag=!SeaLanternInSlot26] ~ ~ ~ execute @s[tag=!HayBaleInSlot26] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot26] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot26] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot26] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot26] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot26] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot26] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot26] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot26] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot26] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot26] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot26] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot26] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot26] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot26] ~ ~ ~ execute @s[tag=!RedCarpetInSlot26] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot26] ~ ~ ~ execute @s[tag=!HardenedClayInSlot26] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot26] ~ ~ ~ execute @s[tag=!PackedIceInSlot26] ~ ~ ~ execute @s[tag=!SunflowerInSlot26] ~ ~ ~ execute @s[tag=!LilacInSlot26] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot26] ~ ~ ~ execute @s[tag=!LargeFernInSlot26] ~ ~ ~ execute @s[tag=!RoseBushInSlot26] ~ ~ ~ execute @s[tag=!PeonyInSlot26] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot26] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot26] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot26] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot26] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot26] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot26] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot26] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot26] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot26] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot26] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot26] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot26] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot26] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot26] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot26] ~ ~ ~ execute @s[tag=!BirchFenceInSlot26] ~ ~ ~ execute @s[tag=!JungleFenceInSlot26] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot26] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot26] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot26] ~ ~ ~ execute @s[tag=!EndRodInSlot26] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot26] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot26] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot26] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot26] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot26] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot26] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot26] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot26] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot26] ~ ~ ~ execute @s[tag=!GrassPathInSlot26] ~ ~ ~ execute @s[tag=!EndGatewayInSlot26] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot26] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot26] ~ ~ ~ execute @s[tag=!FrostedIceInSlot26] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot26] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot26] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot26] ~ ~ ~ execute @s[tag=!BoneBlockInSlot26] ~ ~ ~ execute @s[tag=!StructureVoidInSlot26] ~ ~ ~ execute @s[tag=!ObserverInSlot26] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot26] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot26] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot26] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot26] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot26] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot26] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot26] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot26] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot26] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot26] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot26] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot26] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot26] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot26] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot26] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot26] ~ ~ ~ execute @s[tag=!RedConcreteInSlot26] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot26] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot26] ~ ~ ~ execute @s[tag=!StructureBlockInSlot26] ~ ~ ~ scoreboard players tag @s add AirInSlot26 