scoreboard players tag @s add AirInSlot18 {Inventory:[{Slot:18b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot18 {Inventory:[{Slot:18b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot18 {Inventory:[{Slot:18b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot18 {Inventory:[{Slot:18b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot18 {Inventory:[{Slot:18b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot18 {Inventory:[{Slot:18b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot18 {Inventory:[{Slot:18b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot18 {Inventory:[{Slot:18b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot18 {Inventory:[{Slot:18b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot18 {Inventory:[{Slot:18b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot18 {Inventory:[{Slot:18b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot18 {Inventory:[{Slot:18b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot18 {Inventory:[{Slot:18b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot18 {Inventory:[{Slot:18b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot18 {Inventory:[{Slot:18b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot18 {Inventory:[{Slot:18b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot18 {Inventory:[{Slot:18b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot18 {Inventory:[{Slot:18b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot18 {Inventory:[{Slot:18b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot18 {Inventory:[{Slot:18b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot18 {Inventory:[{Slot:18b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot18 {Inventory:[{Slot:18b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot18 {Inventory:[{Slot:18b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot18 {Inventory:[{Slot:18b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot18 {Inventory:[{Slot:18b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot18 {Inventory:[{Slot:18b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot18 {Inventory:[{Slot:18b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot18 {Inventory:[{Slot:18b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot18 {Inventory:[{Slot:18b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot18 {Inventory:[{Slot:18b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot18 {Inventory:[{Slot:18b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot18 {Inventory:[{Slot:18b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot18 {Inventory:[{Slot:18b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot18 {Inventory:[{Slot:18b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot18 {Inventory:[{Slot:18b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot18 {Inventory:[{Slot:18b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot18 {Inventory:[{Slot:18b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot18 {Inventory:[{Slot:18b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot18 {Inventory:[{Slot:18b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot18 {Inventory:[{Slot:18b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot18 {Inventory:[{Slot:18b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot18 {Inventory:[{Slot:18b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot18 {Inventory:[{Slot:18b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot18 {Inventory:[{Slot:18b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot18 {Inventory:[{Slot:18b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot18 {Inventory:[{Slot:18b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot18 {Inventory:[{Slot:18b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot18] ~ ~ ~ execute @s[tag=!StoneInSlot18] ~ ~ ~ execute @s[tag=!GraniteInSlot18] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot18] ~ ~ ~ execute @s[tag=!DioriteInSlot18] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot18] ~ ~ ~ execute @s[tag=!AndesiteInSlot18] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot18] ~ ~ ~ execute @s[tag=!GrassBlockInSlot18] ~ ~ ~ execute @s[tag=!DirtInSlot18] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot18] ~ ~ ~ execute @s[tag=!PodzolInSlot18] ~ ~ ~ execute @s[tag=!CobblestoneInSlot18] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot18] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot18] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot18] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot18] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot18] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot18] ~ ~ ~ execute @s[tag=!OakSaplingInSlot18] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot18] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot18] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot18] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot18] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot18] ~ ~ ~ execute @s[tag=!BedrockInSlot18] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot18] ~ ~ ~ execute @s[tag=!StillWaterInSlot18] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot18] ~ ~ ~ execute @s[tag=!StillLavaInSlot18] ~ ~ ~ execute @s[tag=!SandInSlot18] ~ ~ ~ execute @s[tag=!RedSandInSlot18] ~ ~ ~ execute @s[tag=!GravelInSlot18] ~ ~ ~ execute @s[tag=!GoldOreInSlot18] ~ ~ ~ execute @s[tag=!IronOreInSlot18] ~ ~ ~ execute @s[tag=!CoalOreInSlot18] ~ ~ ~ execute @s[tag=!OakWoodInSlot18] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot18] ~ ~ ~ execute @s[tag=!BirchWoodInSlot18] ~ ~ ~ execute @s[tag=!JungleWoodInSlot18] ~ ~ ~ execute @s[tag=!OakLeavesInSlot18] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot18] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot18] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot18] ~ ~ ~ execute @s[tag=!SpongeInSlot18] ~ ~ ~ execute @s[tag=!WetSpongeInSlot18] ~ ~ ~ execute @s[tag=!GlassInSlot18] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot18] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot18] ~ ~ ~ execute @s[tag=!DispenserInSlot18] ~ ~ ~ execute @s[tag=!SandstoneInSlot18] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot18] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot18] ~ ~ ~ execute @s[tag=!NoteBlockInSlot18] ~ ~ ~ execute @s[tag=!BedInSlot18] ~ ~ ~ execute @s[tag=!PoweredRailInSlot18] ~ ~ ~ execute @s[tag=!DetectorRailInSlot18] ~ ~ ~ execute @s[tag=!StickyPistonInSlot18] ~ ~ ~ execute @s[tag=!CobwebInSlot18] ~ ~ ~ execute @s[tag=!DeadShrubInSlot18] ~ ~ ~ execute @s[tag=!GrassInSlot18] ~ ~ ~ execute @s[tag=!FernInSlot18] ~ ~ ~ execute @s[tag=!DeadBushInSlot18] ~ ~ ~ execute @s[tag=!PistonInSlot18] ~ ~ ~ execute @s[tag=!PistonHeadInSlot18] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot18] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot18] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot18] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot18] ~ ~ ~ execute @s[tag=!YellowWoolInSlot18] ~ ~ ~ execute @s[tag=!LimeWoolInSlot18] ~ ~ ~ execute @s[tag=!PinkWoolInSlot18] ~ ~ ~ execute @s[tag=!GrayWoolInSlot18] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot18] ~ ~ ~ execute @s[tag=!CyanWoolInSlot18] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot18] ~ ~ ~ execute @s[tag=!BlueWoolInSlot18] ~ ~ ~ execute @s[tag=!BrownWoolInSlot18] ~ ~ ~ execute @s[tag=!GreenWoolInSlot18] ~ ~ ~ execute @s[tag=!RedWoolInSlot18] ~ ~ ~ execute @s[tag=!BlackWoolInSlot18] ~ ~ ~ execute @s[tag=!DandelionInSlot18] ~ ~ ~ execute @s[tag=!PoppyInSlot18] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot18] ~ ~ ~ execute @s[tag=!AlliumInSlot18] ~ ~ ~ execute @s[tag=!AzureBluetInSlot18] ~ ~ ~ execute @s[tag=!RedTulipInSlot18] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot18] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot18] ~ ~ ~ execute @s[tag=!PinkTulipInSlot18] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot18] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot18] ~ ~ ~ execute @s[tag=!RedMushroomInSlot18] ~ ~ ~ execute @s[tag=!GoldBlockInSlot18] ~ ~ ~ execute @s[tag=!IronBlockInSlot18] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot18] ~ ~ ~ execute @s[tag=!StoneSlabInSlot18] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot18] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot18] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot18] ~ ~ ~ execute @s[tag=!BrickSlabInSlot18] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot18] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot18] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot18] ~ ~ ~ execute @s[tag=!BricksInSlot18] ~ ~ ~ execute @s[tag=!TNTInSlot18] ~ ~ ~ execute @s[tag=!BookshelfInSlot18] ~ ~ ~ execute @s[tag=!MossStoneInSlot18] ~ ~ ~ execute @s[tag=!ObsidianInSlot18] ~ ~ ~ execute @s[tag=!TorchInSlot18] ~ ~ ~ execute @s[tag=!FireInSlot18] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot18] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot18] ~ ~ ~ execute @s[tag=!ChestInSlot18] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot18] ~ ~ ~ execute @s[tag=!DiamondOreInSlot18] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot18] ~ ~ ~ execute @s[tag=!CraftingTableInSlot18] ~ ~ ~ execute @s[tag=!WheatCropsInSlot18] ~ ~ ~ execute @s[tag=!FarmlandInSlot18] ~ ~ ~ execute @s[tag=!FurnaceInSlot18] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot18] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot18] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!LadderInSlot18] ~ ~ ~ execute @s[tag=!RailInSlot18] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot18] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot18] ~ ~ ~ execute @s[tag=!LeverInSlot18] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot18] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot18] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot18] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot18] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot18] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot18] ~ ~ ~ execute @s[tag=!StoneButtonInSlot18] ~ ~ ~ execute @s[tag=!SnowInSlot18] ~ ~ ~ execute @s[tag=!IceInSlot18] ~ ~ ~ execute @s[tag=!SnowBlockInSlot18] ~ ~ ~ execute @s[tag=!CactusInSlot18] ~ ~ ~ execute @s[tag=!SugarCanesInSlot18] ~ ~ ~ execute @s[tag=!JukeboxInSlot18] ~ ~ ~ execute @s[tag=!OakFenceInSlot18] ~ ~ ~ execute @s[tag=!PumpkinInSlot18] ~ ~ ~ execute @s[tag=!NetherrackInSlot18] ~ ~ ~ execute @s[tag=!SoulSandInSlot18] ~ ~ ~ execute @s[tag=!GlowstoneInSlot18] ~ ~ ~ execute @s[tag=!NetherPortalInSlot18] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot18] ~ ~ ~ execute @s[tag=!CakeBlockInSlot18] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot18] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot18] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot18] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot18] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot18] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot18] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot18] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot18] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot18] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot18] ~ ~ ~ execute @s[tag=!StoneBricksInSlot18] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot18] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot18] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot18] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot18] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot18] ~ ~ ~ execute @s[tag=!IronBarsInSlot18] ~ ~ ~ execute @s[tag=!GlassPaneInSlot18] ~ ~ ~ execute @s[tag=!MelonBlockInSlot18] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot18] ~ ~ ~ execute @s[tag=!MelonStemInSlot18] ~ ~ ~ execute @s[tag=!VinesInSlot18] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot18] ~ ~ ~ execute @s[tag=!BrickStairsInSlot18] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot18] ~ ~ ~ execute @s[tag=!MyceliumInSlot18] ~ ~ ~ execute @s[tag=!LilyPadInSlot18] ~ ~ ~ execute @s[tag=!NetherBrickInSlot18] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot18] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot18] ~ ~ ~ execute @s[tag=!NetherWartInSlot18] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot18] ~ ~ ~ execute @s[tag=!BrewingStandInSlot18] ~ ~ ~ execute @s[tag=!CauldronInSlot18] ~ ~ ~ execute @s[tag=!EndPortalInSlot18] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot18] ~ ~ ~ execute @s[tag=!EndStoneInSlot18] ~ ~ ~ execute @s[tag=!DragonEggInSlot18] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot18] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot18] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot18] ~ ~ ~ execute @s[tag=!CocoaInSlot18] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot18] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot18] ~ ~ ~ execute @s[tag=!EnderChestInSlot18] ~ ~ ~ execute @s[tag=!TripwireHookInSlot18] ~ ~ ~ execute @s[tag=!TripwireInSlot18] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot18] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot18] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot18] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot18] ~ ~ ~ execute @s[tag=!CommandBlockInSlot18] ~ ~ ~ execute @s[tag=!BeaconInSlot18] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot18] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot18] ~ ~ ~ execute @s[tag=!FlowerPotInSlot18] ~ ~ ~ execute @s[tag=!CarrotsInSlot18] ~ ~ ~ execute @s[tag=!PotatoesInSlot18] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot18] ~ ~ ~ execute @s[tag=!MobHeadInSlot18] ~ ~ ~ execute @s[tag=!AnvilInSlot18] ~ ~ ~ execute @s[tag=!TrappedChestInSlot18] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot18] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot18] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot18] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot18] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot18] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot18] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot18] ~ ~ ~ execute @s[tag=!HopperInSlot18] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot18] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot18] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot18] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot18] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot18] ~ ~ ~ execute @s[tag=!DropperInSlot18] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot18] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot18] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot18] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot18] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot18] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot18] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot18] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot18] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot18] ~ ~ ~ execute @s[tag=!BarrierInSlot18] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot18] ~ ~ ~ execute @s[tag=!PrismarineInSlot18] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot18] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot18] ~ ~ ~ execute @s[tag=!SeaLanternInSlot18] ~ ~ ~ execute @s[tag=!HayBaleInSlot18] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot18] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot18] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot18] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot18] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot18] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot18] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot18] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot18] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot18] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot18] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot18] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot18] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot18] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot18] ~ ~ ~ execute @s[tag=!RedCarpetInSlot18] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot18] ~ ~ ~ execute @s[tag=!HardenedClayInSlot18] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot18] ~ ~ ~ execute @s[tag=!PackedIceInSlot18] ~ ~ ~ execute @s[tag=!SunflowerInSlot18] ~ ~ ~ execute @s[tag=!LilacInSlot18] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot18] ~ ~ ~ execute @s[tag=!LargeFernInSlot18] ~ ~ ~ execute @s[tag=!RoseBushInSlot18] ~ ~ ~ execute @s[tag=!PeonyInSlot18] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot18] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot18] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot18] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot18] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot18] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot18] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot18] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot18] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot18] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot18] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot18] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot18] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot18] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot18] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot18] ~ ~ ~ execute @s[tag=!BirchFenceInSlot18] ~ ~ ~ execute @s[tag=!JungleFenceInSlot18] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot18] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot18] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot18] ~ ~ ~ execute @s[tag=!EndRodInSlot18] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot18] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot18] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot18] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot18] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot18] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot18] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot18] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot18] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot18] ~ ~ ~ execute @s[tag=!GrassPathInSlot18] ~ ~ ~ execute @s[tag=!EndGatewayInSlot18] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot18] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot18] ~ ~ ~ execute @s[tag=!FrostedIceInSlot18] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot18] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot18] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot18] ~ ~ ~ execute @s[tag=!BoneBlockInSlot18] ~ ~ ~ execute @s[tag=!StructureVoidInSlot18] ~ ~ ~ execute @s[tag=!ObserverInSlot18] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot18] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot18] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot18] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot18] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot18] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot18] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot18] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot18] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot18] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot18] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot18] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot18] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot18] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot18] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot18] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot18] ~ ~ ~ execute @s[tag=!RedConcreteInSlot18] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot18] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot18] ~ ~ ~ execute @s[tag=!StructureBlockInSlot18] ~ ~ ~ scoreboard players tag @s add AirInSlot18 