scoreboard players tag @s add AirInSlot1 {Inventory:[{Slot:1b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot1 {Inventory:[{Slot:1b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot1 {Inventory:[{Slot:1b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot1 {Inventory:[{Slot:1b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot1 {Inventory:[{Slot:1b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot1 {Inventory:[{Slot:1b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot1 {Inventory:[{Slot:1b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot1 {Inventory:[{Slot:1b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot1 {Inventory:[{Slot:1b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot1 {Inventory:[{Slot:1b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot1 {Inventory:[{Slot:1b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot1 {Inventory:[{Slot:1b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot1 {Inventory:[{Slot:1b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot1 {Inventory:[{Slot:1b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot1 {Inventory:[{Slot:1b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot1 {Inventory:[{Slot:1b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot1 {Inventory:[{Slot:1b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot1 {Inventory:[{Slot:1b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot1 {Inventory:[{Slot:1b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot1 {Inventory:[{Slot:1b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot1 {Inventory:[{Slot:1b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot1 {Inventory:[{Slot:1b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot1 {Inventory:[{Slot:1b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot1 {Inventory:[{Slot:1b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot1 {Inventory:[{Slot:1b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot1 {Inventory:[{Slot:1b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot1 {Inventory:[{Slot:1b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot1 {Inventory:[{Slot:1b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot1 {Inventory:[{Slot:1b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot1 {Inventory:[{Slot:1b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot1 {Inventory:[{Slot:1b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot1 {Inventory:[{Slot:1b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot1 {Inventory:[{Slot:1b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot1 {Inventory:[{Slot:1b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot1 {Inventory:[{Slot:1b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot1 {Inventory:[{Slot:1b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot1 {Inventory:[{Slot:1b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot1 {Inventory:[{Slot:1b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot1 {Inventory:[{Slot:1b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot1 {Inventory:[{Slot:1b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot1 {Inventory:[{Slot:1b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot1 {Inventory:[{Slot:1b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot1 {Inventory:[{Slot:1b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot1 {Inventory:[{Slot:1b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot1 {Inventory:[{Slot:1b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot1 {Inventory:[{Slot:1b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot1 {Inventory:[{Slot:1b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot1 {Inventory:[{Slot:1b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot1 {Inventory:[{Slot:1b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot1 {Inventory:[{Slot:1b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot1 {Inventory:[{Slot:1b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot1 {Inventory:[{Slot:1b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot1 {Inventory:[{Slot:1b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot1 {Inventory:[{Slot:1b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot1 {Inventory:[{Slot:1b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot1 {Inventory:[{Slot:1b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot1 {Inventory:[{Slot:1b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot1 {Inventory:[{Slot:1b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot1 {Inventory:[{Slot:1b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot1 {Inventory:[{Slot:1b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot1 {Inventory:[{Slot:1b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot1 {Inventory:[{Slot:1b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot1 {Inventory:[{Slot:1b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot1 {Inventory:[{Slot:1b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot1 {Inventory:[{Slot:1b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot1 {Inventory:[{Slot:1b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot1 {Inventory:[{Slot:1b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot1 {Inventory:[{Slot:1b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot1 {Inventory:[{Slot:1b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot1 {Inventory:[{Slot:1b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot1 {Inventory:[{Slot:1b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot1 {Inventory:[{Slot:1b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot1 {Inventory:[{Slot:1b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot1 {Inventory:[{Slot:1b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot1 {Inventory:[{Slot:1b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot1 {Inventory:[{Slot:1b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot1 {Inventory:[{Slot:1b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot1 {Inventory:[{Slot:1b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot1 {Inventory:[{Slot:1b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot1 {Inventory:[{Slot:1b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot1 {Inventory:[{Slot:1b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot1 {Inventory:[{Slot:1b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot1 {Inventory:[{Slot:1b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot1 {Inventory:[{Slot:1b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot1 {Inventory:[{Slot:1b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot1] ~ ~ ~ execute @s[tag=!StoneInSlot1] ~ ~ ~ execute @s[tag=!GraniteInSlot1] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot1] ~ ~ ~ execute @s[tag=!DioriteInSlot1] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot1] ~ ~ ~ execute @s[tag=!AndesiteInSlot1] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot1] ~ ~ ~ execute @s[tag=!GrassBlockInSlot1] ~ ~ ~ execute @s[tag=!DirtInSlot1] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot1] ~ ~ ~ execute @s[tag=!PodzolInSlot1] ~ ~ ~ execute @s[tag=!CobblestoneInSlot1] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot1] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot1] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot1] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot1] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot1] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot1] ~ ~ ~ execute @s[tag=!OakSaplingInSlot1] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot1] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot1] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot1] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot1] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot1] ~ ~ ~ execute @s[tag=!BedrockInSlot1] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot1] ~ ~ ~ execute @s[tag=!StillWaterInSlot1] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot1] ~ ~ ~ execute @s[tag=!StillLavaInSlot1] ~ ~ ~ execute @s[tag=!SandInSlot1] ~ ~ ~ execute @s[tag=!RedSandInSlot1] ~ ~ ~ execute @s[tag=!GravelInSlot1] ~ ~ ~ execute @s[tag=!GoldOreInSlot1] ~ ~ ~ execute @s[tag=!IronOreInSlot1] ~ ~ ~ execute @s[tag=!CoalOreInSlot1] ~ ~ ~ execute @s[tag=!OakWoodInSlot1] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot1] ~ ~ ~ execute @s[tag=!BirchWoodInSlot1] ~ ~ ~ execute @s[tag=!JungleWoodInSlot1] ~ ~ ~ execute @s[tag=!OakLeavesInSlot1] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot1] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot1] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot1] ~ ~ ~ execute @s[tag=!SpongeInSlot1] ~ ~ ~ execute @s[tag=!WetSpongeInSlot1] ~ ~ ~ execute @s[tag=!GlassInSlot1] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot1] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot1] ~ ~ ~ execute @s[tag=!DispenserInSlot1] ~ ~ ~ execute @s[tag=!SandstoneInSlot1] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot1] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot1] ~ ~ ~ execute @s[tag=!NoteBlockInSlot1] ~ ~ ~ execute @s[tag=!BedInSlot1] ~ ~ ~ execute @s[tag=!PoweredRailInSlot1] ~ ~ ~ execute @s[tag=!DetectorRailInSlot1] ~ ~ ~ execute @s[tag=!StickyPistonInSlot1] ~ ~ ~ execute @s[tag=!CobwebInSlot1] ~ ~ ~ execute @s[tag=!DeadShrubInSlot1] ~ ~ ~ execute @s[tag=!GrassInSlot1] ~ ~ ~ execute @s[tag=!FernInSlot1] ~ ~ ~ execute @s[tag=!DeadBushInSlot1] ~ ~ ~ execute @s[tag=!PistonInSlot1] ~ ~ ~ execute @s[tag=!PistonHeadInSlot1] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot1] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot1] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot1] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot1] ~ ~ ~ execute @s[tag=!YellowWoolInSlot1] ~ ~ ~ execute @s[tag=!LimeWoolInSlot1] ~ ~ ~ execute @s[tag=!PinkWoolInSlot1] ~ ~ ~ execute @s[tag=!GrayWoolInSlot1] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot1] ~ ~ ~ execute @s[tag=!CyanWoolInSlot1] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot1] ~ ~ ~ execute @s[tag=!BlueWoolInSlot1] ~ ~ ~ execute @s[tag=!BrownWoolInSlot1] ~ ~ ~ execute @s[tag=!GreenWoolInSlot1] ~ ~ ~ execute @s[tag=!RedWoolInSlot1] ~ ~ ~ execute @s[tag=!BlackWoolInSlot1] ~ ~ ~ execute @s[tag=!DandelionInSlot1] ~ ~ ~ execute @s[tag=!PoppyInSlot1] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot1] ~ ~ ~ execute @s[tag=!AlliumInSlot1] ~ ~ ~ execute @s[tag=!AzureBluetInSlot1] ~ ~ ~ execute @s[tag=!RedTulipInSlot1] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot1] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot1] ~ ~ ~ execute @s[tag=!PinkTulipInSlot1] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot1] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot1] ~ ~ ~ execute @s[tag=!RedMushroomInSlot1] ~ ~ ~ execute @s[tag=!GoldBlockInSlot1] ~ ~ ~ execute @s[tag=!IronBlockInSlot1] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot1] ~ ~ ~ execute @s[tag=!StoneSlabInSlot1] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot1] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot1] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot1] ~ ~ ~ execute @s[tag=!BrickSlabInSlot1] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot1] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot1] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot1] ~ ~ ~ execute @s[tag=!BricksInSlot1] ~ ~ ~ execute @s[tag=!TNTInSlot1] ~ ~ ~ execute @s[tag=!BookshelfInSlot1] ~ ~ ~ execute @s[tag=!MossStoneInSlot1] ~ ~ ~ execute @s[tag=!ObsidianInSlot1] ~ ~ ~ execute @s[tag=!TorchInSlot1] ~ ~ ~ execute @s[tag=!FireInSlot1] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot1] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot1] ~ ~ ~ execute @s[tag=!ChestInSlot1] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot1] ~ ~ ~ execute @s[tag=!DiamondOreInSlot1] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot1] ~ ~ ~ execute @s[tag=!CraftingTableInSlot1] ~ ~ ~ execute @s[tag=!WheatCropsInSlot1] ~ ~ ~ execute @s[tag=!FarmlandInSlot1] ~ ~ ~ execute @s[tag=!FurnaceInSlot1] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot1] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot1] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!LadderInSlot1] ~ ~ ~ execute @s[tag=!RailInSlot1] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot1] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot1] ~ ~ ~ execute @s[tag=!LeverInSlot1] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot1] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot1] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot1] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot1] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot1] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot1] ~ ~ ~ execute @s[tag=!StoneButtonInSlot1] ~ ~ ~ execute @s[tag=!SnowInSlot1] ~ ~ ~ execute @s[tag=!IceInSlot1] ~ ~ ~ execute @s[tag=!SnowBlockInSlot1] ~ ~ ~ execute @s[tag=!CactusInSlot1] ~ ~ ~ execute @s[tag=!SugarCanesInSlot1] ~ ~ ~ execute @s[tag=!JukeboxInSlot1] ~ ~ ~ execute @s[tag=!OakFenceInSlot1] ~ ~ ~ execute @s[tag=!PumpkinInSlot1] ~ ~ ~ execute @s[tag=!NetherrackInSlot1] ~ ~ ~ execute @s[tag=!SoulSandInSlot1] ~ ~ ~ execute @s[tag=!GlowstoneInSlot1] ~ ~ ~ execute @s[tag=!NetherPortalInSlot1] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot1] ~ ~ ~ execute @s[tag=!CakeBlockInSlot1] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot1] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot1] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot1] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot1] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot1] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot1] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot1] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot1] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot1] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot1] ~ ~ ~ execute @s[tag=!StoneBricksInSlot1] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot1] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot1] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot1] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot1] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot1] ~ ~ ~ execute @s[tag=!IronBarsInSlot1] ~ ~ ~ execute @s[tag=!GlassPaneInSlot1] ~ ~ ~ execute @s[tag=!MelonBlockInSlot1] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot1] ~ ~ ~ execute @s[tag=!MelonStemInSlot1] ~ ~ ~ execute @s[tag=!VinesInSlot1] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot1] ~ ~ ~ execute @s[tag=!BrickStairsInSlot1] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot1] ~ ~ ~ execute @s[tag=!MyceliumInSlot1] ~ ~ ~ execute @s[tag=!LilyPadInSlot1] ~ ~ ~ execute @s[tag=!NetherBrickInSlot1] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot1] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot1] ~ ~ ~ execute @s[tag=!NetherWartInSlot1] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot1] ~ ~ ~ execute @s[tag=!BrewingStandInSlot1] ~ ~ ~ execute @s[tag=!CauldronInSlot1] ~ ~ ~ execute @s[tag=!EndPortalInSlot1] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot1] ~ ~ ~ execute @s[tag=!EndStoneInSlot1] ~ ~ ~ execute @s[tag=!DragonEggInSlot1] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot1] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot1] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot1] ~ ~ ~ execute @s[tag=!CocoaInSlot1] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot1] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot1] ~ ~ ~ execute @s[tag=!EnderChestInSlot1] ~ ~ ~ execute @s[tag=!TripwireHookInSlot1] ~ ~ ~ execute @s[tag=!TripwireInSlot1] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot1] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot1] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot1] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot1] ~ ~ ~ execute @s[tag=!CommandBlockInSlot1] ~ ~ ~ execute @s[tag=!BeaconInSlot1] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot1] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot1] ~ ~ ~ execute @s[tag=!FlowerPotInSlot1] ~ ~ ~ execute @s[tag=!CarrotsInSlot1] ~ ~ ~ execute @s[tag=!PotatoesInSlot1] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot1] ~ ~ ~ execute @s[tag=!MobHeadInSlot1] ~ ~ ~ execute @s[tag=!AnvilInSlot1] ~ ~ ~ execute @s[tag=!TrappedChestInSlot1] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot1] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot1] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot1] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot1] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot1] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot1] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot1] ~ ~ ~ execute @s[tag=!HopperInSlot1] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot1] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot1] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot1] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot1] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot1] ~ ~ ~ execute @s[tag=!DropperInSlot1] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot1] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot1] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot1] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot1] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot1] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot1] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot1] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot1] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot1] ~ ~ ~ execute @s[tag=!BarrierInSlot1] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot1] ~ ~ ~ execute @s[tag=!PrismarineInSlot1] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot1] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot1] ~ ~ ~ execute @s[tag=!SeaLanternInSlot1] ~ ~ ~ execute @s[tag=!HayBaleInSlot1] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot1] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot1] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot1] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot1] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot1] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot1] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot1] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot1] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot1] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot1] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot1] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot1] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot1] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot1] ~ ~ ~ execute @s[tag=!RedCarpetInSlot1] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot1] ~ ~ ~ execute @s[tag=!HardenedClayInSlot1] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot1] ~ ~ ~ execute @s[tag=!PackedIceInSlot1] ~ ~ ~ execute @s[tag=!SunflowerInSlot1] ~ ~ ~ execute @s[tag=!LilacInSlot1] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot1] ~ ~ ~ execute @s[tag=!LargeFernInSlot1] ~ ~ ~ execute @s[tag=!RoseBushInSlot1] ~ ~ ~ execute @s[tag=!PeonyInSlot1] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot1] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot1] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot1] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot1] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot1] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot1] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot1] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot1] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot1] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot1] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot1] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot1] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot1] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot1] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot1] ~ ~ ~ execute @s[tag=!BirchFenceInSlot1] ~ ~ ~ execute @s[tag=!JungleFenceInSlot1] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot1] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot1] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot1] ~ ~ ~ execute @s[tag=!EndRodInSlot1] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot1] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot1] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot1] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot1] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot1] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot1] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot1] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot1] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot1] ~ ~ ~ execute @s[tag=!GrassPathInSlot1] ~ ~ ~ execute @s[tag=!EndGatewayInSlot1] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot1] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot1] ~ ~ ~ execute @s[tag=!FrostedIceInSlot1] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot1] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot1] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot1] ~ ~ ~ execute @s[tag=!BoneBlockInSlot1] ~ ~ ~ execute @s[tag=!StructureVoidInSlot1] ~ ~ ~ execute @s[tag=!ObserverInSlot1] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot1] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot1] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot1] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot1] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot1] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot1] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot1] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot1] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot1] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot1] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot1] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot1] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot1] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot1] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot1] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot1] ~ ~ ~ execute @s[tag=!RedConcreteInSlot1] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot1] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot1] ~ ~ ~ execute @s[tag=!StructureBlockInSlot1] ~ ~ ~ scoreboard players tag @s add AirInSlot1 