scoreboard players tag @a add AirInSlot6 {Inventory:[{Slot:6b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot6 {Inventory:[{Slot:6b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot6 {Inventory:[{Slot:6b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot6 {Inventory:[{Slot:6b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot6 {Inventory:[{Slot:6b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot6 {Inventory:[{Slot:6b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot6 {Inventory:[{Slot:6b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot6 {Inventory:[{Slot:6b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot6 {Inventory:[{Slot:6b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot6 {Inventory:[{Slot:6b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot6 {Inventory:[{Slot:6b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot6 {Inventory:[{Slot:6b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot6 {Inventory:[{Slot:6b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot6 {Inventory:[{Slot:6b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot6 {Inventory:[{Slot:6b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot6 {Inventory:[{Slot:6b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot6 {Inventory:[{Slot:6b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot6 {Inventory:[{Slot:6b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot6 {Inventory:[{Slot:6b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot6 {Inventory:[{Slot:6b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot6 {Inventory:[{Slot:6b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot6 {Inventory:[{Slot:6b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot6 {Inventory:[{Slot:6b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot6 {Inventory:[{Slot:6b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot6 {Inventory:[{Slot:6b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot6 {Inventory:[{Slot:6b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot6 {Inventory:[{Slot:6b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot6 {Inventory:[{Slot:6b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot6 {Inventory:[{Slot:6b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot6 {Inventory:[{Slot:6b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot6 {Inventory:[{Slot:6b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot6 {Inventory:[{Slot:6b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot6 {Inventory:[{Slot:6b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot6 {Inventory:[{Slot:6b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot6 {Inventory:[{Slot:6b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot6 {Inventory:[{Slot:6b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot6 {Inventory:[{Slot:6b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot6 {Inventory:[{Slot:6b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot6 {Inventory:[{Slot:6b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot6 {Inventory:[{Slot:6b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot6 {Inventory:[{Slot:6b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot6 {Inventory:[{Slot:6b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot6 {Inventory:[{Slot:6b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot6 {Inventory:[{Slot:6b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot6 {Inventory:[{Slot:6b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot6 {Inventory:[{Slot:6b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot6 {Inventory:[{Slot:6b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot6 {Inventory:[{Slot:6b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot6 {Inventory:[{Slot:6b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot6 {Inventory:[{Slot:6b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot6 {Inventory:[{Slot:6b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot6 {Inventory:[{Slot:6b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot6 {Inventory:[{Slot:6b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot6 {Inventory:[{Slot:6b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot6 {Inventory:[{Slot:6b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot6 {Inventory:[{Slot:6b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot6 {Inventory:[{Slot:6b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot6 {Inventory:[{Slot:6b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot6 {Inventory:[{Slot:6b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot6 {Inventory:[{Slot:6b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot6 {Inventory:[{Slot:6b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot6 {Inventory:[{Slot:6b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot6 {Inventory:[{Slot:6b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot6 {Inventory:[{Slot:6b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot6 {Inventory:[{Slot:6b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot6 {Inventory:[{Slot:6b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot6 {Inventory:[{Slot:6b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot6 {Inventory:[{Slot:6b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot6 {Inventory:[{Slot:6b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot6 {Inventory:[{Slot:6b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot6 {Inventory:[{Slot:6b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot6 {Inventory:[{Slot:6b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot6 {Inventory:[{Slot:6b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot6 {Inventory:[{Slot:6b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot6 {Inventory:[{Slot:6b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot6 {Inventory:[{Slot:6b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot6 {Inventory:[{Slot:6b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot6 {Inventory:[{Slot:6b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot6 {Inventory:[{Slot:6b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot6 {Inventory:[{Slot:6b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot6 {Inventory:[{Slot:6b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot6 {Inventory:[{Slot:6b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot6 {Inventory:[{Slot:6b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot6 {Inventory:[{Slot:6b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot6 {Inventory:[{Slot:6b,id:"minecraft:structure_block",Damage:0s}]}
