scoreboard players tag @s add AirInSlot15 {Inventory:[{Slot:15b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot15 {Inventory:[{Slot:15b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot15 {Inventory:[{Slot:15b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot15 {Inventory:[{Slot:15b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot15 {Inventory:[{Slot:15b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot15 {Inventory:[{Slot:15b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot15 {Inventory:[{Slot:15b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot15 {Inventory:[{Slot:15b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot15 {Inventory:[{Slot:15b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot15 {Inventory:[{Slot:15b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot15 {Inventory:[{Slot:15b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot15 {Inventory:[{Slot:15b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot15 {Inventory:[{Slot:15b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot15 {Inventory:[{Slot:15b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot15 {Inventory:[{Slot:15b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot15 {Inventory:[{Slot:15b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot15 {Inventory:[{Slot:15b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot15 {Inventory:[{Slot:15b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot15 {Inventory:[{Slot:15b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot15 {Inventory:[{Slot:15b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot15 {Inventory:[{Slot:15b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot15 {Inventory:[{Slot:15b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot15 {Inventory:[{Slot:15b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot15 {Inventory:[{Slot:15b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot15 {Inventory:[{Slot:15b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot15 {Inventory:[{Slot:15b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot15 {Inventory:[{Slot:15b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot15 {Inventory:[{Slot:15b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot15 {Inventory:[{Slot:15b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot15 {Inventory:[{Slot:15b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot15 {Inventory:[{Slot:15b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot15 {Inventory:[{Slot:15b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot15 {Inventory:[{Slot:15b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot15 {Inventory:[{Slot:15b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot15 {Inventory:[{Slot:15b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot15 {Inventory:[{Slot:15b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot15 {Inventory:[{Slot:15b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot15 {Inventory:[{Slot:15b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot15 {Inventory:[{Slot:15b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot15 {Inventory:[{Slot:15b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot15 {Inventory:[{Slot:15b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot15 {Inventory:[{Slot:15b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot15 {Inventory:[{Slot:15b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot15 {Inventory:[{Slot:15b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot15 {Inventory:[{Slot:15b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot15 {Inventory:[{Slot:15b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot15 {Inventory:[{Slot:15b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot15 {Inventory:[{Slot:15b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot15 {Inventory:[{Slot:15b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot15 {Inventory:[{Slot:15b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot15 {Inventory:[{Slot:15b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot15 {Inventory:[{Slot:15b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot15 {Inventory:[{Slot:15b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot15 {Inventory:[{Slot:15b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot15 {Inventory:[{Slot:15b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot15 {Inventory:[{Slot:15b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot15 {Inventory:[{Slot:15b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot15 {Inventory:[{Slot:15b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot15 {Inventory:[{Slot:15b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot15 {Inventory:[{Slot:15b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot15 {Inventory:[{Slot:15b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot15 {Inventory:[{Slot:15b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot15 {Inventory:[{Slot:15b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot15 {Inventory:[{Slot:15b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot15 {Inventory:[{Slot:15b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot15 {Inventory:[{Slot:15b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot15 {Inventory:[{Slot:15b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot15 {Inventory:[{Slot:15b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot15 {Inventory:[{Slot:15b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot15 {Inventory:[{Slot:15b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot15 {Inventory:[{Slot:15b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot15 {Inventory:[{Slot:15b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot15 {Inventory:[{Slot:15b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot15 {Inventory:[{Slot:15b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot15 {Inventory:[{Slot:15b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot15 {Inventory:[{Slot:15b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot15 {Inventory:[{Slot:15b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot15 {Inventory:[{Slot:15b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot15 {Inventory:[{Slot:15b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot15 {Inventory:[{Slot:15b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot15 {Inventory:[{Slot:15b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot15 {Inventory:[{Slot:15b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot15 {Inventory:[{Slot:15b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot15 {Inventory:[{Slot:15b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot15 {Inventory:[{Slot:15b,id:"minecraft:structure_block",Damage:0s}]}
