scoreboard players tag @s add AirInSlot3 {Inventory:[{Slot:3b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot3 {Inventory:[{Slot:3b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot3 {Inventory:[{Slot:3b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot3 {Inventory:[{Slot:3b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot3 {Inventory:[{Slot:3b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot3 {Inventory:[{Slot:3b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot3 {Inventory:[{Slot:3b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot3 {Inventory:[{Slot:3b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot3 {Inventory:[{Slot:3b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot3 {Inventory:[{Slot:3b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot3 {Inventory:[{Slot:3b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot3 {Inventory:[{Slot:3b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot3 {Inventory:[{Slot:3b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot3 {Inventory:[{Slot:3b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot3 {Inventory:[{Slot:3b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot3 {Inventory:[{Slot:3b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot3 {Inventory:[{Slot:3b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot3 {Inventory:[{Slot:3b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot3 {Inventory:[{Slot:3b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot3 {Inventory:[{Slot:3b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot3 {Inventory:[{Slot:3b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot3 {Inventory:[{Slot:3b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot3 {Inventory:[{Slot:3b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot3 {Inventory:[{Slot:3b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot3 {Inventory:[{Slot:3b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot3 {Inventory:[{Slot:3b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot3 {Inventory:[{Slot:3b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot3 {Inventory:[{Slot:3b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot3 {Inventory:[{Slot:3b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot3 {Inventory:[{Slot:3b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot3 {Inventory:[{Slot:3b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot3 {Inventory:[{Slot:3b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot3 {Inventory:[{Slot:3b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:structure_block",Damage:0s}]}
