scoreboard players tag @s add AirInSlot30 {Inventory:[{Slot:30b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot30 {Inventory:[{Slot:30b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot30 {Inventory:[{Slot:30b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot30 {Inventory:[{Slot:30b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot30 {Inventory:[{Slot:30b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot30 {Inventory:[{Slot:30b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot30 {Inventory:[{Slot:30b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot30 {Inventory:[{Slot:30b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot30 {Inventory:[{Slot:30b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot30 {Inventory:[{Slot:30b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot30 {Inventory:[{Slot:30b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot30 {Inventory:[{Slot:30b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot30 {Inventory:[{Slot:30b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot30 {Inventory:[{Slot:30b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot30 {Inventory:[{Slot:30b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot30 {Inventory:[{Slot:30b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot30 {Inventory:[{Slot:30b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot30 {Inventory:[{Slot:30b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot30 {Inventory:[{Slot:30b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot30 {Inventory:[{Slot:30b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot30 {Inventory:[{Slot:30b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot30 {Inventory:[{Slot:30b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot30 {Inventory:[{Slot:30b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot30 {Inventory:[{Slot:30b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot30 {Inventory:[{Slot:30b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot30 {Inventory:[{Slot:30b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot30 {Inventory:[{Slot:30b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot30 {Inventory:[{Slot:30b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot30 {Inventory:[{Slot:30b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot30 {Inventory:[{Slot:30b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot30 {Inventory:[{Slot:30b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot30 {Inventory:[{Slot:30b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot30 {Inventory:[{Slot:30b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot30 {Inventory:[{Slot:30b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot30 {Inventory:[{Slot:30b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot30 {Inventory:[{Slot:30b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot30 {Inventory:[{Slot:30b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot30 {Inventory:[{Slot:30b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot30 {Inventory:[{Slot:30b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot30 {Inventory:[{Slot:30b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot30 {Inventory:[{Slot:30b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot30 {Inventory:[{Slot:30b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot30 {Inventory:[{Slot:30b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot30 {Inventory:[{Slot:30b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot30 {Inventory:[{Slot:30b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot30 {Inventory:[{Slot:30b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot30 {Inventory:[{Slot:30b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot30 {Inventory:[{Slot:30b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot30 {Inventory:[{Slot:30b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot30 {Inventory:[{Slot:30b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot30 {Inventory:[{Slot:30b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot30 {Inventory:[{Slot:30b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot30 {Inventory:[{Slot:30b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot30 {Inventory:[{Slot:30b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot30 {Inventory:[{Slot:30b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot30 {Inventory:[{Slot:30b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot30 {Inventory:[{Slot:30b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot30 {Inventory:[{Slot:30b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot30 {Inventory:[{Slot:30b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot30 {Inventory:[{Slot:30b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot30 {Inventory:[{Slot:30b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot30 {Inventory:[{Slot:30b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot30 {Inventory:[{Slot:30b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot30 {Inventory:[{Slot:30b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot30 {Inventory:[{Slot:30b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot30 {Inventory:[{Slot:30b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot30 {Inventory:[{Slot:30b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot30 {Inventory:[{Slot:30b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot30 {Inventory:[{Slot:30b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot30 {Inventory:[{Slot:30b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot30 {Inventory:[{Slot:30b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot30 {Inventory:[{Slot:30b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot30 {Inventory:[{Slot:30b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot30 {Inventory:[{Slot:30b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot30 {Inventory:[{Slot:30b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot30 {Inventory:[{Slot:30b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot30 {Inventory:[{Slot:30b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot30 {Inventory:[{Slot:30b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot30 {Inventory:[{Slot:30b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot30 {Inventory:[{Slot:30b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot30 {Inventory:[{Slot:30b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot30 {Inventory:[{Slot:30b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot30 {Inventory:[{Slot:30b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot30 {Inventory:[{Slot:30b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot30 {Inventory:[{Slot:30b,id:"minecraft:structure_block",Damage:0s}]}
execute @s[tag=!AirInSlot30] ~ ~ ~ execute @s[tag=!StoneInSlot30] ~ ~ ~ execute @s[tag=!GraniteInSlot30] ~ ~ ~ execute @s[tag=!PolishedGraniteInSlot30] ~ ~ ~ execute @s[tag=!DioriteInSlot30] ~ ~ ~ execute @s[tag=!PolishedDioriteInSlot30] ~ ~ ~ execute @s[tag=!AndesiteInSlot30] ~ ~ ~ execute @s[tag=!PolishedAndesiteInSlot30] ~ ~ ~ execute @s[tag=!GrassBlockInSlot30] ~ ~ ~ execute @s[tag=!DirtInSlot30] ~ ~ ~ execute @s[tag=!CoarseDirtInSlot30] ~ ~ ~ execute @s[tag=!PodzolInSlot30] ~ ~ ~ execute @s[tag=!CobblestoneInSlot30] ~ ~ ~ execute @s[tag=!OakWoodPlankInSlot30] ~ ~ ~ execute @s[tag=!SpruceWoodPlankInSlot30] ~ ~ ~ execute @s[tag=!BirchWoodPlankInSlot30] ~ ~ ~ execute @s[tag=!JungleWoodPlankInSlot30] ~ ~ ~ execute @s[tag=!AcaciaWoodPlankInSlot30] ~ ~ ~ execute @s[tag=!DarkOakWoodPlankInSlot30] ~ ~ ~ execute @s[tag=!OakSaplingInSlot30] ~ ~ ~ execute @s[tag=!SpruceSaplingInSlot30] ~ ~ ~ execute @s[tag=!BirchSaplingInSlot30] ~ ~ ~ execute @s[tag=!JungleSaplingInSlot30] ~ ~ ~ execute @s[tag=!AcaciaSaplingInSlot30] ~ ~ ~ execute @s[tag=!DarkOakSaplingInSlot30] ~ ~ ~ execute @s[tag=!BedrockInSlot30] ~ ~ ~ execute @s[tag=!FlowingWaterInSlot30] ~ ~ ~ execute @s[tag=!StillWaterInSlot30] ~ ~ ~ execute @s[tag=!FlowingLavaInSlot30] ~ ~ ~ execute @s[tag=!StillLavaInSlot30] ~ ~ ~ execute @s[tag=!SandInSlot30] ~ ~ ~ execute @s[tag=!RedSandInSlot30] ~ ~ ~ execute @s[tag=!GravelInSlot30] ~ ~ ~ execute @s[tag=!GoldOreInSlot30] ~ ~ ~ execute @s[tag=!IronOreInSlot30] ~ ~ ~ execute @s[tag=!CoalOreInSlot30] ~ ~ ~ execute @s[tag=!OakWoodInSlot30] ~ ~ ~ execute @s[tag=!SpruceWoodInSlot30] ~ ~ ~ execute @s[tag=!BirchWoodInSlot30] ~ ~ ~ execute @s[tag=!JungleWoodInSlot30] ~ ~ ~ execute @s[tag=!OakLeavesInSlot30] ~ ~ ~ execute @s[tag=!SpruceLeavesInSlot30] ~ ~ ~ execute @s[tag=!BirchLeavesInSlot30] ~ ~ ~ execute @s[tag=!JungleLeavesInSlot30] ~ ~ ~ execute @s[tag=!SpongeInSlot30] ~ ~ ~ execute @s[tag=!WetSpongeInSlot30] ~ ~ ~ execute @s[tag=!GlassInSlot30] ~ ~ ~ execute @s[tag=!LapisLazuliOreInSlot30] ~ ~ ~ execute @s[tag=!LapisLazuliBlockInSlot30] ~ ~ ~ execute @s[tag=!DispenserInSlot30] ~ ~ ~ execute @s[tag=!SandstoneInSlot30] ~ ~ ~ execute @s[tag=!ChiseledSandstoneInSlot30] ~ ~ ~ execute @s[tag=!SmoothSandstoneInSlot30] ~ ~ ~ execute @s[tag=!NoteBlockInSlot30] ~ ~ ~ execute @s[tag=!BedInSlot30] ~ ~ ~ execute @s[tag=!PoweredRailInSlot30] ~ ~ ~ execute @s[tag=!DetectorRailInSlot30] ~ ~ ~ execute @s[tag=!StickyPistonInSlot30] ~ ~ ~ execute @s[tag=!CobwebInSlot30] ~ ~ ~ execute @s[tag=!DeadShrubInSlot30] ~ ~ ~ execute @s[tag=!GrassInSlot30] ~ ~ ~ execute @s[tag=!FernInSlot30] ~ ~ ~ execute @s[tag=!DeadBushInSlot30] ~ ~ ~ execute @s[tag=!PistonInSlot30] ~ ~ ~ execute @s[tag=!PistonHeadInSlot30] ~ ~ ~ execute @s[tag=!WhiteWoolInSlot30] ~ ~ ~ execute @s[tag=!OrangeWoolInSlot30] ~ ~ ~ execute @s[tag=!MagentaWoolInSlot30] ~ ~ ~ execute @s[tag=!LightBlueWoolInSlot30] ~ ~ ~ execute @s[tag=!YellowWoolInSlot30] ~ ~ ~ execute @s[tag=!LimeWoolInSlot30] ~ ~ ~ execute @s[tag=!PinkWoolInSlot30] ~ ~ ~ execute @s[tag=!GrayWoolInSlot30] ~ ~ ~ execute @s[tag=!LightGrayWoolInSlot30] ~ ~ ~ execute @s[tag=!CyanWoolInSlot30] ~ ~ ~ execute @s[tag=!PurpleWoolInSlot30] ~ ~ ~ execute @s[tag=!BlueWoolInSlot30] ~ ~ ~ execute @s[tag=!BrownWoolInSlot30] ~ ~ ~ execute @s[tag=!GreenWoolInSlot30] ~ ~ ~ execute @s[tag=!RedWoolInSlot30] ~ ~ ~ execute @s[tag=!BlackWoolInSlot30] ~ ~ ~ execute @s[tag=!DandelionInSlot30] ~ ~ ~ execute @s[tag=!PoppyInSlot30] ~ ~ ~ execute @s[tag=!BlueOrchidInSlot30] ~ ~ ~ execute @s[tag=!AlliumInSlot30] ~ ~ ~ execute @s[tag=!AzureBluetInSlot30] ~ ~ ~ execute @s[tag=!RedTulipInSlot30] ~ ~ ~ execute @s[tag=!OrangeTulipInSlot30] ~ ~ ~ execute @s[tag=!WhiteTulipInSlot30] ~ ~ ~ execute @s[tag=!PinkTulipInSlot30] ~ ~ ~ execute @s[tag=!OxeyeDaisyInSlot30] ~ ~ ~ execute @s[tag=!BrownMushroomInSlot30] ~ ~ ~ execute @s[tag=!RedMushroomInSlot30] ~ ~ ~ execute @s[tag=!GoldBlockInSlot30] ~ ~ ~ execute @s[tag=!IronBlockInSlot30] ~ ~ ~ execute @s[tag=!DoubleStoneSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleSandstoneSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleWoodenSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleCobblestoneSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleBrickSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleStoneBrickSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleNetherBrickSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleQuartzSlabInSlot30] ~ ~ ~ execute @s[tag=!StoneSlabInSlot30] ~ ~ ~ execute @s[tag=!SandstoneSlabInSlot30] ~ ~ ~ execute @s[tag=!WoodenSlabInSlot30] ~ ~ ~ execute @s[tag=!CobblestoneSlabInSlot30] ~ ~ ~ execute @s[tag=!BrickSlabInSlot30] ~ ~ ~ execute @s[tag=!StoneBrickSlabInSlot30] ~ ~ ~ execute @s[tag=!NetherBrickSlabInSlot30] ~ ~ ~ execute @s[tag=!QuartzSlabInSlot30] ~ ~ ~ execute @s[tag=!BricksInSlot30] ~ ~ ~ execute @s[tag=!TNTInSlot30] ~ ~ ~ execute @s[tag=!BookshelfInSlot30] ~ ~ ~ execute @s[tag=!MossStoneInSlot30] ~ ~ ~ execute @s[tag=!ObsidianInSlot30] ~ ~ ~ execute @s[tag=!TorchInSlot30] ~ ~ ~ execute @s[tag=!FireInSlot30] ~ ~ ~ execute @s[tag=!MonsterSpawnerInSlot30] ~ ~ ~ execute @s[tag=!OakWoodStairsInSlot30] ~ ~ ~ execute @s[tag=!ChestInSlot30] ~ ~ ~ execute @s[tag=!RedstoneWireInSlot30] ~ ~ ~ execute @s[tag=!DiamondOreInSlot30] ~ ~ ~ execute @s[tag=!DiamondBlockInSlot30] ~ ~ ~ execute @s[tag=!CraftingTableInSlot30] ~ ~ ~ execute @s[tag=!WheatCropsInSlot30] ~ ~ ~ execute @s[tag=!FarmlandInSlot30] ~ ~ ~ execute @s[tag=!FurnaceInSlot30] ~ ~ ~ execute @s[tag=!BurningFurnaceInSlot30] ~ ~ ~ execute @s[tag=!StandingSignBlockInSlot30] ~ ~ ~ execute @s[tag=!OakDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!LadderInSlot30] ~ ~ ~ execute @s[tag=!RailInSlot30] ~ ~ ~ execute @s[tag=!CobblestoneStairsInSlot30] ~ ~ ~ execute @s[tag=!Wall-mountedSignBlockInSlot30] ~ ~ ~ execute @s[tag=!LeverInSlot30] ~ ~ ~ execute @s[tag=!StonePressurePlateInSlot30] ~ ~ ~ execute @s[tag=!IronDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!WoodenPressurePlateInSlot30] ~ ~ ~ execute @s[tag=!RedstoneOreInSlot30] ~ ~ ~ execute @s[tag=!GlowingRedstoneOreInSlot30] ~ ~ ~ execute @s[tag=!RedstoneTorch(off)InSlot30] ~ ~ ~ execute @s[tag=!RedstoneTorch(on)InSlot30] ~ ~ ~ execute @s[tag=!StoneButtonInSlot30] ~ ~ ~ execute @s[tag=!SnowInSlot30] ~ ~ ~ execute @s[tag=!IceInSlot30] ~ ~ ~ execute @s[tag=!SnowBlockInSlot30] ~ ~ ~ execute @s[tag=!CactusInSlot30] ~ ~ ~ execute @s[tag=!SugarCanesInSlot30] ~ ~ ~ execute @s[tag=!JukeboxInSlot30] ~ ~ ~ execute @s[tag=!OakFenceInSlot30] ~ ~ ~ execute @s[tag=!PumpkinInSlot30] ~ ~ ~ execute @s[tag=!NetherrackInSlot30] ~ ~ ~ execute @s[tag=!SoulSandInSlot30] ~ ~ ~ execute @s[tag=!GlowstoneInSlot30] ~ ~ ~ execute @s[tag=!NetherPortalInSlot30] ~ ~ ~ execute @s[tag=!Jacko'LanternInSlot30] ~ ~ ~ execute @s[tag=!CakeBlockInSlot30] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(off)InSlot30] ~ ~ ~ execute @s[tag=!RedstoneRepeaterBlock(on)InSlot30] ~ ~ ~ execute @s[tag=!WhiteStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!OrangeStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!MagentaStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!YellowStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!LimeStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!PinkStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!GrayStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!CyanStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!PurpleStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!BlueStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!BrownStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!GreenStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!RedStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!BlackStainedGlassInSlot30] ~ ~ ~ execute @s[tag=!WoodenTrapdoorInSlot30] ~ ~ ~ execute @s[tag=!StoneMonsterEggInSlot30] ~ ~ ~ execute @s[tag=!CobblestoneMonsterEggInSlot30] ~ ~ ~ execute @s[tag=!StoneBrickMonsterEggInSlot30] ~ ~ ~ execute @s[tag=!MossyStoneBrickMonsterEggInSlot30] ~ ~ ~ execute @s[tag=!CrackedStoneBrickMonsterEggInSlot30] ~ ~ ~ execute @s[tag=!ChiseledStoneBrickMonsterEggInSlot30] ~ ~ ~ execute @s[tag=!StoneBricksInSlot30] ~ ~ ~ execute @s[tag=!MossyStoneBricksInSlot30] ~ ~ ~ execute @s[tag=!CrackedStoneBricksInSlot30] ~ ~ ~ execute @s[tag=!ChiseledStoneBricksInSlot30] ~ ~ ~ execute @s[tag=!BrownMushroomBlockInSlot30] ~ ~ ~ execute @s[tag=!RedMushroomBlockInSlot30] ~ ~ ~ execute @s[tag=!IronBarsInSlot30] ~ ~ ~ execute @s[tag=!GlassPaneInSlot30] ~ ~ ~ execute @s[tag=!MelonBlockInSlot30] ~ ~ ~ execute @s[tag=!PumpkinStemInSlot30] ~ ~ ~ execute @s[tag=!MelonStemInSlot30] ~ ~ ~ execute @s[tag=!VinesInSlot30] ~ ~ ~ execute @s[tag=!OakFenceGateInSlot30] ~ ~ ~ execute @s[tag=!BrickStairsInSlot30] ~ ~ ~ execute @s[tag=!StoneBrickStairsInSlot30] ~ ~ ~ execute @s[tag=!MyceliumInSlot30] ~ ~ ~ execute @s[tag=!LilyPadInSlot30] ~ ~ ~ execute @s[tag=!NetherBrickInSlot30] ~ ~ ~ execute @s[tag=!NetherBrickFenceInSlot30] ~ ~ ~ execute @s[tag=!NetherBrickStairsInSlot30] ~ ~ ~ execute @s[tag=!NetherWartInSlot30] ~ ~ ~ execute @s[tag=!EnchantmentTableInSlot30] ~ ~ ~ execute @s[tag=!BrewingStandInSlot30] ~ ~ ~ execute @s[tag=!CauldronInSlot30] ~ ~ ~ execute @s[tag=!EndPortalInSlot30] ~ ~ ~ execute @s[tag=!EndPortalFrameInSlot30] ~ ~ ~ execute @s[tag=!EndStoneInSlot30] ~ ~ ~ execute @s[tag=!DragonEggInSlot30] ~ ~ ~ execute @s[tag=!RedstoneLamp(inactive)InSlot30] ~ ~ ~ execute @s[tag=!RedstoneLamp(active)InSlot30] ~ ~ ~ execute @s[tag=!DoubleOakWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleSpruceWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleBirchWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleJungleWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleAcaciaWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!DoubleDarkOakWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!OakWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!SpruceWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!BirchWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!JungleWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!AcaciaWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!DarkOakWoodSlabInSlot30] ~ ~ ~ execute @s[tag=!CocoaInSlot30] ~ ~ ~ execute @s[tag=!SandstoneStairsInSlot30] ~ ~ ~ execute @s[tag=!EmeraldOreInSlot30] ~ ~ ~ execute @s[tag=!EnderChestInSlot30] ~ ~ ~ execute @s[tag=!TripwireHookInSlot30] ~ ~ ~ execute @s[tag=!TripwireInSlot30] ~ ~ ~ execute @s[tag=!EmeraldBlockInSlot30] ~ ~ ~ execute @s[tag=!SpruceWoodStairsInSlot30] ~ ~ ~ execute @s[tag=!BirchWoodStairsInSlot30] ~ ~ ~ execute @s[tag=!JungleWoodStairsInSlot30] ~ ~ ~ execute @s[tag=!CommandBlockInSlot30] ~ ~ ~ execute @s[tag=!BeaconInSlot30] ~ ~ ~ execute @s[tag=!CobblestoneWallInSlot30] ~ ~ ~ execute @s[tag=!MossyCobblestoneWallInSlot30] ~ ~ ~ execute @s[tag=!FlowerPotInSlot30] ~ ~ ~ execute @s[tag=!CarrotsInSlot30] ~ ~ ~ execute @s[tag=!PotatoesInSlot30] ~ ~ ~ execute @s[tag=!WoodenButtonInSlot30] ~ ~ ~ execute @s[tag=!MobHeadInSlot30] ~ ~ ~ execute @s[tag=!AnvilInSlot30] ~ ~ ~ execute @s[tag=!TrappedChestInSlot30] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(light)InSlot30] ~ ~ ~ execute @s[tag=!WeightedPressurePlate(heavy)InSlot30] ~ ~ ~ execute @s[tag=!RedstoneComparator(inactive)InSlot30] ~ ~ ~ execute @s[tag=!RedstoneComparator(active)InSlot30] ~ ~ ~ execute @s[tag=!DaylightSensorInSlot30] ~ ~ ~ execute @s[tag=!RedstoneBlockInSlot30] ~ ~ ~ execute @s[tag=!NetherQuartzOreInSlot30] ~ ~ ~ execute @s[tag=!HopperInSlot30] ~ ~ ~ execute @s[tag=!QuartzBlockInSlot30] ~ ~ ~ execute @s[tag=!ChiseledQuartzBlockInSlot30] ~ ~ ~ execute @s[tag=!PillarQuartzBlockInSlot30] ~ ~ ~ execute @s[tag=!QuartzStairsInSlot30] ~ ~ ~ execute @s[tag=!ActivatorRailInSlot30] ~ ~ ~ execute @s[tag=!DropperInSlot30] ~ ~ ~ execute @s[tag=!WhiteHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!OrangeHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!MagentaHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!LightBlueHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!YellowHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!LimeHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!PinkHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!GrayHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!LightGrayHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!CyanHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!PurpleHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!BlueHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!BrownHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!GreenHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!RedHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!BlackHardenedClayInSlot30] ~ ~ ~ execute @s[tag=!WhiteStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!OrangeStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!MagentaStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!LightBlueStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!YellowStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!LimeStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!PinkStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!GrayStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!LightGrayStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!CyanStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!PurpleStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!BlueStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!BrownStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!GreenStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!RedStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!BlackStainedGlassPaneInSlot30] ~ ~ ~ execute @s[tag=!AcaciaLeavesInSlot30] ~ ~ ~ execute @s[tag=!DarkOakLeavesInSlot30] ~ ~ ~ execute @s[tag=!AcaciaWoodInSlot30] ~ ~ ~ execute @s[tag=!DarkOakWoodInSlot30] ~ ~ ~ execute @s[tag=!AcaciaWoodStairsInSlot30] ~ ~ ~ execute @s[tag=!DarkOakWoodStairsInSlot30] ~ ~ ~ execute @s[tag=!SlimeBlockInSlot30] ~ ~ ~ execute @s[tag=!BarrierInSlot30] ~ ~ ~ execute @s[tag=!IronTrapdoorInSlot30] ~ ~ ~ execute @s[tag=!PrismarineInSlot30] ~ ~ ~ execute @s[tag=!PrismarineBricksInSlot30] ~ ~ ~ execute @s[tag=!DarkPrismarineInSlot30] ~ ~ ~ execute @s[tag=!SeaLanternInSlot30] ~ ~ ~ execute @s[tag=!HayBaleInSlot30] ~ ~ ~ execute @s[tag=!WhiteCarpetInSlot30] ~ ~ ~ execute @s[tag=!OrangeCarpetInSlot30] ~ ~ ~ execute @s[tag=!MagentaCarpetInSlot30] ~ ~ ~ execute @s[tag=!LightBlueCarpetInSlot30] ~ ~ ~ execute @s[tag=!YellowCarpetInSlot30] ~ ~ ~ execute @s[tag=!LimeCarpetInSlot30] ~ ~ ~ execute @s[tag=!PinkCarpetInSlot30] ~ ~ ~ execute @s[tag=!GrayCarpetInSlot30] ~ ~ ~ execute @s[tag=!LightGrayCarpetInSlot30] ~ ~ ~ execute @s[tag=!CyanCarpetInSlot30] ~ ~ ~ execute @s[tag=!PurpleCarpetInSlot30] ~ ~ ~ execute @s[tag=!BlueCarpetInSlot30] ~ ~ ~ execute @s[tag=!BrownCarpetInSlot30] ~ ~ ~ execute @s[tag=!GreenCarpetInSlot30] ~ ~ ~ execute @s[tag=!RedCarpetInSlot30] ~ ~ ~ execute @s[tag=!BlackCarpetInSlot30] ~ ~ ~ execute @s[tag=!HardenedClayInSlot30] ~ ~ ~ execute @s[tag=!BlockofCoalInSlot30] ~ ~ ~ execute @s[tag=!PackedIceInSlot30] ~ ~ ~ execute @s[tag=!SunflowerInSlot30] ~ ~ ~ execute @s[tag=!LilacInSlot30] ~ ~ ~ execute @s[tag=!DoubleTallgrassInSlot30] ~ ~ ~ execute @s[tag=!LargeFernInSlot30] ~ ~ ~ execute @s[tag=!RoseBushInSlot30] ~ ~ ~ execute @s[tag=!PeonyInSlot30] ~ ~ ~ execute @s[tag=!Free-standingBannerInSlot30] ~ ~ ~ execute @s[tag=!Wall-mountedBannerInSlot30] ~ ~ ~ execute @s[tag=!InvertedDaylightSensorInSlot30] ~ ~ ~ execute @s[tag=!RedSandstoneInSlot30] ~ ~ ~ execute @s[tag=!ChiseledRedSandstoneInSlot30] ~ ~ ~ execute @s[tag=!SmoothRedSandstoneInSlot30] ~ ~ ~ execute @s[tag=!RedSandstoneStairsInSlot30] ~ ~ ~ execute @s[tag=!DoubleRedSandstoneSlabInSlot30] ~ ~ ~ execute @s[tag=!RedSandstoneSlabInSlot30] ~ ~ ~ execute @s[tag=!SpruceFenceGateInSlot30] ~ ~ ~ execute @s[tag=!BirchFenceGateInSlot30] ~ ~ ~ execute @s[tag=!JungleFenceGateInSlot30] ~ ~ ~ execute @s[tag=!DarkOakFenceGateInSlot30] ~ ~ ~ execute @s[tag=!AcaciaFenceGateInSlot30] ~ ~ ~ execute @s[tag=!SpruceFenceInSlot30] ~ ~ ~ execute @s[tag=!BirchFenceInSlot30] ~ ~ ~ execute @s[tag=!JungleFenceInSlot30] ~ ~ ~ execute @s[tag=!DarkOakFenceInSlot30] ~ ~ ~ execute @s[tag=!AcaciaFenceInSlot30] ~ ~ ~ execute @s[tag=!SpruceDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!BirchDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!JungleDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!AcaciaDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!DarkOakDoorBlockInSlot30] ~ ~ ~ execute @s[tag=!EndRodInSlot30] ~ ~ ~ execute @s[tag=!ChorusPlantInSlot30] ~ ~ ~ execute @s[tag=!ChorusFlowerInSlot30] ~ ~ ~ execute @s[tag=!PurpurBlockInSlot30] ~ ~ ~ execute @s[tag=!PurpurPillarInSlot30] ~ ~ ~ execute @s[tag=!PurpurStairsInSlot30] ~ ~ ~ execute @s[tag=!PurpurDoubleSlabInSlot30] ~ ~ ~ execute @s[tag=!PurpurSlabInSlot30] ~ ~ ~ execute @s[tag=!EndStoneBricksInSlot30] ~ ~ ~ execute @s[tag=!BeetrootBlockInSlot30] ~ ~ ~ execute @s[tag=!GrassPathInSlot30] ~ ~ ~ execute @s[tag=!EndGatewayInSlot30] ~ ~ ~ execute @s[tag=!RepeatingCommandBlockInSlot30] ~ ~ ~ execute @s[tag=!ChainCommandBlockInSlot30] ~ ~ ~ execute @s[tag=!FrostedIceInSlot30] ~ ~ ~ execute @s[tag=!MagmaBlockInSlot30] ~ ~ ~ execute @s[tag=!NetherWartBlockInSlot30] ~ ~ ~ execute @s[tag=!RedNetherBrickInSlot30] ~ ~ ~ execute @s[tag=!BoneBlockInSlot30] ~ ~ ~ execute @s[tag=!StructureVoidInSlot30] ~ ~ ~ execute @s[tag=!ObserverInSlot30] ~ ~ ~ execute @s[tag=!WhiteShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!OrangeShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!MagentaShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!LightBlueShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!YellowShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!LimeShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!PinkShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!GrayShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!LightGrayShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!CyanShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!PurpleShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!BlueShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!BrownShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!GreenShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!RedShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!BlackShulkerBoxInSlot30] ~ ~ ~ execute @s[tag=!WhiteGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!OrangeGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!MagentaGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!LightBlueGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!YellowGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!LimeGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!PinkGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!GrayGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!LightGrayGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!CyanGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!PurpleGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!BlueGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!BrownGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!GreenGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!RedGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!BlackGlazedTerracottaInSlot30] ~ ~ ~ execute @s[tag=!WhiteConcreteInSlot30] ~ ~ ~ execute @s[tag=!OrangeConcreteInSlot30] ~ ~ ~ execute @s[tag=!MagentaConcreteInSlot30] ~ ~ ~ execute @s[tag=!LightBlueConcreteInSlot30] ~ ~ ~ execute @s[tag=!YellowConcreteInSlot30] ~ ~ ~ execute @s[tag=!LimeConcreteInSlot30] ~ ~ ~ execute @s[tag=!PinkConcreteInSlot30] ~ ~ ~ execute @s[tag=!GrayConcreteInSlot30] ~ ~ ~ execute @s[tag=!LightGrayConcreteInSlot30] ~ ~ ~ execute @s[tag=!CyanConcreteInSlot30] ~ ~ ~ execute @s[tag=!PurpleConcreteInSlot30] ~ ~ ~ execute @s[tag=!BlueConcreteInSlot30] ~ ~ ~ execute @s[tag=!BrownConcreteInSlot30] ~ ~ ~ execute @s[tag=!GreenConcreteInSlot30] ~ ~ ~ execute @s[tag=!RedConcreteInSlot30] ~ ~ ~ execute @s[tag=!BlackConcreteInSlot30] ~ ~ ~ execute @s[tag=!WhiteConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!OrangeConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!MagentaConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!LightBlueConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!YellowConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!LimeConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!PinkConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!GrayConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!LightGrayConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!CyanConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!PurpleConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!BlueConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!BrownConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!GreenConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!RedConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!BlackConcretePowderInSlot30] ~ ~ ~ execute @s[tag=!StructureBlockInSlot30] ~ ~ ~ scoreboard players tag @s add AirInSlot30 