scoreboard players tag @s add AirInSlot17 {Inventory:[{Slot:17b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot17 {Inventory:[{Slot:17b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot17 {Inventory:[{Slot:17b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot17 {Inventory:[{Slot:17b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot17 {Inventory:[{Slot:17b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot17 {Inventory:[{Slot:17b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot17 {Inventory:[{Slot:17b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot17 {Inventory:[{Slot:17b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot17 {Inventory:[{Slot:17b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot17 {Inventory:[{Slot:17b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot17 {Inventory:[{Slot:17b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot17 {Inventory:[{Slot:17b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot17 {Inventory:[{Slot:17b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot17 {Inventory:[{Slot:17b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot17 {Inventory:[{Slot:17b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot17 {Inventory:[{Slot:17b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot17 {Inventory:[{Slot:17b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot17 {Inventory:[{Slot:17b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot17 {Inventory:[{Slot:17b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot17 {Inventory:[{Slot:17b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot17 {Inventory:[{Slot:17b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot17 {Inventory:[{Slot:17b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot17 {Inventory:[{Slot:17b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot17 {Inventory:[{Slot:17b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot17 {Inventory:[{Slot:17b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot17 {Inventory:[{Slot:17b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot17 {Inventory:[{Slot:17b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot17 {Inventory:[{Slot:17b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot17 {Inventory:[{Slot:17b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot17 {Inventory:[{Slot:17b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot17 {Inventory:[{Slot:17b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot17 {Inventory:[{Slot:17b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot17 {Inventory:[{Slot:17b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot17 {Inventory:[{Slot:17b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot17 {Inventory:[{Slot:17b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot17 {Inventory:[{Slot:17b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot17 {Inventory:[{Slot:17b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot17 {Inventory:[{Slot:17b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot17 {Inventory:[{Slot:17b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot17 {Inventory:[{Slot:17b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot17 {Inventory:[{Slot:17b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot17 {Inventory:[{Slot:17b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot17 {Inventory:[{Slot:17b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot17 {Inventory:[{Slot:17b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot17 {Inventory:[{Slot:17b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot17 {Inventory:[{Slot:17b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot17 {Inventory:[{Slot:17b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot17 {Inventory:[{Slot:17b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot17 {Inventory:[{Slot:17b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot17 {Inventory:[{Slot:17b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot17 {Inventory:[{Slot:17b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot17 {Inventory:[{Slot:17b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot17 {Inventory:[{Slot:17b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot17 {Inventory:[{Slot:17b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot17 {Inventory:[{Slot:17b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot17 {Inventory:[{Slot:17b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot17 {Inventory:[{Slot:17b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot17 {Inventory:[{Slot:17b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot17 {Inventory:[{Slot:17b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot17 {Inventory:[{Slot:17b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot17 {Inventory:[{Slot:17b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot17 {Inventory:[{Slot:17b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot17 {Inventory:[{Slot:17b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot17 {Inventory:[{Slot:17b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot17 {Inventory:[{Slot:17b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot17 {Inventory:[{Slot:17b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot17 {Inventory:[{Slot:17b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot17 {Inventory:[{Slot:17b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot17 {Inventory:[{Slot:17b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot17 {Inventory:[{Slot:17b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot17 {Inventory:[{Slot:17b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot17 {Inventory:[{Slot:17b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot17 {Inventory:[{Slot:17b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot17 {Inventory:[{Slot:17b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot17 {Inventory:[{Slot:17b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot17 {Inventory:[{Slot:17b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot17 {Inventory:[{Slot:17b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot17 {Inventory:[{Slot:17b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot17 {Inventory:[{Slot:17b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot17 {Inventory:[{Slot:17b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot17 {Inventory:[{Slot:17b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot17 {Inventory:[{Slot:17b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot17 {Inventory:[{Slot:17b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot17 {Inventory:[{Slot:17b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot17 {Inventory:[{Slot:17b,id:"minecraft:structure_block",Damage:0s}]}
