scoreboard players tag @a add AirInSlot20 {Inventory:[{Slot:20b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot20 {Inventory:[{Slot:20b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot20 {Inventory:[{Slot:20b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot20 {Inventory:[{Slot:20b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot20 {Inventory:[{Slot:20b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot20 {Inventory:[{Slot:20b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot20 {Inventory:[{Slot:20b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot20 {Inventory:[{Slot:20b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot20 {Inventory:[{Slot:20b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot20 {Inventory:[{Slot:20b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot20 {Inventory:[{Slot:20b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot20 {Inventory:[{Slot:20b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot20 {Inventory:[{Slot:20b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot20 {Inventory:[{Slot:20b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot20 {Inventory:[{Slot:20b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot20 {Inventory:[{Slot:20b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot20 {Inventory:[{Slot:20b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot20 {Inventory:[{Slot:20b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot20 {Inventory:[{Slot:20b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot20 {Inventory:[{Slot:20b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot20 {Inventory:[{Slot:20b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot20 {Inventory:[{Slot:20b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot20 {Inventory:[{Slot:20b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot20 {Inventory:[{Slot:20b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot20 {Inventory:[{Slot:20b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot20 {Inventory:[{Slot:20b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot20 {Inventory:[{Slot:20b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot20 {Inventory:[{Slot:20b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot20 {Inventory:[{Slot:20b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot20 {Inventory:[{Slot:20b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot20 {Inventory:[{Slot:20b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot20 {Inventory:[{Slot:20b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot20 {Inventory:[{Slot:20b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot20 {Inventory:[{Slot:20b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot20 {Inventory:[{Slot:20b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot20 {Inventory:[{Slot:20b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot20 {Inventory:[{Slot:20b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot20 {Inventory:[{Slot:20b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot20 {Inventory:[{Slot:20b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot20 {Inventory:[{Slot:20b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot20 {Inventory:[{Slot:20b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot20 {Inventory:[{Slot:20b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot20 {Inventory:[{Slot:20b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot20 {Inventory:[{Slot:20b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot20 {Inventory:[{Slot:20b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot20 {Inventory:[{Slot:20b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot20 {Inventory:[{Slot:20b,id:"minecraft:structure_block",Damage:0s}]}
