scoreboard players tag @a add AirInSlot22 {Inventory:[{Slot:22b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot22 {Inventory:[{Slot:22b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot22 {Inventory:[{Slot:22b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot22 {Inventory:[{Slot:22b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot22 {Inventory:[{Slot:22b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot22 {Inventory:[{Slot:22b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot22 {Inventory:[{Slot:22b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot22 {Inventory:[{Slot:22b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot22 {Inventory:[{Slot:22b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot22 {Inventory:[{Slot:22b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot22 {Inventory:[{Slot:22b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot22 {Inventory:[{Slot:22b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot22 {Inventory:[{Slot:22b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot22 {Inventory:[{Slot:22b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot22 {Inventory:[{Slot:22b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot22 {Inventory:[{Slot:22b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot22 {Inventory:[{Slot:22b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot22 {Inventory:[{Slot:22b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot22 {Inventory:[{Slot:22b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot22 {Inventory:[{Slot:22b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot22 {Inventory:[{Slot:22b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot22 {Inventory:[{Slot:22b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot22 {Inventory:[{Slot:22b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot22 {Inventory:[{Slot:22b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot22 {Inventory:[{Slot:22b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot22 {Inventory:[{Slot:22b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot22 {Inventory:[{Slot:22b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot22 {Inventory:[{Slot:22b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot22 {Inventory:[{Slot:22b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot22 {Inventory:[{Slot:22b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot22 {Inventory:[{Slot:22b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot22 {Inventory:[{Slot:22b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot22 {Inventory:[{Slot:22b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot22 {Inventory:[{Slot:22b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot22 {Inventory:[{Slot:22b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot22 {Inventory:[{Slot:22b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot22 {Inventory:[{Slot:22b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot22 {Inventory:[{Slot:22b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot22 {Inventory:[{Slot:22b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot22 {Inventory:[{Slot:22b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot22 {Inventory:[{Slot:22b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot22 {Inventory:[{Slot:22b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot22 {Inventory:[{Slot:22b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot22 {Inventory:[{Slot:22b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot22 {Inventory:[{Slot:22b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot22 {Inventory:[{Slot:22b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot22 {Inventory:[{Slot:22b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot22 {Inventory:[{Slot:22b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot22 {Inventory:[{Slot:22b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot22 {Inventory:[{Slot:22b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot22 {Inventory:[{Slot:22b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot22 {Inventory:[{Slot:22b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot22 {Inventory:[{Slot:22b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot22 {Inventory:[{Slot:22b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot22 {Inventory:[{Slot:22b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot22 {Inventory:[{Slot:22b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot22 {Inventory:[{Slot:22b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot22 {Inventory:[{Slot:22b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot22 {Inventory:[{Slot:22b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot22 {Inventory:[{Slot:22b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot22 {Inventory:[{Slot:22b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot22 {Inventory:[{Slot:22b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot22 {Inventory:[{Slot:22b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot22 {Inventory:[{Slot:22b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot22 {Inventory:[{Slot:22b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot22 {Inventory:[{Slot:22b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot22 {Inventory:[{Slot:22b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot22 {Inventory:[{Slot:22b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot22 {Inventory:[{Slot:22b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot22 {Inventory:[{Slot:22b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot22 {Inventory:[{Slot:22b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot22 {Inventory:[{Slot:22b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot22 {Inventory:[{Slot:22b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot22 {Inventory:[{Slot:22b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot22 {Inventory:[{Slot:22b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot22 {Inventory:[{Slot:22b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot22 {Inventory:[{Slot:22b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot22 {Inventory:[{Slot:22b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot22 {Inventory:[{Slot:22b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot22 {Inventory:[{Slot:22b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot22 {Inventory:[{Slot:22b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot22 {Inventory:[{Slot:22b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot22 {Inventory:[{Slot:22b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot22 {Inventory:[{Slot:22b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot22 {Inventory:[{Slot:22b,id:"minecraft:structure_block",Damage:0s}]}
