scoreboard players tag @a add AirInSlot2 {Inventory:[{Slot:2b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot2 {Inventory:[{Slot:2b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot2 {Inventory:[{Slot:2b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot2 {Inventory:[{Slot:2b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot2 {Inventory:[{Slot:2b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot2 {Inventory:[{Slot:2b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot2 {Inventory:[{Slot:2b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot2 {Inventory:[{Slot:2b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot2 {Inventory:[{Slot:2b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot2 {Inventory:[{Slot:2b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot2 {Inventory:[{Slot:2b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot2 {Inventory:[{Slot:2b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot2 {Inventory:[{Slot:2b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot2 {Inventory:[{Slot:2b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot2 {Inventory:[{Slot:2b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot2 {Inventory:[{Slot:2b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot2 {Inventory:[{Slot:2b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot2 {Inventory:[{Slot:2b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot2 {Inventory:[{Slot:2b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot2 {Inventory:[{Slot:2b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot2 {Inventory:[{Slot:2b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot2 {Inventory:[{Slot:2b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot2 {Inventory:[{Slot:2b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot2 {Inventory:[{Slot:2b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot2 {Inventory:[{Slot:2b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot2 {Inventory:[{Slot:2b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot2 {Inventory:[{Slot:2b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot2 {Inventory:[{Slot:2b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot2 {Inventory:[{Slot:2b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot2 {Inventory:[{Slot:2b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot2 {Inventory:[{Slot:2b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot2 {Inventory:[{Slot:2b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot2 {Inventory:[{Slot:2b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot2 {Inventory:[{Slot:2b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot2 {Inventory:[{Slot:2b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot2 {Inventory:[{Slot:2b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot2 {Inventory:[{Slot:2b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot2 {Inventory:[{Slot:2b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot2 {Inventory:[{Slot:2b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot2 {Inventory:[{Slot:2b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot2 {Inventory:[{Slot:2b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot2 {Inventory:[{Slot:2b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot2 {Inventory:[{Slot:2b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot2 {Inventory:[{Slot:2b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot2 {Inventory:[{Slot:2b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot2 {Inventory:[{Slot:2b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot2 {Inventory:[{Slot:2b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot2 {Inventory:[{Slot:2b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot2 {Inventory:[{Slot:2b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot2 {Inventory:[{Slot:2b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot2 {Inventory:[{Slot:2b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot2 {Inventory:[{Slot:2b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot2 {Inventory:[{Slot:2b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot2 {Inventory:[{Slot:2b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot2 {Inventory:[{Slot:2b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot2 {Inventory:[{Slot:2b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot2 {Inventory:[{Slot:2b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot2 {Inventory:[{Slot:2b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot2 {Inventory:[{Slot:2b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot2 {Inventory:[{Slot:2b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot2 {Inventory:[{Slot:2b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot2 {Inventory:[{Slot:2b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot2 {Inventory:[{Slot:2b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot2 {Inventory:[{Slot:2b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot2 {Inventory:[{Slot:2b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot2 {Inventory:[{Slot:2b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot2 {Inventory:[{Slot:2b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot2 {Inventory:[{Slot:2b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot2 {Inventory:[{Slot:2b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot2 {Inventory:[{Slot:2b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot2 {Inventory:[{Slot:2b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot2 {Inventory:[{Slot:2b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot2 {Inventory:[{Slot:2b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot2 {Inventory:[{Slot:2b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot2 {Inventory:[{Slot:2b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot2 {Inventory:[{Slot:2b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot2 {Inventory:[{Slot:2b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot2 {Inventory:[{Slot:2b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot2 {Inventory:[{Slot:2b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot2 {Inventory:[{Slot:2b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot2 {Inventory:[{Slot:2b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot2 {Inventory:[{Slot:2b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot2 {Inventory:[{Slot:2b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot2 {Inventory:[{Slot:2b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot2 {Inventory:[{Slot:2b,id:"minecraft:structure_block",Damage:0s}]}
