scoreboard players tag @s add AirInSlot21 {Inventory:[{Slot:21b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @s add StoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @s add GraniteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @s add PolishedGraniteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @s add DioriteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @s add PolishedDioriteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @s add AndesiteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @s add PolishedAndesiteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @s add GrassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @s add DirtInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @s add CoarseDirtInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @s add PodzolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @s add CobblestoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @s add OakWoodPlankInSlot21 {Inventory:[{Slot:21b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @s add SpruceWoodPlankInSlot21 {Inventory:[{Slot:21b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @s add BirchWoodPlankInSlot21 {Inventory:[{Slot:21b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @s add JungleWoodPlankInSlot21 {Inventory:[{Slot:21b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodPlankInSlot21 {Inventory:[{Slot:21b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodPlankInSlot21 {Inventory:[{Slot:21b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @s add OakSaplingInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @s add SpruceSaplingInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @s add BirchSaplingInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @s add JungleSaplingInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @s add AcaciaSaplingInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @s add DarkOakSaplingInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @s add BedrockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @s add FlowingWaterInSlot21 {Inventory:[{Slot:21b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @s add StillWaterInSlot21 {Inventory:[{Slot:21b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @s add FlowingLavaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @s add StillLavaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @s add SandInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @s add RedSandInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @s add GravelInSlot21 {Inventory:[{Slot:21b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @s add GoldOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @s add IronOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @s add CoalOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @s add OakWoodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @s add SpruceWoodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @s add BirchWoodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @s add JungleWoodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @s add OakLeavesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @s add SpruceLeavesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @s add BirchLeavesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @s add JungleLeavesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @s add SpongeInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @s add WetSpongeInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @s add GlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @s add LapisLazuliOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @s add LapisLazuliBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @s add DispenserInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @s add SandstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledSandstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothSandstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @s add NoteBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @s add BedInSlot21 {Inventory:[{Slot:21b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @s add PoweredRailInSlot21 {Inventory:[{Slot:21b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @s add DetectorRailInSlot21 {Inventory:[{Slot:21b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @s add StickyPistonInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @s add CobwebInSlot21 {Inventory:[{Slot:21b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @s add DeadShrubInSlot21 {Inventory:[{Slot:21b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @s add GrassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @s add FernInSlot21 {Inventory:[{Slot:21b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @s add DeadBushInSlot21 {Inventory:[{Slot:21b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @s add PistonInSlot21 {Inventory:[{Slot:21b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @s add PistonHeadInSlot21 {Inventory:[{Slot:21b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @s add WhiteWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @s add OrangeWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @s add MagentaWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @s add LightBlueWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @s add YellowWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @s add LimeWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @s add PinkWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @s add GrayWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @s add LightGrayWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @s add CyanWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @s add PurpleWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @s add BlueWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @s add BrownWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @s add GreenWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @s add RedWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @s add BlackWoolInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @s add DandelionInSlot21 {Inventory:[{Slot:21b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @s add PoppyInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @s add BlueOrchidInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @s add AlliumInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @s add AzureBluetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @s add RedTulipInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @s add OrangeTulipInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @s add WhiteTulipInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @s add PinkTulipInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @s add OxeyeDaisyInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @s add BrownMushroomInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @s add RedMushroomInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @s add GoldBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @s add IronBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @s add DoubleStoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSandstoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @s add DoubleWoodenSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @s add DoubleCobblestoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @s add DoubleBrickSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @s add DoubleStoneBrickSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @s add DoubleNetherBrickSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @s add DoubleQuartzSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @s add StoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @s add SandstoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @s add WoodenSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @s add CobblestoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @s add BrickSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @s add StoneBrickSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @s add NetherBrickSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @s add QuartzSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @s add BricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @s add TNTInSlot21 {Inventory:[{Slot:21b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @s add BookshelfInSlot21 {Inventory:[{Slot:21b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @s add MossStoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @s add ObsidianInSlot21 {Inventory:[{Slot:21b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @s add TorchInSlot21 {Inventory:[{Slot:21b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @s add FireInSlot21 {Inventory:[{Slot:21b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @s add MonsterSpawnerInSlot21 {Inventory:[{Slot:21b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @s add OakWoodStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @s add ChestInSlot21 {Inventory:[{Slot:21b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @s add RedstoneWireInSlot21 {Inventory:[{Slot:21b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @s add DiamondOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @s add DiamondBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @s add CraftingTableInSlot21 {Inventory:[{Slot:21b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @s add WheatCropsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @s add FarmlandInSlot21 {Inventory:[{Slot:21b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @s add FurnaceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @s add BurningFurnaceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @s add StandingSignBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @s add OakDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @s add LadderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @s add RailInSlot21 {Inventory:[{Slot:21b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @s add CobblestoneStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @s add Wall-mountedSignBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @s add LeverInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @s add StonePressurePlateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @s add IronDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @s add WoodenPressurePlateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @s add GlowingRedstoneOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(off)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @s add RedstoneTorch(on)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @s add StoneButtonInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @s add SnowInSlot21 {Inventory:[{Slot:21b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @s add IceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @s add SnowBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @s add CactusInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @s add SugarCanesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @s add JukeboxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @s add OakFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @s add PumpkinInSlot21 {Inventory:[{Slot:21b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @s add NetherrackInSlot21 {Inventory:[{Slot:21b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @s add SoulSandInSlot21 {Inventory:[{Slot:21b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @s add GlowstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @s add NetherPortalInSlot21 {Inventory:[{Slot:21b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @s add Jacko'LanternInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @s add CakeBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(off)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @s add RedstoneRepeaterBlock(on)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @s add WhiteStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @s add WoodenTrapdoorInSlot21 {Inventory:[{Slot:21b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @s add StoneMonsterEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @s add CobblestoneMonsterEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @s add StoneBrickMonsterEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @s add MossyStoneBrickMonsterEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @s add CrackedStoneBrickMonsterEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @s add ChiseledStoneBrickMonsterEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @s add StoneBricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @s add MossyStoneBricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @s add CrackedStoneBricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @s add ChiseledStoneBricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @s add BrownMushroomBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @s add RedMushroomBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @s add IronBarsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @s add GlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @s add MelonBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @s add PumpkinStemInSlot21 {Inventory:[{Slot:21b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @s add MelonStemInSlot21 {Inventory:[{Slot:21b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @s add VinesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @s add OakFenceGateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @s add BrickStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @s add StoneBrickStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @s add MyceliumInSlot21 {Inventory:[{Slot:21b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @s add LilyPadInSlot21 {Inventory:[{Slot:21b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @s add NetherBrickInSlot21 {Inventory:[{Slot:21b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @s add NetherBrickFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @s add NetherBrickStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @s add NetherWartInSlot21 {Inventory:[{Slot:21b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @s add EnchantmentTableInSlot21 {Inventory:[{Slot:21b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @s add BrewingStandInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @s add CauldronInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @s add EndPortalInSlot21 {Inventory:[{Slot:21b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @s add EndPortalFrameInSlot21 {Inventory:[{Slot:21b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @s add EndStoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @s add DragonEggInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(inactive)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @s add RedstoneLamp(active)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @s add DoubleOakWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @s add DoubleSpruceWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @s add DoubleBirchWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @s add DoubleJungleWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @s add DoubleAcaciaWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @s add DoubleDarkOakWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @s add OakWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @s add SpruceWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @s add BirchWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @s add JungleWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @s add AcaciaWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @s add DarkOakWoodSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @s add CocoaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @s add SandstoneStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add EmeraldOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @s add EnderChestInSlot21 {Inventory:[{Slot:21b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @s add TripwireHookInSlot21 {Inventory:[{Slot:21b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add TripwireInSlot21 {Inventory:[{Slot:21b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @s add EmeraldBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @s add SpruceWoodStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @s add BirchWoodStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @s add JungleWoodStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @s add CommandBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @s add BeaconInSlot21 {Inventory:[{Slot:21b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @s add CobblestoneWallInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @s add MossyCobblestoneWallInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @s add FlowerPotInSlot21 {Inventory:[{Slot:21b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @s add CarrotsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @s add PotatoesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @s add WoodenButtonInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @s add MobHeadInSlot21 {Inventory:[{Slot:21b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @s add AnvilInSlot21 {Inventory:[{Slot:21b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @s add TrappedChestInSlot21 {Inventory:[{Slot:21b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(light)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add WeightedPressurePlate(heavy)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(inactive)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @s add RedstoneComparator(active)InSlot21 {Inventory:[{Slot:21b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @s add DaylightSensorInSlot21 {Inventory:[{Slot:21b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @s add RedstoneBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @s add NetherQuartzOreInSlot21 {Inventory:[{Slot:21b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @s add HopperInSlot21 {Inventory:[{Slot:21b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @s add QuartzBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @s add ChiseledQuartzBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @s add PillarQuartzBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @s add QuartzStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @s add ActivatorRailInSlot21 {Inventory:[{Slot:21b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @s add DropperInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @s add WhiteHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @s add OrangeHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @s add MagentaHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @s add LightBlueHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @s add YellowHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @s add LimeHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @s add PinkHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @s add GrayHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @s add LightGrayHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @s add CyanHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @s add PurpleHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @s add BlueHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @s add BrownHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @s add GreenHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @s add RedHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @s add BlackHardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @s add WhiteStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @s add OrangeStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @s add MagentaStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @s add LightBlueStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @s add YellowStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @s add LimeStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @s add PinkStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @s add GrayStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @s add LightGrayStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @s add CyanStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @s add PurpleStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @s add BlueStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @s add BrownStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @s add GreenStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @s add RedStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @s add BlackStainedGlassPaneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @s add AcaciaLeavesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @s add DarkOakLeavesInSlot21 {Inventory:[{Slot:21b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @s add AcaciaWoodStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @s add DarkOakWoodStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @s add SlimeBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @s add BarrierInSlot21 {Inventory:[{Slot:21b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @s add IronTrapdoorInSlot21 {Inventory:[{Slot:21b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @s add PrismarineInSlot21 {Inventory:[{Slot:21b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @s add PrismarineBricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @s add DarkPrismarineInSlot21 {Inventory:[{Slot:21b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @s add SeaLanternInSlot21 {Inventory:[{Slot:21b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @s add HayBaleInSlot21 {Inventory:[{Slot:21b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @s add WhiteCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @s add OrangeCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @s add MagentaCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @s add LightBlueCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @s add YellowCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @s add LimeCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @s add PinkCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @s add GrayCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @s add LightGrayCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @s add CyanCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @s add PurpleCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @s add BlueCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @s add BrownCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @s add GreenCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @s add RedCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @s add BlackCarpetInSlot21 {Inventory:[{Slot:21b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @s add HardenedClayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @s add BlockofCoalInSlot21 {Inventory:[{Slot:21b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @s add PackedIceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @s add SunflowerInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @s add LilacInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @s add DoubleTallgrassInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @s add LargeFernInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @s add RoseBushInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @s add PeonyInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @s add Free-standingBannerInSlot21 {Inventory:[{Slot:21b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @s add Wall-mountedBannerInSlot21 {Inventory:[{Slot:21b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @s add InvertedDaylightSensorInSlot21 {Inventory:[{Slot:21b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @s add RedSandstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @s add ChiseledRedSandstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @s add SmoothRedSandstoneInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @s add RedSandstoneStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @s add DoubleRedSandstoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @s add RedSandstoneSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @s add SpruceFenceGateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @s add BirchFenceGateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @s add JungleFenceGateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceGateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceGateInSlot21 {Inventory:[{Slot:21b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @s add SpruceFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @s add BirchFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @s add JungleFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @s add DarkOakFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @s add AcaciaFenceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @s add SpruceDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @s add BirchDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @s add JungleDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @s add AcaciaDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @s add DarkOakDoorBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @s add EndRodInSlot21 {Inventory:[{Slot:21b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @s add ChorusPlantInSlot21 {Inventory:[{Slot:21b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @s add ChorusFlowerInSlot21 {Inventory:[{Slot:21b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @s add PurpurBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @s add PurpurPillarInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @s add PurpurStairsInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @s add PurpurDoubleSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @s add PurpurSlabInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @s add EndStoneBricksInSlot21 {Inventory:[{Slot:21b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @s add BeetrootBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @s add GrassPathInSlot21 {Inventory:[{Slot:21b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @s add EndGatewayInSlot21 {Inventory:[{Slot:21b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @s add RepeatingCommandBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @s add ChainCommandBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @s add FrostedIceInSlot21 {Inventory:[{Slot:21b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @s add MagmaBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @s add NetherWartBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @s add RedNetherBrickInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @s add BoneBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @s add StructureVoidInSlot21 {Inventory:[{Slot:21b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @s add ObserverInSlot21 {Inventory:[{Slot:21b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @s add WhiteShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @s add OrangeShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @s add MagentaShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightBlueShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add YellowShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @s add LimeShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @s add PinkShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @s add GrayShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @s add LightGrayShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @s add CyanShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @s add PurpleShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlueShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @s add BrownShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @s add GreenShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @s add RedShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @s add BlackShulkerBoxInSlot21 {Inventory:[{Slot:21b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @s add WhiteGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add OrangeGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add MagentaGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightBlueGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add YellowGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LimeGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PinkGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GrayGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add LightGrayGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add CyanGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add PurpleGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlueGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BrownGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add GreenGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add RedGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add BlackGlazedTerracottaInSlot21 {Inventory:[{Slot:21b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @s add WhiteConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @s add OrangeConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @s add MagentaConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @s add LightBlueConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @s add YellowConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @s add LimeConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @s add PinkConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @s add GrayConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @s add LightGrayConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @s add CyanConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @s add PurpleConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @s add BlueConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @s add BrownConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @s add GreenConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @s add RedConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @s add BlackConcreteInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @s add WhiteConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @s add OrangeConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @s add MagentaConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @s add LightBlueConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @s add YellowConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @s add LimeConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @s add PinkConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @s add GrayConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @s add LightGrayConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @s add CyanConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @s add PurpleConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @s add BlueConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @s add BrownConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @s add GreenConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @s add RedConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @s add BlackConcretePowderInSlot21 {Inventory:[{Slot:21b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @s add StructureBlockInSlot21 {Inventory:[{Slot:21b,id:"minecraft:structure_block",Damage:0s}]}
