scoreboard players tag @a add AirInSlot7 {Inventory:[{Slot:7b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot7 {Inventory:[{Slot:7b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot7 {Inventory:[{Slot:7b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot7 {Inventory:[{Slot:7b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot7 {Inventory:[{Slot:7b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot7 {Inventory:[{Slot:7b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot7 {Inventory:[{Slot:7b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot7 {Inventory:[{Slot:7b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot7 {Inventory:[{Slot:7b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot7 {Inventory:[{Slot:7b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot7 {Inventory:[{Slot:7b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot7 {Inventory:[{Slot:7b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot7 {Inventory:[{Slot:7b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot7 {Inventory:[{Slot:7b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot7 {Inventory:[{Slot:7b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot7 {Inventory:[{Slot:7b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot7 {Inventory:[{Slot:7b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot7 {Inventory:[{Slot:7b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot7 {Inventory:[{Slot:7b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot7 {Inventory:[{Slot:7b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot7 {Inventory:[{Slot:7b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot7 {Inventory:[{Slot:7b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot7 {Inventory:[{Slot:7b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot7 {Inventory:[{Slot:7b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot7 {Inventory:[{Slot:7b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot7 {Inventory:[{Slot:7b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot7 {Inventory:[{Slot:7b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot7 {Inventory:[{Slot:7b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot7 {Inventory:[{Slot:7b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot7 {Inventory:[{Slot:7b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot7 {Inventory:[{Slot:7b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot7 {Inventory:[{Slot:7b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot7 {Inventory:[{Slot:7b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot7 {Inventory:[{Slot:7b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot7 {Inventory:[{Slot:7b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot7 {Inventory:[{Slot:7b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot7 {Inventory:[{Slot:7b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot7 {Inventory:[{Slot:7b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot7 {Inventory:[{Slot:7b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot7 {Inventory:[{Slot:7b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot7 {Inventory:[{Slot:7b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot7 {Inventory:[{Slot:7b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot7 {Inventory:[{Slot:7b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot7 {Inventory:[{Slot:7b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot7 {Inventory:[{Slot:7b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot7 {Inventory:[{Slot:7b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot7 {Inventory:[{Slot:7b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot7 {Inventory:[{Slot:7b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot7 {Inventory:[{Slot:7b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot7 {Inventory:[{Slot:7b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot7 {Inventory:[{Slot:7b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot7 {Inventory:[{Slot:7b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot7 {Inventory:[{Slot:7b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot7 {Inventory:[{Slot:7b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot7 {Inventory:[{Slot:7b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot7 {Inventory:[{Slot:7b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot7 {Inventory:[{Slot:7b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot7 {Inventory:[{Slot:7b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot7 {Inventory:[{Slot:7b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot7 {Inventory:[{Slot:7b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot7 {Inventory:[{Slot:7b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot7 {Inventory:[{Slot:7b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot7 {Inventory:[{Slot:7b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot7 {Inventory:[{Slot:7b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot7 {Inventory:[{Slot:7b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot7 {Inventory:[{Slot:7b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot7 {Inventory:[{Slot:7b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot7 {Inventory:[{Slot:7b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot7 {Inventory:[{Slot:7b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot7 {Inventory:[{Slot:7b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot7 {Inventory:[{Slot:7b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot7 {Inventory:[{Slot:7b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot7 {Inventory:[{Slot:7b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot7 {Inventory:[{Slot:7b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot7 {Inventory:[{Slot:7b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot7 {Inventory:[{Slot:7b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot7 {Inventory:[{Slot:7b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot7 {Inventory:[{Slot:7b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot7 {Inventory:[{Slot:7b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot7 {Inventory:[{Slot:7b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot7 {Inventory:[{Slot:7b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot7 {Inventory:[{Slot:7b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot7 {Inventory:[{Slot:7b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot7 {Inventory:[{Slot:7b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot7 {Inventory:[{Slot:7b,id:"minecraft:structure_block",Damage:0s}]}
