scoreboard players tag @a add AirInSlot3 {Inventory:[{Slot:3b,id:"minecraft:air",Damage:0s}]}
scoreboard players tag @a add StoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:0s}]}
scoreboard players tag @a add GraniteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:1s}]}
scoreboard players tag @a add PolishedGraniteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:2s}]}
scoreboard players tag @a add DioriteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:3s}]}
scoreboard players tag @a add PolishedDioriteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:4s}]}
scoreboard players tag @a add AndesiteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:5s}]}
scoreboard players tag @a add PolishedAndesiteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone",Damage:6s}]}
scoreboard players tag @a add GrassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:grass",Damage:0s}]}
scoreboard players tag @a add DirtInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dirt",Damage:0s}]}
scoreboard players tag @a add CoarseDirtInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dirt",Damage:1s}]}
scoreboard players tag @a add PodzolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dirt",Damage:2s}]}
scoreboard players tag @a add CobblestoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cobblestone",Damage:0s}]}
scoreboard players tag @a add OakWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:0s}]}
scoreboard players tag @a add SpruceWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:1s}]}
scoreboard players tag @a add BirchWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:2s}]}
scoreboard players tag @a add JungleWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodPlankInSlot3 {Inventory:[{Slot:3b,id:"minecraft:planks",Damage:5s}]}
scoreboard players tag @a add OakSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:0s}]}
scoreboard players tag @a add SpruceSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:1s}]}
scoreboard players tag @a add BirchSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:2s}]}
scoreboard players tag @a add JungleSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:3s}]}
scoreboard players tag @a add AcaciaSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:4s}]}
scoreboard players tag @a add DarkOakSaplingInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sapling",Damage:5s}]}
scoreboard players tag @a add BedrockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bedrock",Damage:0s}]}
scoreboard players tag @a add FlowingWaterInSlot3 {Inventory:[{Slot:3b,id:"minecraft:flowing_water",Damage:0s}]}
scoreboard players tag @a add StillWaterInSlot3 {Inventory:[{Slot:3b,id:"minecraft:water",Damage:0s}]}
scoreboard players tag @a add FlowingLavaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:flowing_lava",Damage:0s}]}
scoreboard players tag @a add StillLavaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lava",Damage:0s}]}
scoreboard players tag @a add SandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sand",Damage:0s}]}
scoreboard players tag @a add RedSandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sand",Damage:1s}]}
scoreboard players tag @a add GravelInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gravel",Damage:0s}]}
scoreboard players tag @a add GoldOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gold_ore",Damage:0s}]}
scoreboard players tag @a add IronOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_ore",Damage:0s}]}
scoreboard players tag @a add CoalOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:coal_ore",Damage:0s}]}
scoreboard players tag @a add OakWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:0s}]}
scoreboard players tag @a add SpruceWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:1s}]}
scoreboard players tag @a add BirchWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:2s}]}
scoreboard players tag @a add JungleWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log",Damage:3s}]}
scoreboard players tag @a add OakLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:0s}]}
scoreboard players tag @a add SpruceLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:1s}]}
scoreboard players tag @a add BirchLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:2s}]}
scoreboard players tag @a add JungleLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves",Damage:3s}]}
scoreboard players tag @a add SpongeInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sponge",Damage:0s}]}
scoreboard players tag @a add WetSpongeInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sponge",Damage:1s}]}
scoreboard players tag @a add GlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:glass",Damage:0s}]}
scoreboard players tag @a add LapisLazuliOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lapis_ore",Damage:0s}]}
scoreboard players tag @a add LapisLazuliBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lapis_block",Damage:0s}]}
scoreboard players tag @a add DispenserInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dispenser",Damage:0s}]}
scoreboard players tag @a add SandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone",Damage:2s}]}
scoreboard players tag @a add NoteBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:noteblock",Damage:0s}]}
scoreboard players tag @a add BedInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bed",Damage:0s}]}
scoreboard players tag @a add PoweredRailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:golden_rail",Damage:0s}]}
scoreboard players tag @a add DetectorRailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:detector_rail",Damage:0s}]}
scoreboard players tag @a add StickyPistonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sticky_piston",Damage:0s}]}
scoreboard players tag @a add CobwebInSlot3 {Inventory:[{Slot:3b,id:"minecraft:web",Damage:0s}]}
scoreboard players tag @a add DeadShrubInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tallgrass",Damage:0s}]}
scoreboard players tag @a add GrassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tallgrass",Damage:1s}]}
scoreboard players tag @a add FernInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tallgrass",Damage:2s}]}
scoreboard players tag @a add DeadBushInSlot3 {Inventory:[{Slot:3b,id:"minecraft:deadbush",Damage:0s}]}
scoreboard players tag @a add PistonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:piston",Damage:0s}]}
scoreboard players tag @a add PistonHeadInSlot3 {Inventory:[{Slot:3b,id:"minecraft:piston_head",Damage:0s}]}
scoreboard players tag @a add WhiteWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:0s}]}
scoreboard players tag @a add OrangeWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:1s}]}
scoreboard players tag @a add MagentaWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:2s}]}
scoreboard players tag @a add LightBlueWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:3s}]}
scoreboard players tag @a add YellowWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:4s}]}
scoreboard players tag @a add LimeWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:5s}]}
scoreboard players tag @a add PinkWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:6s}]}
scoreboard players tag @a add GrayWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:7s}]}
scoreboard players tag @a add LightGrayWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:8s}]}
scoreboard players tag @a add CyanWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:9s}]}
scoreboard players tag @a add PurpleWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:10s}]}
scoreboard players tag @a add BlueWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:11s}]}
scoreboard players tag @a add BrownWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:12s}]}
scoreboard players tag @a add GreenWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:13s}]}
scoreboard players tag @a add RedWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:14s}]}
scoreboard players tag @a add BlackWoolInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wool",Damage:15s}]}
scoreboard players tag @a add DandelionInSlot3 {Inventory:[{Slot:3b,id:"minecraft:yellow_flower",Damage:0s}]}
scoreboard players tag @a add PoppyInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:0s}]}
scoreboard players tag @a add BlueOrchidInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:1s}]}
scoreboard players tag @a add AlliumInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:2s}]}
scoreboard players tag @a add AzureBluetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:3s}]}
scoreboard players tag @a add RedTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:4s}]}
scoreboard players tag @a add OrangeTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:5s}]}
scoreboard players tag @a add WhiteTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:6s}]}
scoreboard players tag @a add PinkTulipInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:7s}]}
scoreboard players tag @a add OxeyeDaisyInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_flower",Damage:8s}]}
scoreboard players tag @a add BrownMushroomInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_mushroom",Damage:0s}]}
scoreboard players tag @a add RedMushroomInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_mushroom",Damage:0s}]}
scoreboard players tag @a add GoldBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gold_block",Damage:0s}]}
scoreboard players tag @a add IronBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_block",Damage:0s}]}
scoreboard players tag @a add DoubleStoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:1s}]}
scoreboard players tag @a add DoubleWoodenSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:2s}]}
scoreboard players tag @a add DoubleCobblestoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:3s}]}
scoreboard players tag @a add DoubleBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:4s}]}
scoreboard players tag @a add DoubleStoneBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:5s}]}
scoreboard players tag @a add DoubleNetherBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:6s}]}
scoreboard players tag @a add DoubleQuartzSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab",Damage:7s}]}
scoreboard players tag @a add StoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:0s}]}
scoreboard players tag @a add SandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:1s}]}
scoreboard players tag @a add WoodenSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:2s}]}
scoreboard players tag @a add CobblestoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:3s}]}
scoreboard players tag @a add BrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:4s}]}
scoreboard players tag @a add StoneBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:5s}]}
scoreboard players tag @a add NetherBrickSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:6s}]}
scoreboard players tag @a add QuartzSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab",Damage:7s}]}
scoreboard players tag @a add BricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brick_block",Damage:0s}]}
scoreboard players tag @a add TNTInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tnt",Damage:0s}]}
scoreboard players tag @a add BookshelfInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bookshelf",Damage:0s}]}
scoreboard players tag @a add MossStoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:mossy_cobblestone",Damage:0s}]}
scoreboard players tag @a add ObsidianInSlot3 {Inventory:[{Slot:3b,id:"minecraft:obsidian",Damage:0s}]}
scoreboard players tag @a add TorchInSlot3 {Inventory:[{Slot:3b,id:"minecraft:torch",Damage:0s}]}
scoreboard players tag @a add FireInSlot3 {Inventory:[{Slot:3b,id:"minecraft:fire",Damage:0s}]}
scoreboard players tag @a add MonsterSpawnerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:mob_spawner",Damage:0s}]}
scoreboard players tag @a add OakWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:oak_stairs",Damage:0s}]}
scoreboard players tag @a add ChestInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chest",Damage:0s}]}
scoreboard players tag @a add RedstoneWireInSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_wire",Damage:0s}]}
scoreboard players tag @a add DiamondOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:diamond_ore",Damage:0s}]}
scoreboard players tag @a add DiamondBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:diamond_block",Damage:0s}]}
scoreboard players tag @a add CraftingTableInSlot3 {Inventory:[{Slot:3b,id:"minecraft:crafting_table",Damage:0s}]}
scoreboard players tag @a add WheatCropsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wheat",Damage:0s}]}
scoreboard players tag @a add FarmlandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:farmland",Damage:0s}]}
scoreboard players tag @a add FurnaceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:furnace",Damage:0s}]}
scoreboard players tag @a add BurningFurnaceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_furnace",Damage:0s}]}
scoreboard players tag @a add StandingSignBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:standing_sign",Damage:0s}]}
scoreboard players tag @a add OakDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_door",Damage:0s}]}
scoreboard players tag @a add LadderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:ladder",Damage:0s}]}
scoreboard players tag @a add RailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:rail",Damage:0s}]}
scoreboard players tag @a add CobblestoneStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_stairs",Damage:0s}]}
scoreboard players tag @a add Wall-mountedSignBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wall_sign",Damage:0s}]}
scoreboard players tag @a add LeverInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lever",Damage:0s}]}
scoreboard players tag @a add StonePressurePlateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_pressure_plate",Damage:0s}]}
scoreboard players tag @a add IronDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_door",Damage:0s}]}
scoreboard players tag @a add WoodenPressurePlateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_ore",Damage:0s}]}
scoreboard players tag @a add GlowingRedstoneOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_redstone_ore",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(off)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:unlit_redstone_torch",Damage:0s}]}
scoreboard players tag @a add RedstoneTorch(on)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_torch",Damage:0s}]}
scoreboard players tag @a add StoneButtonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_button",Damage:0s}]}
scoreboard players tag @a add SnowInSlot3 {Inventory:[{Slot:3b,id:"minecraft:snow_layer",Damage:0s}]}
scoreboard players tag @a add IceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:ice",Damage:0s}]}
scoreboard players tag @a add SnowBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:snow",Damage:0s}]}
scoreboard players tag @a add CactusInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cactus",Damage:0s}]}
scoreboard players tag @a add SugarCanesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:reeds",Damage:0s}]}
scoreboard players tag @a add JukeboxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jukebox",Damage:0s}]}
scoreboard players tag @a add OakFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:fence",Damage:0s}]}
scoreboard players tag @a add PumpkinInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pumpkin",Damage:0s}]}
scoreboard players tag @a add NetherrackInSlot3 {Inventory:[{Slot:3b,id:"minecraft:netherrack",Damage:0s}]}
scoreboard players tag @a add SoulSandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:soul_sand",Damage:0s}]}
scoreboard players tag @a add GlowstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:glowstone",Damage:0s}]}
scoreboard players tag @a add NetherPortalInSlot3 {Inventory:[{Slot:3b,id:"minecraft:portal",Damage:0s}]}
scoreboard players tag @a add Jacko'LanternInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_pumpkin",Damage:0s}]}
scoreboard players tag @a add CakeBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cake",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(off)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:unpowered_repeater",Damage:0s}]}
scoreboard players tag @a add RedstoneRepeaterBlock(on)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:powered_repeater",Damage:0s}]}
scoreboard players tag @a add WhiteStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass",Damage:15s}]}
scoreboard players tag @a add WoodenTrapdoorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:trapdoor",Damage:0s}]}
scoreboard players tag @a add StoneMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:0s}]}
scoreboard players tag @a add CobblestoneMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:1s}]}
scoreboard players tag @a add StoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:2s}]}
scoreboard players tag @a add MossyStoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:3s}]}
scoreboard players tag @a add CrackedStoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:4s}]}
scoreboard players tag @a add ChiseledStoneBrickMonsterEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:monster_egg",Damage:5s}]}
scoreboard players tag @a add StoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:0s}]}
scoreboard players tag @a add MossyStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:1s}]}
scoreboard players tag @a add CrackedStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:2s}]}
scoreboard players tag @a add ChiseledStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stonebrick",Damage:3s}]}
scoreboard players tag @a add BrownMushroomBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_mushroom_block",Damage:0s}]}
scoreboard players tag @a add RedMushroomBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_mushroom_block",Damage:0s}]}
scoreboard players tag @a add IronBarsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_bars",Damage:0s}]}
scoreboard players tag @a add GlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:glass_pane",Damage:0s}]}
scoreboard players tag @a add MelonBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:melon_block",Damage:0s}]}
scoreboard players tag @a add PumpkinStemInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pumpkin_stem",Damage:0s}]}
scoreboard players tag @a add MelonStemInSlot3 {Inventory:[{Slot:3b,id:"minecraft:melon_stem",Damage:0s}]}
scoreboard players tag @a add VinesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:vine",Damage:0s}]}
scoreboard players tag @a add OakFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:fence_gate",Damage:0s}]}
scoreboard players tag @a add BrickStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brick_stairs",Damage:0s}]}
scoreboard players tag @a add StoneBrickStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_brick_stairs",Damage:0s}]}
scoreboard players tag @a add MyceliumInSlot3 {Inventory:[{Slot:3b,id:"minecraft:mycelium",Damage:0s}]}
scoreboard players tag @a add LilyPadInSlot3 {Inventory:[{Slot:3b,id:"minecraft:waterlily",Damage:0s}]}
scoreboard players tag @a add NetherBrickInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_brick",Damage:0s}]}
scoreboard players tag @a add NetherBrickFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_brick_fence",Damage:0s}]}
scoreboard players tag @a add NetherBrickStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_brick_stairs",Damage:0s}]}
scoreboard players tag @a add NetherWartInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_wart",Damage:0s}]}
scoreboard players tag @a add EnchantmentTableInSlot3 {Inventory:[{Slot:3b,id:"minecraft:enchanting_table",Damage:0s}]}
scoreboard players tag @a add BrewingStandInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brewing_stand",Damage:0s}]}
scoreboard players tag @a add CauldronInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cauldron",Damage:0s}]}
scoreboard players tag @a add EndPortalInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_portal",Damage:0s}]}
scoreboard players tag @a add EndPortalFrameInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_portal_frame",Damage:0s}]}
scoreboard players tag @a add EndStoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_stone",Damage:0s}]}
scoreboard players tag @a add DragonEggInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dragon_egg",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(inactive)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_lamp",Damage:0s}]}
scoreboard players tag @a add RedstoneLamp(active)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:lit_redstone_lamp",Damage:0s}]}
scoreboard players tag @a add DoubleOakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:0s}]}
scoreboard players tag @a add DoubleSpruceWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:1s}]}
scoreboard players tag @a add DoubleBirchWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:2s}]}
scoreboard players tag @a add DoubleJungleWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:3s}]}
scoreboard players tag @a add DoubleAcaciaWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:4s}]}
scoreboard players tag @a add DoubleDarkOakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_wooden_slab",Damage:5s}]}
scoreboard players tag @a add OakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:0s}]}
scoreboard players tag @a add SpruceWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:1s}]}
scoreboard players tag @a add BirchWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:2s}]}
scoreboard players tag @a add JungleWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:3s}]}
scoreboard players tag @a add AcaciaWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:4s}]}
scoreboard players tag @a add DarkOakWoodSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_slab",Damage:5s}]}
scoreboard players tag @a add CocoaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cocoa",Damage:0s}]}
scoreboard players tag @a add SandstoneStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add EmeraldOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:emerald_ore",Damage:0s}]}
scoreboard players tag @a add EnderChestInSlot3 {Inventory:[{Slot:3b,id:"minecraft:ender_chest",Damage:0s}]}
scoreboard players tag @a add TripwireHookInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add TripwireInSlot3 {Inventory:[{Slot:3b,id:"minecraft:tripwire_hook",Damage:0s}]}
scoreboard players tag @a add EmeraldBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:emerald_block",Damage:0s}]}
scoreboard players tag @a add SpruceWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_stairs",Damage:0s}]}
scoreboard players tag @a add BirchWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_stairs",Damage:0s}]}
scoreboard players tag @a add JungleWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_stairs",Damage:0s}]}
scoreboard players tag @a add CommandBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:command_block",Damage:0s}]}
scoreboard players tag @a add BeaconInSlot3 {Inventory:[{Slot:3b,id:"minecraft:beacon",Damage:0s}]}
scoreboard players tag @a add CobblestoneWallInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cobblestone_wall",Damage:0s}]}
scoreboard players tag @a add MossyCobblestoneWallInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cobblestone_wall",Damage:1s}]}
scoreboard players tag @a add FlowerPotInSlot3 {Inventory:[{Slot:3b,id:"minecraft:flower_pot",Damage:0s}]}
scoreboard players tag @a add CarrotsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carrots",Damage:0s}]}
scoreboard players tag @a add PotatoesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:potatoes",Damage:0s}]}
scoreboard players tag @a add WoodenButtonInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wooden_button",Damage:0s}]}
scoreboard players tag @a add MobHeadInSlot3 {Inventory:[{Slot:3b,id:"minecraft:skull",Damage:0s}]}
scoreboard players tag @a add AnvilInSlot3 {Inventory:[{Slot:3b,id:"minecraft:anvil",Damage:0s}]}
scoreboard players tag @a add TrappedChestInSlot3 {Inventory:[{Slot:3b,id:"minecraft:trapped_chest",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(light)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add WeightedPressurePlate(heavy)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:heavy_weighted_pressure_plate",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(inactive)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:unpowered_comparator",Damage:0s}]}
scoreboard players tag @a add RedstoneComparator(active)InSlot3 {Inventory:[{Slot:3b,id:"minecraft:powered_comparator",Damage:0s}]}
scoreboard players tag @a add DaylightSensorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:daylight_detector",Damage:0s}]}
scoreboard players tag @a add RedstoneBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:redstone_block",Damage:0s}]}
scoreboard players tag @a add NetherQuartzOreInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_ore",Damage:0s}]}
scoreboard players tag @a add HopperInSlot3 {Inventory:[{Slot:3b,id:"minecraft:hopper",Damage:0s}]}
scoreboard players tag @a add QuartzBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_block",Damage:0s}]}
scoreboard players tag @a add ChiseledQuartzBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_block",Damage:1s}]}
scoreboard players tag @a add PillarQuartzBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_block",Damage:2s}]}
scoreboard players tag @a add QuartzStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:quartz_stairs",Damage:0s}]}
scoreboard players tag @a add ActivatorRailInSlot3 {Inventory:[{Slot:3b,id:"minecraft:activator_rail",Damage:0s}]}
scoreboard players tag @a add DropperInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dropper",Damage:0s}]}
scoreboard players tag @a add WhiteHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:0s}]}
scoreboard players tag @a add OrangeHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:1s}]}
scoreboard players tag @a add MagentaHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:2s}]}
scoreboard players tag @a add LightBlueHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:3s}]}
scoreboard players tag @a add YellowHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:4s}]}
scoreboard players tag @a add LimeHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:5s}]}
scoreboard players tag @a add PinkHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:6s}]}
scoreboard players tag @a add GrayHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:7s}]}
scoreboard players tag @a add LightGrayHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:8s}]}
scoreboard players tag @a add CyanHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:9s}]}
scoreboard players tag @a add PurpleHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:10s}]}
scoreboard players tag @a add BlueHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:11s}]}
scoreboard players tag @a add BrownHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:12s}]}
scoreboard players tag @a add GreenHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:13s}]}
scoreboard players tag @a add RedHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:14s}]}
scoreboard players tag @a add BlackHardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_hardened_clay",Damage:15s}]}
scoreboard players tag @a add WhiteStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:0s}]}
scoreboard players tag @a add OrangeStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:1s}]}
scoreboard players tag @a add MagentaStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:2s}]}
scoreboard players tag @a add LightBlueStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:3s}]}
scoreboard players tag @a add YellowStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:4s}]}
scoreboard players tag @a add LimeStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:5s}]}
scoreboard players tag @a add PinkStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:6s}]}
scoreboard players tag @a add GrayStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:7s}]}
scoreboard players tag @a add LightGrayStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:8s}]}
scoreboard players tag @a add CyanStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:9s}]}
scoreboard players tag @a add PurpleStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:10s}]}
scoreboard players tag @a add BlueStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:11s}]}
scoreboard players tag @a add BrownStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:12s}]}
scoreboard players tag @a add GreenStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:13s}]}
scoreboard players tag @a add RedStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:14s}]}
scoreboard players tag @a add BlackStainedGlassPaneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stained_glass_pane",Damage:15s}]}
scoreboard players tag @a add AcaciaLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves2",Damage:0s}]}
scoreboard players tag @a add DarkOakLeavesInSlot3 {Inventory:[{Slot:3b,id:"minecraft:leaves2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log2",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:log2",Damage:1s}]}
scoreboard players tag @a add AcaciaWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_stairs",Damage:0s}]}
scoreboard players tag @a add DarkOakWoodStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_stairs",Damage:0s}]}
scoreboard players tag @a add SlimeBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:slime",Damage:0s}]}
scoreboard players tag @a add BarrierInSlot3 {Inventory:[{Slot:3b,id:"minecraft:barrier",Damage:0s}]}
scoreboard players tag @a add IronTrapdoorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:iron_trapdoor",Damage:0s}]}
scoreboard players tag @a add PrismarineInSlot3 {Inventory:[{Slot:3b,id:"minecraft:prismarine",Damage:0s}]}
scoreboard players tag @a add PrismarineBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:prismarine",Damage:1s}]}
scoreboard players tag @a add DarkPrismarineInSlot3 {Inventory:[{Slot:3b,id:"minecraft:prismarine",Damage:2s}]}
scoreboard players tag @a add SeaLanternInSlot3 {Inventory:[{Slot:3b,id:"minecraft:sea_lantern",Damage:0s}]}
scoreboard players tag @a add HayBaleInSlot3 {Inventory:[{Slot:3b,id:"minecraft:hay_block",Damage:0s}]}
scoreboard players tag @a add WhiteCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:0s}]}
scoreboard players tag @a add OrangeCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:1s}]}
scoreboard players tag @a add MagentaCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:2s}]}
scoreboard players tag @a add LightBlueCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:3s}]}
scoreboard players tag @a add YellowCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:4s}]}
scoreboard players tag @a add LimeCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:5s}]}
scoreboard players tag @a add PinkCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:6s}]}
scoreboard players tag @a add GrayCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:7s}]}
scoreboard players tag @a add LightGrayCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:8s}]}
scoreboard players tag @a add CyanCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:9s}]}
scoreboard players tag @a add PurpleCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:10s}]}
scoreboard players tag @a add BlueCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:11s}]}
scoreboard players tag @a add BrownCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:12s}]}
scoreboard players tag @a add GreenCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:13s}]}
scoreboard players tag @a add RedCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:14s}]}
scoreboard players tag @a add BlackCarpetInSlot3 {Inventory:[{Slot:3b,id:"minecraft:carpet",Damage:15s}]}
scoreboard players tag @a add HardenedClayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:hardened_clay",Damage:0s}]}
scoreboard players tag @a add BlockofCoalInSlot3 {Inventory:[{Slot:3b,id:"minecraft:coal_block",Damage:0s}]}
scoreboard players tag @a add PackedIceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:packed_ice",Damage:0s}]}
scoreboard players tag @a add SunflowerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:0s}]}
scoreboard players tag @a add LilacInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:1s}]}
scoreboard players tag @a add DoubleTallgrassInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:2s}]}
scoreboard players tag @a add LargeFernInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:3s}]}
scoreboard players tag @a add RoseBushInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:4s}]}
scoreboard players tag @a add PeonyInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_plant",Damage:5s}]}
scoreboard players tag @a add Free-standingBannerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:standing_banner",Damage:0s}]}
scoreboard players tag @a add Wall-mountedBannerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:wall_banner",Damage:0s}]}
scoreboard players tag @a add InvertedDaylightSensorInSlot3 {Inventory:[{Slot:3b,id:"minecraft:daylight_detector_inverted",Damage:0s}]}
scoreboard players tag @a add RedSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone",Damage:0s}]}
scoreboard players tag @a add ChiseledRedSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone",Damage:1s}]}
scoreboard players tag @a add SmoothRedSandstoneInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone",Damage:2s}]}
scoreboard players tag @a add RedSandstoneStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_sandstone_stairs",Damage:0s}]}
scoreboard players tag @a add DoubleRedSandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:double_stone_slab2",Damage:0s}]}
scoreboard players tag @a add RedSandstoneSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:stone_slab2",Damage:0s}]}
scoreboard players tag @a add SpruceFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_fence_gate",Damage:0s}]}
scoreboard players tag @a add BirchFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_fence_gate",Damage:0s}]}
scoreboard players tag @a add JungleFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_fence_gate",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_fence_gate",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceGateInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_fence_gate",Damage:0s}]}
scoreboard players tag @a add SpruceFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_fence",Damage:0s}]}
scoreboard players tag @a add BirchFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_fence",Damage:0s}]}
scoreboard players tag @a add JungleFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_fence",Damage:0s}]}
scoreboard players tag @a add DarkOakFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_fence",Damage:0s}]}
scoreboard players tag @a add AcaciaFenceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_fence",Damage:0s}]}
scoreboard players tag @a add SpruceDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:spruce_door",Damage:0s}]}
scoreboard players tag @a add BirchDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:birch_door",Damage:0s}]}
scoreboard players tag @a add JungleDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:jungle_door",Damage:0s}]}
scoreboard players tag @a add AcaciaDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:acacia_door",Damage:0s}]}
scoreboard players tag @a add DarkOakDoorBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:dark_oak_door",Damage:0s}]}
scoreboard players tag @a add EndRodInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_rod",Damage:0s}]}
scoreboard players tag @a add ChorusPlantInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chorus_plant",Damage:0s}]}
scoreboard players tag @a add ChorusFlowerInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chorus_flower",Damage:0s}]}
scoreboard players tag @a add PurpurBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_block",Damage:0s}]}
scoreboard players tag @a add PurpurPillarInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_pillar",Damage:0s}]}
scoreboard players tag @a add PurpurStairsInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_stairs",Damage:0s}]}
scoreboard players tag @a add PurpurDoubleSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_double_slab",Damage:0s}]}
scoreboard players tag @a add PurpurSlabInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purpur_slab",Damage:0s}]}
scoreboard players tag @a add EndStoneBricksInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_bricks",Damage:0s}]}
scoreboard players tag @a add BeetrootBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:beetroots",Damage:0s}]}
scoreboard players tag @a add GrassPathInSlot3 {Inventory:[{Slot:3b,id:"minecraft:grass_path",Damage:0s}]}
scoreboard players tag @a add EndGatewayInSlot3 {Inventory:[{Slot:3b,id:"minecraft:end_gateway",Damage:0s}]}
scoreboard players tag @a add RepeatingCommandBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:repeating_command_block",Damage:0s}]}
scoreboard players tag @a add ChainCommandBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:chain_command_block",Damage:0s}]}
scoreboard players tag @a add FrostedIceInSlot3 {Inventory:[{Slot:3b,id:"minecraft:frosted_ice",Damage:0s}]}
scoreboard players tag @a add MagmaBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:magma",Damage:0s}]}
scoreboard players tag @a add NetherWartBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:nether_wart_block",Damage:0s}]}
scoreboard players tag @a add RedNetherBrickInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_nether_brick",Damage:0s}]}
scoreboard players tag @a add BoneBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:bone_block",Damage:0s}]}
scoreboard players tag @a add StructureVoidInSlot3 {Inventory:[{Slot:3b,id:"minecraft:structure_void",Damage:0s}]}
scoreboard players tag @a add ObserverInSlot3 {Inventory:[{Slot:3b,id:"minecraft:observer",Damage:0s}]}
scoreboard players tag @a add WhiteShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:white_shulker_box",Damage:0s}]}
scoreboard players tag @a add OrangeShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:orange_shulker_box",Damage:0s}]}
scoreboard players tag @a add MagentaShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:magenta_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightBlueShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add YellowShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:yellow_shulker_box",Damage:0s}]}
scoreboard players tag @a add LimeShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lime_shulker_box",Damage:0s}]}
scoreboard players tag @a add PinkShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pink_shulker_box",Damage:0s}]}
scoreboard players tag @a add GrayShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gray_shulker_box",Damage:0s}]}
scoreboard players tag @a add LightGrayShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:silver_shulker_box",Damage:0s}]}
scoreboard players tag @a add CyanShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cyan_shulker_box",Damage:0s}]}
scoreboard players tag @a add PurpleShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purple_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlueShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:blue_shulker_box",Damage:0s}]}
scoreboard players tag @a add BrownShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_shulker_box",Damage:0s}]}
scoreboard players tag @a add GreenShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:green_shulker_box",Damage:0s}]}
scoreboard players tag @a add RedShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_shulker_box",Damage:0s}]}
scoreboard players tag @a add BlackShulkerBoxInSlot3 {Inventory:[{Slot:3b,id:"minecraft:black_shulker_box",Damage:0s}]}
scoreboard players tag @a add WhiteGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:white_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add OrangeGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:orange_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add MagentaGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:magenta_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightBlueGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add YellowGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:yellow_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LimeGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:lime_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PinkGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:pink_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GrayGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add LightGrayGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:light_gray_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add CyanGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:cyan_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add PurpleGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:purple_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlueGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:blue_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BrownGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:brown_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add GreenGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:green_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add RedGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:red_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add BlackGlazedTerracottaInSlot3 {Inventory:[{Slot:3b,id:"minecraft:black_glazed_terracotta",Damage:0s}]}
scoreboard players tag @a add WhiteConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:0s}]}
scoreboard players tag @a add OrangeConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:1s}]}
scoreboard players tag @a add MagentaConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:2s}]}
scoreboard players tag @a add LightBlueConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:3s}]}
scoreboard players tag @a add YellowConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:4s}]}
scoreboard players tag @a add LimeConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:5s}]}
scoreboard players tag @a add PinkConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:6s}]}
scoreboard players tag @a add GrayConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:7s}]}
scoreboard players tag @a add LightGrayConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:8s}]}
scoreboard players tag @a add CyanConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:9s}]}
scoreboard players tag @a add PurpleConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:10s}]}
scoreboard players tag @a add BlueConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:11s}]}
scoreboard players tag @a add BrownConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:12s}]}
scoreboard players tag @a add GreenConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:13s}]}
scoreboard players tag @a add RedConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:14s}]}
scoreboard players tag @a add BlackConcreteInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete",Damage:15s}]}
scoreboard players tag @a add WhiteConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:0s}]}
scoreboard players tag @a add OrangeConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:1s}]}
scoreboard players tag @a add MagentaConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:2s}]}
scoreboard players tag @a add LightBlueConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:3s}]}
scoreboard players tag @a add YellowConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:4s}]}
scoreboard players tag @a add LimeConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:5s}]}
scoreboard players tag @a add PinkConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:6s}]}
scoreboard players tag @a add GrayConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:7s}]}
scoreboard players tag @a add LightGrayConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:8s}]}
scoreboard players tag @a add CyanConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:9s}]}
scoreboard players tag @a add PurpleConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:10s}]}
scoreboard players tag @a add BlueConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:11s}]}
scoreboard players tag @a add BrownConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:12s}]}
scoreboard players tag @a add GreenConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:13s}]}
scoreboard players tag @a add RedConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:14s}]}
scoreboard players tag @a add BlackConcretePowderInSlot3 {Inventory:[{Slot:3b,id:"minecraft:concrete_powder",Damage:15s}]}
scoreboard players tag @a add StructureBlockInSlot3 {Inventory:[{Slot:3b,id:"minecraft:structure_block",Damage:0s}]}
