execute @s[tag=editBlock1] ~ ~ ~ execute @e[name=block1Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block1Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock1] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block1","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock2] ~ ~ ~ execute @e[name=block2Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block2Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock2] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block2","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock3] ~ ~ ~ execute @e[name=block3Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block3Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock3] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block3","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock4] ~ ~ ~ execute @e[name=block4Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block4Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock4] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block4","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock5] ~ ~ ~ execute @e[name=block5Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block5Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock5] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block5","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock6] ~ ~ ~ execute @e[name=block6Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block6Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock6] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block6","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock7] ~ ~ ~ execute @e[name=block7Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block7Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock7] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block7","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock8] ~ ~ ~ execute @e[name=block8Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block8Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock8] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block8","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock9] ~ ~ ~ execute @e[name=block9Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block9Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock9] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block9","objective":"Loot"},"color":"none"}]
execute @s[tag=editBlock10] ~ ~ ~ execute @e[name=block10Memory,tag=Slot7IsLootBlock] ~ ~ ~ scoreboard players add @a UIcurrentLine 1
execute @e[name=block10Memory,tag=Slot7IsLootBlock] ~ ~ ~ tellraw @a[tag=editBlock10] ["",{"text":"     "},{"text":" <= ","color":"white","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/prev/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}}},{"text":" => ","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:block_placer/tags/toggleLoot/next/slot7"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click","color":"white"}]}},"color":"none"},{"text":"Loot Table: ","color":"gray"},{"score":{"name":"slot7Block10","objective":"Loot"},"color":"none"}]
