function block_placer:tags/inventoryTest/clear_hotbar_slot_tags
function block_placer:tags/inventoryTest/slots/slot0
function block_placer:tags/inventoryTest/slots/slot1
function block_placer:tags/inventoryTest/slots/slot2
function block_placer:tags/inventoryTest/slots/slot3
function block_placer:tags/inventoryTest/slots/slot4
function block_placer:tags/inventoryTest/slots/slot5
function block_placer:tags/inventoryTest/slots/slot6
function block_placer:tags/inventoryTest/slots/slot7
function block_placer:tags/inventoryTest/slots/slot8
